// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generate.proto

package generate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 台账数据
type GenerateConfig struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	DatastoreId          string   `protobuf:"bytes,3,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	ApiKey               string   `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key"`
	DatastoreName        string   `protobuf:"bytes,5,opt,name=datastore_name,json=datastoreName,proto3" json:"datastore_name"`
	CanCheck             bool     `protobuf:"varint,6,opt,name=can_check,json=canCheck,proto3" json:"can_check"`
	Fields               []*Field `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields"`
	MappingId            string   `protobuf:"bytes,8,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id"`
	Step                 int64    `protobuf:"varint,9,opt,name=step,proto3" json:"step"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateConfig) Reset()         { *m = GenerateConfig{} }
func (m *GenerateConfig) String() string { return proto.CompactTextString(m) }
func (*GenerateConfig) ProtoMessage()    {}
func (*GenerateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{0}
}

func (m *GenerateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateConfig.Unmarshal(m, b)
}
func (m *GenerateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateConfig.Marshal(b, m, deterministic)
}
func (m *GenerateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateConfig.Merge(m, src)
}
func (m *GenerateConfig) XXX_Size() int {
	return xxx_messageInfo_GenerateConfig.Size(m)
}
func (m *GenerateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateConfig proto.InternalMessageInfo

func (m *GenerateConfig) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GenerateConfig) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GenerateConfig) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *GenerateConfig) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *GenerateConfig) GetDatastoreName() string {
	if m != nil {
		return m.DatastoreName
	}
	return ""
}

func (m *GenerateConfig) GetCanCheck() bool {
	if m != nil {
		return m.CanCheck
	}
	return false
}

func (m *GenerateConfig) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *GenerateConfig) GetMappingId() string {
	if m != nil {
		return m.MappingId
	}
	return ""
}

func (m *GenerateConfig) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

// 字段
type Field struct {
	FieldId              string   `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id"`
	DatastoreId          string   `protobuf:"bytes,3,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	FieldName            string   `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name"`
	FieldType            string   `protobuf:"bytes,5,opt,name=field_type,json=fieldType,proto3" json:"field_type"`
	IsFixed              bool     `protobuf:"varint,36,opt,name=is_fixed,json=isFixed,proto3" json:"is_fixed"`
	IsRequired           bool     `protobuf:"varint,6,opt,name=is_required,json=isRequired,proto3" json:"is_required"`
	IsImage              bool     `protobuf:"varint,7,opt,name=is_image,json=isImage,proto3" json:"is_image"`
	IsCheckImage         bool     `protobuf:"varint,35,opt,name=is_check_image,json=isCheckImage,proto3" json:"is_check_image"`
	AsTitle              bool     `protobuf:"varint,8,opt,name=as_title,json=asTitle,proto3" json:"as_title"`
	Unique               bool     `protobuf:"varint,26,opt,name=unique,proto3" json:"unique"`
	LookupAppId          string   `protobuf:"bytes,9,opt,name=lookup_app_id,json=lookupAppId,proto3" json:"lookup_app_id"`
	LookupDatastoreId    string   `protobuf:"bytes,10,opt,name=lookup_datastore_id,json=lookupDatastoreId,proto3" json:"lookup_datastore_id"`
	LookupFieldId        string   `protobuf:"bytes,11,opt,name=lookup_field_id,json=lookupFieldId,proto3" json:"lookup_field_id"`
	UserGroupId          string   `protobuf:"bytes,12,opt,name=user_group_id,json=userGroupId,proto3" json:"user_group_id"`
	OptionId             string   `protobuf:"bytes,13,opt,name=option_id,json=optionId,proto3" json:"option_id"`
	MinLength            int64    `protobuf:"varint,27,opt,name=min_length,json=minLength,proto3" json:"min_length"`
	MaxLength            int64    `protobuf:"varint,28,opt,name=max_length,json=maxLength,proto3" json:"max_length"`
	MinValue             int64    `protobuf:"varint,29,opt,name=min_value,json=minValue,proto3" json:"min_value"`
	MaxValue             int64    `protobuf:"varint,30,opt,name=max_value,json=maxValue,proto3" json:"max_value"`
	DisplayOrder         int64    `protobuf:"varint,25,opt,name=display_order,json=displayOrder,proto3" json:"display_order"`
	DisplayDigits        int64    `protobuf:"varint,31,opt,name=display_digits,json=displayDigits,proto3" json:"display_digits"`
	Precision            int64    `protobuf:"varint,37,opt,name=precision,proto3" json:"precision"`
	Prefix               string   `protobuf:"bytes,32,opt,name=prefix,proto3" json:"prefix"`
	ReturnType           string   `protobuf:"bytes,33,opt,name=return_type,json=returnType,proto3" json:"return_type"`
	Formula              string   `protobuf:"bytes,34,opt,name=formula,proto3" json:"formula"`
	CsvHeader            string   `protobuf:"bytes,19,opt,name=csv_header,json=csvHeader,proto3" json:"csv_header"`
	CanChange            bool     `protobuf:"varint,20,opt,name=can_change,json=canChange,proto3" json:"can_change"`
	IsEmptyLine          bool     `protobuf:"varint,21,opt,name=is_empty_line,json=isEmptyLine,proto3" json:"is_empty_line"`
	CheckErrors          string   `protobuf:"bytes,22,opt,name=check_errors,json=checkErrors,proto3" json:"check_errors"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{1}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

func (m *Field) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Field) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *Field) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *Field) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *Field) GetIsFixed() bool {
	if m != nil {
		return m.IsFixed
	}
	return false
}

func (m *Field) GetIsRequired() bool {
	if m != nil {
		return m.IsRequired
	}
	return false
}

func (m *Field) GetIsImage() bool {
	if m != nil {
		return m.IsImage
	}
	return false
}

func (m *Field) GetIsCheckImage() bool {
	if m != nil {
		return m.IsCheckImage
	}
	return false
}

func (m *Field) GetAsTitle() bool {
	if m != nil {
		return m.AsTitle
	}
	return false
}

func (m *Field) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *Field) GetLookupAppId() string {
	if m != nil {
		return m.LookupAppId
	}
	return ""
}

func (m *Field) GetLookupDatastoreId() string {
	if m != nil {
		return m.LookupDatastoreId
	}
	return ""
}

func (m *Field) GetLookupFieldId() string {
	if m != nil {
		return m.LookupFieldId
	}
	return ""
}

func (m *Field) GetUserGroupId() string {
	if m != nil {
		return m.UserGroupId
	}
	return ""
}

func (m *Field) GetOptionId() string {
	if m != nil {
		return m.OptionId
	}
	return ""
}

func (m *Field) GetMinLength() int64 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *Field) GetMaxLength() int64 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *Field) GetMinValue() int64 {
	if m != nil {
		return m.MinValue
	}
	return 0
}

func (m *Field) GetMaxValue() int64 {
	if m != nil {
		return m.MaxValue
	}
	return 0
}

func (m *Field) GetDisplayOrder() int64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Field) GetDisplayDigits() int64 {
	if m != nil {
		return m.DisplayDigits
	}
	return 0
}

func (m *Field) GetPrecision() int64 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *Field) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Field) GetReturnType() string {
	if m != nil {
		return m.ReturnType
	}
	return ""
}

func (m *Field) GetFormula() string {
	if m != nil {
		return m.Formula
	}
	return ""
}

func (m *Field) GetCsvHeader() string {
	if m != nil {
		return m.CsvHeader
	}
	return ""
}

func (m *Field) GetCanChange() bool {
	if m != nil {
		return m.CanChange
	}
	return false
}

func (m *Field) GetIsEmptyLine() bool {
	if m != nil {
		return m.IsEmptyLine
	}
	return false
}

func (m *Field) GetCheckErrors() string {
	if m != nil {
		return m.CheckErrors
	}
	return ""
}

// 查找多条记录
type FindRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{2}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FindRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindResponse struct {
	GenConfig            *GenerateConfig `protobuf:"bytes,1,opt,name=gen_config,json=genConfig,proto3" json:"gen_config"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{3}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetGenConfig() *GenerateConfig {
	if m != nil {
		return m.GenConfig
	}
	return nil
}

// 添加数据
type AddRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{4}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{5}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

// 更新数据
type ModifyRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	DatastoreId          string   `protobuf:"bytes,3,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	ApiKey               string   `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key"`
	DatastoreName        string   `protobuf:"bytes,5,opt,name=datastore_name,json=datastoreName,proto3" json:"datastore_name"`
	CanCheck             string   `protobuf:"bytes,6,opt,name=can_check,json=canCheck,proto3" json:"can_check"`
	Fields               []*Field `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields"`
	MappingId            string   `protobuf:"bytes,8,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id"`
	Step                 int64    `protobuf:"varint,9,opt,name=step,proto3" json:"step"`
	Database             string   `protobuf:"bytes,10,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequest) Reset()         { *m = ModifyRequest{} }
func (m *ModifyRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequest) ProtoMessage()    {}
func (*ModifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{6}
}

func (m *ModifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequest.Unmarshal(m, b)
}
func (m *ModifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequest.Marshal(b, m, deterministic)
}
func (m *ModifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequest.Merge(m, src)
}
func (m *ModifyRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequest.Size(m)
}
func (m *ModifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequest proto.InternalMessageInfo

func (m *ModifyRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ModifyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ModifyRequest) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *ModifyRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *ModifyRequest) GetDatastoreName() string {
	if m != nil {
		return m.DatastoreName
	}
	return ""
}

func (m *ModifyRequest) GetCanCheck() string {
	if m != nil {
		return m.CanCheck
	}
	return ""
}

func (m *ModifyRequest) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ModifyRequest) GetMappingId() string {
	if m != nil {
		return m.MappingId
	}
	return ""
}

func (m *ModifyRequest) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *ModifyRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type ModifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyResponse) Reset()         { *m = ModifyResponse{} }
func (m *ModifyResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyResponse) ProtoMessage()    {}
func (*ModifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{7}
}

func (m *ModifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyResponse.Unmarshal(m, b)
}
func (m *ModifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyResponse.Marshal(b, m, deterministic)
}
func (m *ModifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyResponse.Merge(m, src)
}
func (m *ModifyResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyResponse.Size(m)
}
func (m *ModifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyResponse proto.InternalMessageInfo

// 上传数据
type UploadRequest struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{8}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *UploadRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type UploadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{9}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

// 获取行数据
type RowRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	PageIndex            int64    `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index"`
	PageSize             int64    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowRequest) Reset()         { *m = RowRequest{} }
func (m *RowRequest) String() string { return proto.CompactTextString(m) }
func (*RowRequest) ProtoMessage()    {}
func (*RowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{10}
}

func (m *RowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowRequest.Unmarshal(m, b)
}
func (m *RowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowRequest.Marshal(b, m, deterministic)
}
func (m *RowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowRequest.Merge(m, src)
}
func (m *RowRequest) XXX_Size() int {
	return xxx_messageInfo_RowRequest.Size(m)
}
func (m *RowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RowRequest proto.InternalMessageInfo

func (m *RowRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RowRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RowRequest) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *RowRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *RowRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type Item struct {
	AppId                string            `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string            `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	ItemMap              map[string]string `protobuf:"bytes,3,rep,name=item_map,json=itemMap,proto3" json:"item_map" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{11}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Item) GetItemMap() map[string]string {
	if m != nil {
		return m.ItemMap
	}
	return nil
}

type RowResponse struct {
	Items                []*Item  `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowResponse) Reset()         { *m = RowResponse{} }
func (m *RowResponse) String() string { return proto.CompactTextString(m) }
func (*RowResponse) ProtoMessage()    {}
func (*RowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{12}
}

func (m *RowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowResponse.Unmarshal(m, b)
}
func (m *RowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowResponse.Marshal(b, m, deterministic)
}
func (m *RowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowResponse.Merge(m, src)
}
func (m *RowResponse) XXX_Size() int {
	return xxx_messageInfo_RowResponse.Size(m)
}
func (m *RowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RowResponse proto.InternalMessageInfo

func (m *RowResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// 获取列数据
type ColumnRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	ColumnName           string   `protobuf:"bytes,3,opt,name=column_name,json=columnName,proto3" json:"column_name"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnRequest) Reset()         { *m = ColumnRequest{} }
func (m *ColumnRequest) String() string { return proto.CompactTextString(m) }
func (*ColumnRequest) ProtoMessage()    {}
func (*ColumnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{13}
}

func (m *ColumnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnRequest.Unmarshal(m, b)
}
func (m *ColumnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnRequest.Marshal(b, m, deterministic)
}
func (m *ColumnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnRequest.Merge(m, src)
}
func (m *ColumnRequest) XXX_Size() int {
	return xxx_messageInfo_ColumnRequest.Size(m)
}
func (m *ColumnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnRequest proto.InternalMessageInfo

func (m *ColumnRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ColumnRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ColumnRequest) GetColumnName() string {
	if m != nil {
		return m.ColumnName
	}
	return ""
}

func (m *ColumnRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type ColumnResponse struct {
	Items                []string `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnResponse) Reset()         { *m = ColumnResponse{} }
func (m *ColumnResponse) String() string { return proto.CompactTextString(m) }
func (*ColumnResponse) ProtoMessage()    {}
func (*ColumnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{14}
}

func (m *ColumnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnResponse.Unmarshal(m, b)
}
func (m *ColumnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnResponse.Marshal(b, m, deterministic)
}
func (m *ColumnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnResponse.Merge(m, src)
}
func (m *ColumnResponse) XXX_Size() int {
	return xxx_messageInfo_ColumnResponse.Size(m)
}
func (m *ColumnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnResponse proto.InternalMessageInfo

func (m *ColumnResponse) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

// 删除数据记录
type DeleteRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{15}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a150c98491dbd900, []int{16}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenerateConfig)(nil), "generate.GenerateConfig")
	proto.RegisterType((*Field)(nil), "generate.Field")
	proto.RegisterType((*FindRequest)(nil), "generate.FindRequest")
	proto.RegisterType((*FindResponse)(nil), "generate.FindResponse")
	proto.RegisterType((*AddRequest)(nil), "generate.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "generate.AddResponse")
	proto.RegisterType((*ModifyRequest)(nil), "generate.ModifyRequest")
	proto.RegisterType((*ModifyResponse)(nil), "generate.ModifyResponse")
	proto.RegisterType((*UploadRequest)(nil), "generate.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "generate.UploadResponse")
	proto.RegisterType((*RowRequest)(nil), "generate.RowRequest")
	proto.RegisterType((*Item)(nil), "generate.Item")
	proto.RegisterMapType((map[string]string)(nil), "generate.Item.ItemMapEntry")
	proto.RegisterType((*RowResponse)(nil), "generate.RowResponse")
	proto.RegisterType((*ColumnRequest)(nil), "generate.ColumnRequest")
	proto.RegisterType((*ColumnResponse)(nil), "generate.ColumnResponse")
	proto.RegisterType((*DeleteRequest)(nil), "generate.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "generate.DeleteResponse")
}

func init() { proto.RegisterFile("generate.proto", fileDescriptor_a150c98491dbd900) }

var fileDescriptor_a150c98491dbd900 = []byte{
	// 1155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x8e, 0xed, 0xda, 0xde, 0x3d, 0xfe, 0x49, 0x3a, 0x4d, 0xd2, 0x89, 0xd3, 0x90, 0x74, 0x9b,
	0x96, 0x5c, 0xe5, 0x22, 0x95, 0x00, 0x55, 0xdc, 0x84, 0xfc, 0x61, 0xb5, 0x05, 0xe1, 0x16, 0x04,
	0xe2, 0x62, 0x35, 0xf5, 0x8e, 0x37, 0xa3, 0x78, 0x67, 0xb7, 0x3b, 0xeb, 0xd4, 0xae, 0x78, 0x0c,
	0x2e, 0x79, 0x02, 0x5e, 0x80, 0x6b, 0x5e, 0x0c, 0xa1, 0x39, 0x33, 0x5e, 0xef, 0xba, 0xa2, 0xa2,
	0x91, 0x0a, 0x37, 0x91, 0xcf, 0xf7, 0x9d, 0x39, 0x73, 0xe6, 0x3b, 0x3f, 0x76, 0xa0, 0x1b, 0x72,
	0xc9, 0x53, 0x96, 0xf1, 0xc3, 0x24, 0x8d, 0xb3, 0x98, 0x38, 0x73, 0xdb, 0xfb, 0xad, 0x0a, 0xdd,
	0x0b, 0x6b, 0x9c, 0xc4, 0x72, 0x24, 0x42, 0xb2, 0x01, 0x0d, 0x96, 0x24, 0xbe, 0x08, 0x68, 0x65,
	0xaf, 0x72, 0xe0, 0x0e, 0xea, 0x2c, 0x49, 0xfa, 0x01, 0xb9, 0x0b, 0xcd, 0x89, 0xe2, 0xa9, 0xc6,
	0xab, 0x88, 0x37, 0xb4, 0xd9, 0x0f, 0xc8, 0x7d, 0x68, 0x07, 0x2c, 0x63, 0x2a, 0x8b, 0x53, 0xae,
	0xd9, 0x1a, 0xb2, 0xad, 0x1c, 0x33, 0x67, 0x59, 0x22, 0xfc, 0x2b, 0x3e, 0xa3, 0xb7, 0xcc, 0x59,
	0x96, 0x88, 0xa7, 0x7c, 0x46, 0x1e, 0x42, 0x77, 0x71, 0x56, 0xb2, 0x88, 0xd3, 0x3a, 0xf2, 0x9d,
	0x1c, 0xfd, 0x86, 0x45, 0x9c, 0x6c, 0x83, 0x3b, 0x64, 0xd2, 0x1f, 0x5e, 0xf2, 0xe1, 0x15, 0x6d,
	0xec, 0x55, 0x0e, 0x9c, 0x81, 0x33, 0x64, 0xf2, 0x44, 0xdb, 0xe4, 0x53, 0x68, 0x8c, 0x04, 0x1f,
	0x07, 0x8a, 0x36, 0xf7, 0x6a, 0x07, 0xad, 0xa3, 0xd5, 0xc3, 0xfc, 0xb5, 0xe7, 0x1a, 0x1f, 0x58,
	0x9a, 0xec, 0x00, 0x44, 0x2c, 0x49, 0x84, 0x0c, 0x75, 0x9a, 0x0e, 0x5e, 0xe4, 0x5a, 0xa4, 0x1f,
	0x10, 0x02, 0xb7, 0x54, 0xc6, 0x13, 0xea, 0xee, 0x55, 0x0e, 0x6a, 0x03, 0xfc, 0xec, 0xfd, 0xd9,
	0x84, 0x3a, 0x06, 0x21, 0x5b, 0xe0, 0x60, 0x98, 0x85, 0x2e, 0x4d, 0xb4, 0xfb, 0x41, 0x41, 0xb0,
	0x6a, 0x51, 0xb0, 0x7f, 0xa1, 0xcb, 0x0e, 0x80, 0x09, 0x8a, 0x4f, 0x37, 0xd2, 0xb8, 0x88, 0xe0,
	0xb3, 0x73, 0x3a, 0x9b, 0x25, 0x73, 0x65, 0x0c, 0xfd, 0x72, 0x96, 0x70, 0x9d, 0x92, 0x50, 0xfe,
	0x48, 0x4c, 0x79, 0x40, 0xf7, 0x51, 0x94, 0xa6, 0x50, 0xe7, 0xda, 0x24, 0xbb, 0xd0, 0x12, 0xca,
	0x4f, 0xf9, 0xeb, 0x89, 0x48, 0x79, 0x60, 0x25, 0x03, 0xa1, 0x06, 0x16, 0xb1, 0x67, 0x45, 0xc4,
	0x42, 0x4e, 0x9b, 0xf3, 0xb3, 0x7d, 0x6d, 0x92, 0x7d, 0xe8, 0x0a, 0x65, 0xb4, 0xb6, 0x0e, 0x0f,
	0xd0, 0xa1, 0x2d, 0x14, 0x0a, 0x6e, 0xbc, 0xb6, 0xc0, 0x61, 0xca, 0xcf, 0x44, 0x36, 0xe6, 0x28,
	0xa5, 0x33, 0x68, 0x32, 0xf5, 0x52, 0x9b, 0x64, 0x13, 0x1a, 0x13, 0x29, 0x5e, 0x4f, 0x38, 0xed,
	0x21, 0x61, 0x2d, 0xe2, 0x41, 0x67, 0x1c, 0xc7, 0x57, 0x93, 0xc4, 0xb7, 0x72, 0xb9, 0x46, 0x11,
	0x03, 0x1e, 0xa3, 0x68, 0x87, 0x70, 0xc7, 0xfa, 0x94, 0xb4, 0x03, 0xf4, 0xbc, 0x6d, 0xa8, 0xd3,
	0x82, 0x82, 0x8f, 0x60, 0xd5, 0xfa, 0xe7, 0xd5, 0x69, 0x99, 0x0e, 0x32, 0xf0, 0xb9, 0xad, 0x91,
	0x07, 0x1d, 0xec, 0xde, 0x30, 0x8d, 0x27, 0x78, 0x77, 0xdb, 0xdc, 0xad, 0xc1, 0x0b, 0x8d, 0xf5,
	0x03, 0xdd, 0x65, 0x71, 0x92, 0x89, 0x58, 0x6a, 0xbe, 0x83, 0xbc, 0x63, 0x00, 0x53, 0xaa, 0x48,
	0x48, 0x7f, 0xcc, 0x65, 0x98, 0x5d, 0xd2, 0x6d, 0xec, 0x11, 0x37, 0x12, 0xf2, 0x19, 0x02, 0xa6,
	0xb7, 0xa6, 0x73, 0xfa, 0x9e, 0xa5, 0xd9, 0xd4, 0xd2, 0xdb, 0xa0, 0x7d, 0xfd, 0x6b, 0x36, 0x9e,
	0x70, 0xba, 0x83, 0xac, 0x13, 0x09, 0xf9, 0x83, 0xb6, 0x91, 0x64, 0x53, 0x4b, 0x7e, 0x62, 0x49,
	0x36, 0x35, 0xe4, 0x03, 0xe8, 0x04, 0x42, 0x25, 0x63, 0x36, 0xf3, 0xe3, 0x34, 0xe0, 0x29, 0xdd,
	0x42, 0x87, 0xb6, 0x05, 0xbf, 0xd5, 0x18, 0x8e, 0x91, 0x75, 0x0a, 0x44, 0x28, 0x32, 0x45, 0x77,
	0xd1, 0x6b, 0x7e, 0xf4, 0x14, 0x41, 0x72, 0x0f, 0xdc, 0x24, 0xe5, 0x43, 0xa1, 0x44, 0x2c, 0xe9,
	0x43, 0x93, 0x63, 0x0e, 0xe8, 0xb2, 0x25, 0x29, 0x1f, 0x89, 0x29, 0xdd, 0x33, 0x33, 0x6a, 0x2c,
	0xdd, 0x4b, 0x29, 0xcf, 0x26, 0xa9, 0x34, 0x6d, 0x78, 0x1f, 0x49, 0x30, 0x10, 0xf6, 0x21, 0x85,
	0xe6, 0x28, 0x4e, 0xa3, 0xc9, 0x98, 0x51, 0xcf, 0x4e, 0x86, 0x31, 0xb5, 0x2a, 0x43, 0x75, 0xed,
	0x5f, 0x72, 0xa6, 0x33, 0xbf, 0x63, 0x1a, 0x78, 0xa8, 0xae, 0xbf, 0x46, 0x00, 0x69, 0x1c, 0x6b,
	0x26, 0x43, 0x4e, 0xd7, 0xb1, 0x59, 0x5c, 0x9c, 0x6b, 0x0d, 0xe8, 0x9a, 0x09, 0xe5, 0xf3, 0x28,
	0xc9, 0x66, 0xfe, 0x58, 0x48, 0x4e, 0x37, 0xd0, 0xa3, 0x25, 0xd4, 0x99, 0xc6, 0x9e, 0x09, 0xc9,
	0xf5, 0x90, 0x99, 0x4e, 0xe5, 0x69, 0x1a, 0xa7, 0x8a, 0x6e, 0x9a, 0xb2, 0x22, 0x76, 0x86, 0x90,
	0xf7, 0x13, 0xb4, 0xce, 0x85, 0x0c, 0x74, 0xeb, 0x73, 0x95, 0x7d, 0xf0, 0x7a, 0xeb, 0x81, 0xa3,
	0x5b, 0xf1, 0x15, 0x53, 0xdc, 0x8e, 0x70, 0x6e, 0x7b, 0x17, 0xd0, 0x36, 0xa1, 0x55, 0x12, 0x4b,
	0xc5, 0xc9, 0xe7, 0x00, 0x21, 0x97, 0xfe, 0x10, 0x17, 0x29, 0xc6, 0x6f, 0x1d, 0xd1, 0xc5, 0x3a,
	0x2a, 0x2f, 0xda, 0x81, 0x1b, 0x72, 0x69, 0x3e, 0x7a, 0x3f, 0x02, 0x1c, 0x07, 0x1f, 0x25, 0xc5,
	0x0e, 0xb4, 0x30, 0xb2, 0xc9, 0xd0, 0xfb, 0xa3, 0x0a, 0x9d, 0xe7, 0x71, 0x20, 0x46, 0xb3, 0x9b,
	0x5e, 0xf6, 0x7f, 0xac, 0x7b, 0xf7, 0xbf, 0x59, 0xf7, 0x25, 0x21, 0x61, 0x49, 0xc8, 0x35, 0xe8,
	0xce, 0x85, 0xb3, 0x5a, 0x7e, 0x07, 0x9d, 0xef, 0x93, 0x71, 0xcc, 0xf2, 0xba, 0xed, 0x43, 0x5d,
	0x64, 0x3c, 0x52, 0xb4, 0x82, 0x99, 0x75, 0x17, 0x99, 0xf5, 0x33, 0x1e, 0x0d, 0x0c, 0x59, 0xba,
	0xa4, 0xfa, 0xee, 0x25, 0xf3, 0x90, 0xf6, 0x92, 0x5f, 0x2b, 0x00, 0x83, 0xf8, 0xcd, 0x4d, 0xab,
	0xb5, 0x03, 0x90, 0xb0, 0x90, 0xfb, 0x42, 0x06, 0x7c, 0x8a, 0xb5, 0xd2, 0x33, 0xcf, 0x42, 0xde,
	0xd7, 0x80, 0x56, 0x1a, 0x69, 0x25, 0xde, 0x9a, 0xef, 0x9f, 0xda, 0xc0, 0xd1, 0xc0, 0x0b, 0xf1,
	0x96, 0x97, 0x12, 0xad, 0x2f, 0x25, 0xfa, 0x7b, 0x05, 0x6e, 0xe9, 0x47, 0x7d, 0x70, 0x42, 0x9f,
	0x81, 0xa3, 0x65, 0xf0, 0x23, 0x96, 0xd0, 0x1a, 0xca, 0xb4, 0x5d, 0x96, 0x09, 0xff, 0x3c, 0x67,
	0xc9, 0x99, 0xcc, 0xd2, 0xd9, 0xa0, 0x29, 0x8c, 0xd5, 0x7b, 0x02, 0xed, 0x22, 0x41, 0xd6, 0xa0,
	0xa6, 0xfb, 0xcb, 0x5c, 0xaa, 0x3f, 0x92, 0x75, 0xa8, 0x9b, 0x15, 0x6a, 0xbf, 0x85, 0xd1, 0x78,
	0x52, 0xfd, 0xa2, 0xe2, 0x3d, 0x86, 0x16, 0x4a, 0x68, 0xa7, 0x34, 0x2f, 0x53, 0xed, 0x3d, 0x65,
	0xf2, 0x7e, 0x81, 0xce, 0x49, 0x3c, 0x9e, 0x44, 0xf2, 0xa6, 0xd2, 0xef, 0x42, 0x6b, 0x88, 0x01,
	0x4c, 0xa7, 0x9b, 0x39, 0x01, 0x03, 0x61, 0x9b, 0xbf, 0x4f, 0xdf, 0x47, 0xd0, 0x9d, 0xdf, 0x6e,
	0xb3, 0x5e, 0x2f, 0x66, 0xed, 0xce, 0xb3, 0xfc, 0x19, 0x3a, 0xa7, 0x7c, 0xcc, 0x33, 0xfe, 0x31,
	0x76, 0xc7, 0x1a, 0x74, 0xe7, 0xc1, 0x4d, 0x12, 0x47, 0x7f, 0xd5, 0x60, 0x75, 0xbe, 0xc5, 0x5e,
	0xf0, 0xf4, 0x5a, 0x0c, 0x39, 0x39, 0x03, 0xa2, 0x97, 0xe0, 0xf2, 0xaf, 0xc8, 0xe2, 0x58, 0xe6,
	0xdb, 0xb7, 0xb7, 0xb9, 0x0c, 0xdb, 0x36, 0x5f, 0x21, 0x5f, 0xc1, 0xed, 0xe3, 0x60, 0x39, 0xca,
	0xfa, 0xc2, 0x7d, 0xb1, 0x1f, 0x7b, 0x1b, 0x4b, 0x68, 0x1e, 0xe3, 0x29, 0xac, 0x9b, 0x19, 0x5d,
	0x0a, 0x73, 0x77, 0x71, 0xa0, 0xb4, 0xfc, 0x7a, 0xf4, 0x5d, 0x22, 0x0f, 0x76, 0x0c, 0x60, 0x66,
	0x51, 0xff, 0xde, 0x28, 0x86, 0x28, 0x0d, 0x7d, 0x31, 0xc4, 0xd2, 0xe8, 0xae, 0x90, 0x2f, 0xed,
	0x57, 0x4f, 0xfc, 0x06, 0x63, 0x14, 0x5e, 0xb3, 0x18, 0xe9, 0xe2, 0x6b, 0x0a, 0x5d, 0xea, 0xad,
	0x90, 0x33, 0xe8, 0xea, 0xd3, 0xa6, 0x0f, 0x96, 0x93, 0x28, 0xf5, 0x66, 0x31, 0x89, 0x72, 0xdb,
	0x18, 0x51, 0x4c, 0x15, 0xff, 0x59, 0x94, 0x52, 0x0b, 0x15, 0x83, 0x95, 0xcb, 0xef, 0xad, 0xbc,
	0x6a, 0xe0, 0x3f, 0x10, 0x8f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x25, 0xf7, 0xeb, 0x52,
	0x0c, 0x00, 0x00,
}
