// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: history.proto

package history

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for HistoryService service

func NewHistoryServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for HistoryService service

type HistoryService interface {
	FindHistories(ctx context.Context, in *HistoriesRequest, opts ...client.CallOption) (*HistoriesResponse, error)
	DownloadHistories(ctx context.Context, in *DownloadRequest, opts ...client.CallOption) (*DownloadResponse, error)
}

type historyService struct {
	c    client.Client
	name string
}

func NewHistoryService(name string, c client.Client) HistoryService {
	return &historyService{
		c:    c,
		name: name,
	}
}

func (c *historyService) FindHistories(ctx context.Context, in *HistoriesRequest, opts ...client.CallOption) (*HistoriesResponse, error) {
	req := c.c.NewRequest(c.name, "HistoryService.FindHistories", in)
	out := new(HistoriesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyService) DownloadHistories(ctx context.Context, in *DownloadRequest, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "HistoryService.DownloadHistories", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HistoryService service

type HistoryServiceHandler interface {
	FindHistories(context.Context, *HistoriesRequest, *HistoriesResponse) error
	DownloadHistories(context.Context, *DownloadRequest, *DownloadResponse) error
}

func RegisterHistoryServiceHandler(s server.Server, hdlr HistoryServiceHandler, opts ...server.HandlerOption) error {
	type historyService interface {
		FindHistories(ctx context.Context, in *HistoriesRequest, out *HistoriesResponse) error
		DownloadHistories(ctx context.Context, in *DownloadRequest, out *DownloadResponse) error
	}
	type HistoryService struct {
		historyService
	}
	h := &historyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&HistoryService{h}, opts...))
}

type historyServiceHandler struct {
	HistoryServiceHandler
}

func (h *historyServiceHandler) FindHistories(ctx context.Context, in *HistoriesRequest, out *HistoriesResponse) error {
	return h.HistoryServiceHandler.FindHistories(ctx, in, out)
}

func (h *historyServiceHandler) DownloadHistories(ctx context.Context, in *DownloadRequest, out *DownloadResponse) error {
	return h.HistoryServiceHandler.DownloadHistories(ctx, in, out)
}
