// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文件
type File struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id"`
	FolderId             string   `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id"`
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name"`
	ObjectName           string   `protobuf:"bytes,4,opt,name=object_name,json=objectName,proto3" json:"object_name"`
	FilePath             string   `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path"`
	FileSize             int64    `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size"`
	ContentType          string   `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type"`
	Domain               string   `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain"`
	Owners               []string `protobuf:"bytes,9,rep,name=owners,proto3" json:"owners"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string   `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string   `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string   `protobuf:"bytes,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	DeletedAt            string   `protobuf:"bytes,14,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	DeletedBy            string   `protobuf:"bytes,15,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *File) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *File) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *File) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *File) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *File) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *File) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *File) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *File) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *File) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *File) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *File) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *File) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

// 查找多个记录
type FindFilesRequest struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	FolderId             string   `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id"`
	FileName             string   `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name"`
	ContentType          string   `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type"`
	Domain               string   `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain"`
	Database             string   `protobuf:"bytes,7,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFilesRequest) Reset()         { *m = FindFilesRequest{} }
func (m *FindFilesRequest) String() string { return proto.CompactTextString(m) }
func (*FindFilesRequest) ProtoMessage()    {}
func (*FindFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *FindFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilesRequest.Unmarshal(m, b)
}
func (m *FindFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilesRequest.Marshal(b, m, deterministic)
}
func (m *FindFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilesRequest.Merge(m, src)
}
func (m *FindFilesRequest) XXX_Size() int {
	return xxx_messageInfo_FindFilesRequest.Size(m)
}
func (m *FindFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilesRequest proto.InternalMessageInfo

func (m *FindFilesRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *FindFilesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FindFilesRequest) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *FindFilesRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FindFilesRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *FindFilesRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *FindFilesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindFilesResponse struct {
	FileList             []*File  `protobuf:"bytes,1,rep,name=file_list,json=fileList,proto3" json:"file_list"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFilesResponse) Reset()         { *m = FindFilesResponse{} }
func (m *FindFilesResponse) String() string { return proto.CompactTextString(m) }
func (*FindFilesResponse) ProtoMessage()    {}
func (*FindFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *FindFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFilesResponse.Unmarshal(m, b)
}
func (m *FindFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFilesResponse.Marshal(b, m, deterministic)
}
func (m *FindFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFilesResponse.Merge(m, src)
}
func (m *FindFilesResponse) XXX_Size() int {
	return xxx_messageInfo_FindFilesResponse.Size(m)
}
func (m *FindFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindFilesResponse proto.InternalMessageInfo

func (m *FindFilesResponse) GetFileList() []*File {
	if m != nil {
		return m.FileList
	}
	return nil
}

// 通过ID查找单个记录
type FindFileRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileRequest) Reset()         { *m = FindFileRequest{} }
func (m *FindFileRequest) String() string { return proto.CompactTextString(m) }
func (*FindFileRequest) ProtoMessage()    {}
func (*FindFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *FindFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileRequest.Unmarshal(m, b)
}
func (m *FindFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileRequest.Marshal(b, m, deterministic)
}
func (m *FindFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileRequest.Merge(m, src)
}
func (m *FindFileRequest) XXX_Size() int {
	return xxx_messageInfo_FindFileRequest.Size(m)
}
func (m *FindFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileRequest proto.InternalMessageInfo

func (m *FindFileRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *FindFileRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindFileResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileResponse) Reset()         { *m = FindFileResponse{} }
func (m *FindFileResponse) String() string { return proto.CompactTextString(m) }
func (*FindFileResponse) ProtoMessage()    {}
func (*FindFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4}
}

func (m *FindFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileResponse.Unmarshal(m, b)
}
func (m *FindFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileResponse.Marshal(b, m, deterministic)
}
func (m *FindFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileResponse.Merge(m, src)
}
func (m *FindFileResponse) XXX_Size() int {
	return xxx_messageInfo_FindFileResponse.Size(m)
}
func (m *FindFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileResponse proto.InternalMessageInfo

func (m *FindFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

// 添加一条记录
type AddRequest struct {
	FolderId             string   `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id"`
	FileName             string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name"`
	ObjectName           string   `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name"`
	FilePath             string   `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path"`
	FileSize             int64    `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size"`
	ContentType          string   `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type"`
	Domain               string   `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain"`
	Owners               []string `protobuf:"bytes,8,rep,name=owners,proto3" json:"owners"`
	Writer               string   `protobuf:"bytes,9,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,10,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{5}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *AddRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AddRequest) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *AddRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *AddRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *AddRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *AddRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddRequest) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *AddRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddResponse struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{6}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

// 逻辑删除-单个文件
type DeleteRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *DeleteRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

// 逻辑删除-多个文件
type DeleteSelectFilesRequest struct {
	FileIdList           []string `protobuf:"bytes,1,rep,name=file_id_list,json=fileIdList,proto3" json:"file_id_list"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSelectFilesRequest) Reset()         { *m = DeleteSelectFilesRequest{} }
func (m *DeleteSelectFilesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSelectFilesRequest) ProtoMessage()    {}
func (*DeleteSelectFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{8}
}

func (m *DeleteSelectFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSelectFilesRequest.Unmarshal(m, b)
}
func (m *DeleteSelectFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSelectFilesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSelectFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSelectFilesRequest.Merge(m, src)
}
func (m *DeleteSelectFilesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSelectFilesRequest.Size(m)
}
func (m *DeleteSelectFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSelectFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSelectFilesRequest proto.InternalMessageInfo

func (m *DeleteSelectFilesRequest) GetFileIdList() []string {
	if m != nil {
		return m.FileIdList
	}
	return nil
}

func (m *DeleteSelectFilesRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteSelectFilesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

// 物理删除-单个文件
type HardDeleteRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardDeleteRequest) Reset()         { *m = HardDeleteRequest{} }
func (m *HardDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*HardDeleteRequest) ProtoMessage()    {}
func (*HardDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{9}
}

func (m *HardDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardDeleteRequest.Unmarshal(m, b)
}
func (m *HardDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardDeleteRequest.Marshal(b, m, deterministic)
}
func (m *HardDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardDeleteRequest.Merge(m, src)
}
func (m *HardDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_HardDeleteRequest.Size(m)
}
func (m *HardDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HardDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HardDeleteRequest proto.InternalMessageInfo

func (m *HardDeleteRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *HardDeleteRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

// 物理删除-多个文件
type HardDeleteFilesRequest struct {
	FileIdList           []string `protobuf:"bytes,1,rep,name=file_id_list,json=fileIdList,proto3" json:"file_id_list"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardDeleteFilesRequest) Reset()         { *m = HardDeleteFilesRequest{} }
func (m *HardDeleteFilesRequest) String() string { return proto.CompactTextString(m) }
func (*HardDeleteFilesRequest) ProtoMessage()    {}
func (*HardDeleteFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{10}
}

func (m *HardDeleteFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardDeleteFilesRequest.Unmarshal(m, b)
}
func (m *HardDeleteFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardDeleteFilesRequest.Marshal(b, m, deterministic)
}
func (m *HardDeleteFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardDeleteFilesRequest.Merge(m, src)
}
func (m *HardDeleteFilesRequest) XXX_Size() int {
	return xxx_messageInfo_HardDeleteFilesRequest.Size(m)
}
func (m *HardDeleteFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HardDeleteFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HardDeleteFilesRequest proto.InternalMessageInfo

func (m *HardDeleteFilesRequest) GetFileIdList() []string {
	if m != nil {
		return m.FileIdList
	}
	return nil
}

func (m *HardDeleteFilesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{11}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// 逻辑删除-整个文件夹文件
type DeleteFolderRequest struct {
	FolderId             string   `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFolderRequest) Reset()         { *m = DeleteFolderRequest{} }
func (m *DeleteFolderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFolderRequest) ProtoMessage()    {}
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{12}
}

func (m *DeleteFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFolderRequest.Unmarshal(m, b)
}
func (m *DeleteFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFolderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFolderRequest.Merge(m, src)
}
func (m *DeleteFolderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFolderRequest.Size(m)
}
func (m *DeleteFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFolderRequest proto.InternalMessageInfo

func (m *DeleteFolderRequest) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *DeleteFolderRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteFolderRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

// 恢复选中文件
type RecoverSelectFilesRequest struct {
	FileIdList           []string `protobuf:"bytes,1,rep,name=file_id_list,json=fileIdList,proto3" json:"file_id_list"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverSelectFilesRequest) Reset()         { *m = RecoverSelectFilesRequest{} }
func (m *RecoverSelectFilesRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverSelectFilesRequest) ProtoMessage()    {}
func (*RecoverSelectFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{13}
}

func (m *RecoverSelectFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverSelectFilesRequest.Unmarshal(m, b)
}
func (m *RecoverSelectFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverSelectFilesRequest.Marshal(b, m, deterministic)
}
func (m *RecoverSelectFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverSelectFilesRequest.Merge(m, src)
}
func (m *RecoverSelectFilesRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverSelectFilesRequest.Size(m)
}
func (m *RecoverSelectFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverSelectFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverSelectFilesRequest proto.InternalMessageInfo

func (m *RecoverSelectFilesRequest) GetFileIdList() []string {
	if m != nil {
		return m.FileIdList
	}
	return nil
}

func (m *RecoverSelectFilesRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *RecoverSelectFilesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type RecoverSelectFilesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverSelectFilesResponse) Reset()         { *m = RecoverSelectFilesResponse{} }
func (m *RecoverSelectFilesResponse) String() string { return proto.CompactTextString(m) }
func (*RecoverSelectFilesResponse) ProtoMessage()    {}
func (*RecoverSelectFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{14}
}

func (m *RecoverSelectFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverSelectFilesResponse.Unmarshal(m, b)
}
func (m *RecoverSelectFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverSelectFilesResponse.Marshal(b, m, deterministic)
}
func (m *RecoverSelectFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverSelectFilesResponse.Merge(m, src)
}
func (m *RecoverSelectFilesResponse) XXX_Size() int {
	return xxx_messageInfo_RecoverSelectFilesResponse.Size(m)
}
func (m *RecoverSelectFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverSelectFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverSelectFilesResponse proto.InternalMessageInfo

// 恢复文件夹文件
type RecoverFolderFilesRequest struct {
	FolderId             string   `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverFolderFilesRequest) Reset()         { *m = RecoverFolderFilesRequest{} }
func (m *RecoverFolderFilesRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverFolderFilesRequest) ProtoMessage()    {}
func (*RecoverFolderFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{15}
}

func (m *RecoverFolderFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverFolderFilesRequest.Unmarshal(m, b)
}
func (m *RecoverFolderFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverFolderFilesRequest.Marshal(b, m, deterministic)
}
func (m *RecoverFolderFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverFolderFilesRequest.Merge(m, src)
}
func (m *RecoverFolderFilesRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverFolderFilesRequest.Size(m)
}
func (m *RecoverFolderFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverFolderFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverFolderFilesRequest proto.InternalMessageInfo

func (m *RecoverFolderFilesRequest) GetFolderId() string {
	if m != nil {
		return m.FolderId
	}
	return ""
}

func (m *RecoverFolderFilesRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *RecoverFolderFilesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type RecoverFolderFilesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverFolderFilesResponse) Reset()         { *m = RecoverFolderFilesResponse{} }
func (m *RecoverFolderFilesResponse) String() string { return proto.CompactTextString(m) }
func (*RecoverFolderFilesResponse) ProtoMessage()    {}
func (*RecoverFolderFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{16}
}

func (m *RecoverFolderFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverFolderFilesResponse.Unmarshal(m, b)
}
func (m *RecoverFolderFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverFolderFilesResponse.Marshal(b, m, deterministic)
}
func (m *RecoverFolderFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverFolderFilesResponse.Merge(m, src)
}
func (m *RecoverFolderFilesResponse) XXX_Size() int {
	return xxx_messageInfo_RecoverFolderFilesResponse.Size(m)
}
func (m *RecoverFolderFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverFolderFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverFolderFilesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*File)(nil), "file.File")
	proto.RegisterType((*FindFilesRequest)(nil), "file.FindFilesRequest")
	proto.RegisterType((*FindFilesResponse)(nil), "file.FindFilesResponse")
	proto.RegisterType((*FindFileRequest)(nil), "file.FindFileRequest")
	proto.RegisterType((*FindFileResponse)(nil), "file.FindFileResponse")
	proto.RegisterType((*AddRequest)(nil), "file.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "file.AddResponse")
	proto.RegisterType((*DeleteRequest)(nil), "file.DeleteRequest")
	proto.RegisterType((*DeleteSelectFilesRequest)(nil), "file.DeleteSelectFilesRequest")
	proto.RegisterType((*HardDeleteRequest)(nil), "file.HardDeleteRequest")
	proto.RegisterType((*HardDeleteFilesRequest)(nil), "file.HardDeleteFilesRequest")
	proto.RegisterType((*DeleteResponse)(nil), "file.DeleteResponse")
	proto.RegisterType((*DeleteFolderRequest)(nil), "file.DeleteFolderRequest")
	proto.RegisterType((*RecoverSelectFilesRequest)(nil), "file.RecoverSelectFilesRequest")
	proto.RegisterType((*RecoverSelectFilesResponse)(nil), "file.RecoverSelectFilesResponse")
	proto.RegisterType((*RecoverFolderFilesRequest)(nil), "file.RecoverFolderFilesRequest")
	proto.RegisterType((*RecoverFolderFilesResponse)(nil), "file.RecoverFolderFilesResponse")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0xe2, 0xc4, 0x49, 0x26, 0xbd, 0x24, 0x5b, 0x48, 0xb7, 0xa1, 0xb4, 0x21, 0x0f, 0xd0,
	0xa7, 0x0a, 0x95, 0x27, 0x04, 0x42, 0x4a, 0x05, 0xa5, 0x08, 0x84, 0x50, 0x8a, 0x90, 0x90, 0x90,
	0x2a, 0x27, 0x9e, 0xaa, 0x46, 0x6e, 0xec, 0xda, 0xdb, 0x56, 0xee, 0x17, 0xf1, 0x1b, 0x7c, 0x00,
	0x12, 0x9f, 0x84, 0xf6, 0xe2, 0xcb, 0x3a, 0xb5, 0x5b, 0x2a, 0xc4, 0x5b, 0x76, 0xce, 0xcc, 0xec,
	0xd9, 0x39, 0x73, 0xdc, 0x02, 0x1c, 0x3b, 0x2e, 0xee, 0xf8, 0x81, 0xc7, 0x3c, 0x52, 0xe3, 0xbf,
	0x87, 0x3f, 0x0d, 0xa8, 0xed, 0x3b, 0x2e, 0x92, 0x35, 0x68, 0xf0, 0xc0, 0x91, 0x63, 0xd3, 0xca,
	0xa0, 0xb2, 0xdd, 0x1a, 0x9b, 0xfc, 0xf8, 0xce, 0x26, 0x0f, 0xa0, 0x75, 0xec, 0xb9, 0x36, 0x06,
	0x1c, 0xaa, 0x0a, 0xa8, 0x29, 0x03, 0x0a, 0xe4, 0x55, 0x33, 0xeb, 0x14, 0xa9, 0xa1, 0x40, 0xc7,
	0xc5, 0x8f, 0xd6, 0x29, 0x92, 0x2d, 0x68, 0x7b, 0x93, 0xef, 0x38, 0x65, 0x12, 0xae, 0x09, 0x18,
	0x64, 0x48, 0x24, 0xc4, 0xd5, 0xbe, 0xc5, 0x4e, 0x68, 0x3d, 0xad, 0xfe, 0x64, 0xb1, 0x93, 0x04,
	0x0c, 0x9d, 0x2b, 0xa4, 0xe6, 0xa0, 0xb2, 0x6d, 0x48, 0xf0, 0xd0, 0xb9, 0x42, 0xf2, 0x08, 0x16,
	0xa7, 0xde, 0x8c, 0xe1, 0x8c, 0x1d, 0xb1, 0xc8, 0x47, 0xda, 0x10, 0xc5, 0x6d, 0x15, 0xfb, 0x1c,
	0xf9, 0x48, 0x7a, 0x60, 0xda, 0xde, 0xa9, 0xe5, 0xcc, 0x68, 0x53, 0xbe, 0x47, 0x9e, 0x78, 0xdc,
	0xbb, 0x9c, 0x61, 0x10, 0xd2, 0xd6, 0xc0, 0xe0, 0x71, 0x79, 0x22, 0x0f, 0x01, 0xa6, 0x01, 0x5a,
	0x0c, 0xed, 0x23, 0x8b, 0x51, 0x10, 0x35, 0x2d, 0x15, 0x19, 0xb1, 0x2c, 0x3c, 0x89, 0x68, 0x5b,
	0x83, 0xf7, 0x22, 0x0e, 0x9f, 0xfb, 0x76, 0x5c, 0xbd, 0x28, 0x61, 0x15, 0x91, 0xd5, 0x31, 0x3c,
	0x89, 0xe8, 0x92, 0x06, 0xcb, 0x6a, 0x1b, 0x5d, 0x54, 0xd5, 0xcb, 0x12, 0x56, 0x11, 0x59, 0x1d,
	0xc3, 0x93, 0x88, 0xae, 0x68, 0xf0, 0x5e, 0x34, 0xfc, 0x5d, 0x81, 0xce, 0xbe, 0x33, 0xb3, 0xb9,
	0x8e, 0xe1, 0x18, 0xcf, 0xce, 0x31, 0x64, 0x84, 0x40, 0x4d, 0x4c, 0x86, 0x8b, 0x59, 0x1f, 0x8b,
	0xdf, 0x5c, 0xe3, 0xf3, 0x30, 0x2b, 0xa4, 0xc9, 0x8f, 0x79, 0x8d, 0x8d, 0x32, 0x8d, 0x6b, 0x39,
	0x8d, 0xf3, 0x42, 0xd4, 0xcb, 0x84, 0x30, 0x35, 0x21, 0xfa, 0xd0, 0xb4, 0x2d, 0x66, 0x4d, 0xac,
	0x30, 0xd6, 0x2f, 0x39, 0x0f, 0x5f, 0x42, 0x37, 0xf3, 0xa2, 0xd0, 0xf7, 0x66, 0x21, 0x92, 0x27,
	0x8a, 0x88, 0xeb, 0x84, 0x8c, 0x56, 0x06, 0xc6, 0x76, 0x7b, 0x17, 0x76, 0xc4, 0x46, 0xf3, 0x3c,
	0x49, 0xea, 0x83, 0x13, 0xb2, 0xe1, 0x3e, 0xac, 0xc4, 0xd5, 0xf1, 0x38, 0x0a, 0xd7, 0x3b, 0xcb,
	0xa2, 0x9a, 0x63, 0xb1, 0x9b, 0xce, 0x35, 0x21, 0xb1, 0x09, 0xc2, 0x38, 0xa2, 0x8b, 0x7e, 0xbf,
	0x34, 0xd4, 0x8f, 0x2a, 0xc0, 0xc8, 0xb6, 0xe3, 0x7b, 0xb5, 0xc9, 0x56, 0xca, 0x26, 0x5b, 0x2d,
	0x77, 0x8f, 0x51, 0xee, 0x9e, 0x5a, 0x99, 0x7b, 0xea, 0x37, 0xb8, 0xc7, 0x2c, 0x13, 0xad, 0x51,
	0xe0, 0x9e, 0xa6, 0xe6, 0x9e, 0x1e, 0x98, 0x97, 0x81, 0xc3, 0x30, 0xa0, 0x2d, 0x99, 0x2f, 0x4f,
	0xda, 0x78, 0x21, 0x37, 0xde, 0xc7, 0xd0, 0x16, 0x93, 0x52, 0x93, 0x2d, 0x92, 0x68, 0xf8, 0x0d,
	0x96, 0x5e, 0x8b, 0x65, 0xbf, 0x51, 0xcc, 0x94, 0x45, 0xb5, 0x90, 0x85, 0x91, 0x63, 0xe1, 0x03,
	0x95, 0xdd, 0x0f, 0xd1, 0xc5, 0x29, 0xd3, 0x4c, 0x34, 0x80, 0x45, 0x75, 0x51, 0xba, 0x74, 0xad,
	0x31, 0xc8, 0xdb, 0xf8, 0xaa, 0xdd, 0xe9, 0xc6, 0x03, 0xe8, 0x1e, 0x58, 0x81, 0x7d, 0xcb, 0x37,
	0x95, 0x2d, 0xe8, 0x17, 0xe8, 0xa5, 0x9d, 0xfe, 0x92, 0x79, 0x59, 0xdf, 0x0e, 0x2c, 0xc7, 0xec,
	0xa4, 0x38, 0xc3, 0x63, 0x58, 0x55, 0xb7, 0x88, 0xe5, 0xbd, 0xd5, 0x7a, 0xdf, 0x65, 0x36, 0x67,
	0xb0, 0x3e, 0xc6, 0xa9, 0x77, 0x81, 0xc1, 0x7f, 0x93, 0x63, 0x03, 0xfa, 0xd7, 0x5d, 0xa9, 0x1e,
	0xee, 0x26, 0x84, 0xe4, 0xcb, 0x35, 0x42, 0xff, 0xfc, 0xf9, 0x29, 0x17, 0xed, 0x36, 0xc9, 0x65,
	0xf7, 0x57, 0x1d, 0xda, 0x3c, 0x72, 0x88, 0xc1, 0x85, 0x33, 0x45, 0xf2, 0x0a, 0x5a, 0xc9, 0x57,
	0x92, 0xf4, 0xe2, 0x4f, 0x91, 0xfe, 0x87, 0xa0, 0xbf, 0x36, 0x17, 0x57, 0x2f, 0x5b, 0x20, 0x2f,
	0xa0, 0x19, 0x87, 0xc9, 0x7d, 0x3d, 0x2d, 0xae, 0xee, 0xe5, 0xc3, 0x49, 0xf1, 0x53, 0x68, 0x8c,
	0x6c, 0x59, 0xdb, 0x91, 0x49, 0xe9, 0x67, 0xaf, 0xdf, 0xcd, 0x44, 0x92, 0x8a, 0xe7, 0x00, 0xe9,
	0xa6, 0x92, 0x55, 0x99, 0xa2, 0xb9, 0xa0, 0x7f, 0x4f, 0x0f, 0x26, 0xa5, 0xef, 0xa1, 0x3b, 0x67,
	0x52, 0xb2, 0x99, 0x4d, 0x9e, 0x5f, 0x97, 0xc2, 0x66, 0x23, 0x58, 0xd6, 0x5d, 0x43, 0xd4, 0x8c,
	0xe6, 0x5c, 0x59, 0xd8, 0xe2, 0x2d, 0xac, 0xe4, 0x8c, 0x47, 0x36, 0xf2, 0x3d, 0x6e, 0xc5, 0xe5,
	0x0d, 0x74, 0xb2, 0xbe, 0x12, 0x6c, 0xd6, 0xb3, 0xb9, 0x9a, 0xdf, 0x0a, 0xdb, 0x7c, 0x05, 0x32,
	0xbf, 0xc3, 0x64, 0x4b, 0x66, 0x17, 0x1a, 0xaa, 0x3f, 0x28, 0x4e, 0xb8, 0xa6, 0x75, 0x66, 0x25,
	0x73, 0xad, 0xe7, 0xad, 0x91, 0x6b, 0x7d, 0xcd, 0x36, 0x0f, 0x17, 0x26, 0xa6, 0xf8, 0x4f, 0xf4,
	0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x11, 0x4a, 0xe6, 0x97, 0x0a, 0x00, 0x00,
}
