// Code generated by protoc-gen-go. DO NOT EDIT.
// source: access.proto

package access

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 角色
type Access struct {
	AccessId             string              `protobuf:"bytes,1,opt,name=access_id,json=accessId,proto3" json:"access_id"`
	RoleId               string              `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	GroupId              string              `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Apps                 map[string]*AppData `protobuf:"bytes,4,rep,name=apps,proto3" json:"apps" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt            string              `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string              `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string              `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string              `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	DeletedAt            string              `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	DeletedBy            string              `protobuf:"bytes,10,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Access) Reset()         { *m = Access{} }
func (m *Access) String() string { return proto.CompactTextString(m) }
func (*Access) ProtoMessage()    {}
func (*Access) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{0}
}

func (m *Access) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Access.Unmarshal(m, b)
}
func (m *Access) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Access.Marshal(b, m, deterministic)
}
func (m *Access) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Access.Merge(m, src)
}
func (m *Access) XXX_Size() int {
	return xxx_messageInfo_Access.Size(m)
}
func (m *Access) XXX_DiscardUnknown() {
	xxx_messageInfo_Access.DiscardUnknown(m)
}

var xxx_messageInfo_Access proto.InternalMessageInfo

func (m *Access) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *Access) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *Access) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Access) GetApps() map[string]*AppData {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *Access) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Access) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Access) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Access) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Access) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Access) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

type AppData struct {
	DataAccess           map[string]*DataAccess `protobuf:"bytes,1,rep,name=data_access,json=dataAccess,proto3" json:"data_access" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AppData) Reset()         { *m = AppData{} }
func (m *AppData) String() string { return proto.CompactTextString(m) }
func (*AppData) ProtoMessage()    {}
func (*AppData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{1}
}

func (m *AppData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppData.Unmarshal(m, b)
}
func (m *AppData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppData.Marshal(b, m, deterministic)
}
func (m *AppData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppData.Merge(m, src)
}
func (m *AppData) XXX_Size() int {
	return xxx_messageInfo_AppData.Size(m)
}
func (m *AppData) XXX_DiscardUnknown() {
	xxx_messageInfo_AppData.DiscardUnknown(m)
}

var xxx_messageInfo_AppData proto.InternalMessageInfo

func (m *AppData) GetDataAccess() map[string]*DataAccess {
	if m != nil {
		return m.DataAccess
	}
	return nil
}

type DataAccess struct {
	DatastoreId          string        `protobuf:"bytes,1,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	Actions              []*DataAction `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DataAccess) Reset()         { *m = DataAccess{} }
func (m *DataAccess) String() string { return proto.CompactTextString(m) }
func (*DataAccess) ProtoMessage()    {}
func (*DataAccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{2}
}

func (m *DataAccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAccess.Unmarshal(m, b)
}
func (m *DataAccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAccess.Marshal(b, m, deterministic)
}
func (m *DataAccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAccess.Merge(m, src)
}
func (m *DataAccess) XXX_Size() int {
	return xxx_messageInfo_DataAccess.Size(m)
}
func (m *DataAccess) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAccess.DiscardUnknown(m)
}

var xxx_messageInfo_DataAccess proto.InternalMessageInfo

func (m *DataAccess) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *DataAccess) GetActions() []*DataAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

type DataAction struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	AccessKey            string   `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key"`
	CanFind              bool     `protobuf:"varint,3,opt,name=can_find,json=canFind,proto3" json:"can_find"`
	CanUpdate            bool     `protobuf:"varint,4,opt,name=can_update,json=canUpdate,proto3" json:"can_update"`
	CanDelete            bool     `protobuf:"varint,5,opt,name=can_delete,json=canDelete,proto3" json:"can_delete"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataAction) Reset()         { *m = DataAction{} }
func (m *DataAction) String() string { return proto.CompactTextString(m) }
func (*DataAction) ProtoMessage()    {}
func (*DataAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{3}
}

func (m *DataAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAction.Unmarshal(m, b)
}
func (m *DataAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAction.Marshal(b, m, deterministic)
}
func (m *DataAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAction.Merge(m, src)
}
func (m *DataAction) XXX_Size() int {
	return xxx_messageInfo_DataAction.Size(m)
}
func (m *DataAction) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAction.DiscardUnknown(m)
}

var xxx_messageInfo_DataAction proto.InternalMessageInfo

func (m *DataAction) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *DataAction) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *DataAction) GetCanFind() bool {
	if m != nil {
		return m.CanFind
	}
	return false
}

func (m *DataAction) GetCanUpdate() bool {
	if m != nil {
		return m.CanUpdate
	}
	return false
}

func (m *DataAction) GetCanDelete() bool {
	if m != nil {
		return m.CanDelete
	}
	return false
}

type FindUserAccesssRequest struct {
	RoleId               []string `protobuf:"bytes,1,rep,name=role_id,json=roleId,proto3" json:"role_id"`
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id"`
	DatastoreId          string   `protobuf:"bytes,4,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner"`
	Action               string   `protobuf:"bytes,6,opt,name=action,proto3" json:"action"`
	Database             string   `protobuf:"bytes,7,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserAccesssRequest) Reset()         { *m = FindUserAccesssRequest{} }
func (m *FindUserAccesssRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserAccesssRequest) ProtoMessage()    {}
func (*FindUserAccesssRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{4}
}

func (m *FindUserAccesssRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserAccesssRequest.Unmarshal(m, b)
}
func (m *FindUserAccesssRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserAccesssRequest.Marshal(b, m, deterministic)
}
func (m *FindUserAccesssRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserAccesssRequest.Merge(m, src)
}
func (m *FindUserAccesssRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserAccesssRequest.Size(m)
}
func (m *FindUserAccesssRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserAccesssRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserAccesssRequest proto.InternalMessageInfo

func (m *FindUserAccesssRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *FindUserAccesssRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *FindUserAccesssRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindUserAccesssRequest) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *FindUserAccesssRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *FindUserAccesssRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *FindUserAccesssRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindUserAccesssResponse struct {
	AccessKeys           []string `protobuf:"bytes,1,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserAccesssResponse) Reset()         { *m = FindUserAccesssResponse{} }
func (m *FindUserAccesssResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserAccesssResponse) ProtoMessage()    {}
func (*FindUserAccesssResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{5}
}

func (m *FindUserAccesssResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserAccesssResponse.Unmarshal(m, b)
}
func (m *FindUserAccesssResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserAccesssResponse.Marshal(b, m, deterministic)
}
func (m *FindUserAccesssResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserAccesssResponse.Merge(m, src)
}
func (m *FindUserAccesssResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserAccesssResponse.Size(m)
}
func (m *FindUserAccesssResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserAccesssResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserAccesssResponse proto.InternalMessageInfo

func (m *FindUserAccesssResponse) GetAccessKeys() []string {
	if m != nil {
		return m.AccessKeys
	}
	return nil
}

type FindAccessRequest struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAccessRequest) Reset()         { *m = FindAccessRequest{} }
func (m *FindAccessRequest) String() string { return proto.CompactTextString(m) }
func (*FindAccessRequest) ProtoMessage()    {}
func (*FindAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{6}
}

func (m *FindAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccessRequest.Unmarshal(m, b)
}
func (m *FindAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccessRequest.Marshal(b, m, deterministic)
}
func (m *FindAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccessRequest.Merge(m, src)
}
func (m *FindAccessRequest) XXX_Size() int {
	return xxx_messageInfo_FindAccessRequest.Size(m)
}
func (m *FindAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccessRequest proto.InternalMessageInfo

func (m *FindAccessRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *FindAccessRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *FindAccessRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindAccessResponse struct {
	AccessList           []*Access `protobuf:"bytes,1,rep,name=access_list,json=accessList,proto3" json:"access_list"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindAccessResponse) Reset()         { *m = FindAccessResponse{} }
func (m *FindAccessResponse) String() string { return proto.CompactTextString(m) }
func (*FindAccessResponse) ProtoMessage()    {}
func (*FindAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{7}
}

func (m *FindAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccessResponse.Unmarshal(m, b)
}
func (m *FindAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccessResponse.Marshal(b, m, deterministic)
}
func (m *FindAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccessResponse.Merge(m, src)
}
func (m *FindAccessResponse) XXX_Size() int {
	return xxx_messageInfo_FindAccessResponse.Size(m)
}
func (m *FindAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccessResponse proto.InternalMessageInfo

func (m *FindAccessResponse) GetAccessList() []*Access {
	if m != nil {
		return m.AccessList
	}
	return nil
}

type FindOneAccessRequest struct {
	AccessId             string   `protobuf:"bytes,1,opt,name=access_id,json=accessId,proto3" json:"access_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneAccessRequest) Reset()         { *m = FindOneAccessRequest{} }
func (m *FindOneAccessRequest) String() string { return proto.CompactTextString(m) }
func (*FindOneAccessRequest) ProtoMessage()    {}
func (*FindOneAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{8}
}

func (m *FindOneAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneAccessRequest.Unmarshal(m, b)
}
func (m *FindOneAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneAccessRequest.Marshal(b, m, deterministic)
}
func (m *FindOneAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneAccessRequest.Merge(m, src)
}
func (m *FindOneAccessRequest) XXX_Size() int {
	return xxx_messageInfo_FindOneAccessRequest.Size(m)
}
func (m *FindOneAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneAccessRequest proto.InternalMessageInfo

func (m *FindOneAccessRequest) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *FindOneAccessRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindOneAccessResponse struct {
	Access               *Access  `protobuf:"bytes,1,opt,name=access,proto3" json:"access"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneAccessResponse) Reset()         { *m = FindOneAccessResponse{} }
func (m *FindOneAccessResponse) String() string { return proto.CompactTextString(m) }
func (*FindOneAccessResponse) ProtoMessage()    {}
func (*FindOneAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{9}
}

func (m *FindOneAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneAccessResponse.Unmarshal(m, b)
}
func (m *FindOneAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneAccessResponse.Marshal(b, m, deterministic)
}
func (m *FindOneAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneAccessResponse.Merge(m, src)
}
func (m *FindOneAccessResponse) XXX_Size() int {
	return xxx_messageInfo_FindOneAccessResponse.Size(m)
}
func (m *FindOneAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneAccessResponse proto.InternalMessageInfo

func (m *FindOneAccessResponse) GetAccess() *Access {
	if m != nil {
		return m.Access
	}
	return nil
}

type AddAccessRequest struct {
	RoleId               string              `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	GroupId              string              `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Apps                 map[string]*AppData `protobuf:"bytes,3,rep,name=apps,proto3" json:"apps" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Writer               string              `protobuf:"bytes,4,opt,name=writer,proto3" json:"writer"`
	Database             string              `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AddAccessRequest) Reset()         { *m = AddAccessRequest{} }
func (m *AddAccessRequest) String() string { return proto.CompactTextString(m) }
func (*AddAccessRequest) ProtoMessage()    {}
func (*AddAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{10}
}

func (m *AddAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccessRequest.Unmarshal(m, b)
}
func (m *AddAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccessRequest.Marshal(b, m, deterministic)
}
func (m *AddAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccessRequest.Merge(m, src)
}
func (m *AddAccessRequest) XXX_Size() int {
	return xxx_messageInfo_AddAccessRequest.Size(m)
}
func (m *AddAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccessRequest proto.InternalMessageInfo

func (m *AddAccessRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *AddAccessRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *AddAccessRequest) GetApps() map[string]*AppData {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *AddAccessRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddAccessRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddAccessResponse struct {
	AccessId             string   `protobuf:"bytes,1,opt,name=access_id,json=accessId,proto3" json:"access_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccessResponse) Reset()         { *m = AddAccessResponse{} }
func (m *AddAccessResponse) String() string { return proto.CompactTextString(m) }
func (*AddAccessResponse) ProtoMessage()    {}
func (*AddAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{11}
}

func (m *AddAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccessResponse.Unmarshal(m, b)
}
func (m *AddAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccessResponse.Marshal(b, m, deterministic)
}
func (m *AddAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccessResponse.Merge(m, src)
}
func (m *AddAccessResponse) XXX_Size() int {
	return xxx_messageInfo_AddAccessResponse.Size(m)
}
func (m *AddAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccessResponse proto.InternalMessageInfo

func (m *AddAccessResponse) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

type HardDeleteAccessRequest struct {
	AccessList           []string `protobuf:"bytes,1,rep,name=access_list,json=accessList,proto3" json:"access_list"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardDeleteAccessRequest) Reset()         { *m = HardDeleteAccessRequest{} }
func (m *HardDeleteAccessRequest) String() string { return proto.CompactTextString(m) }
func (*HardDeleteAccessRequest) ProtoMessage()    {}
func (*HardDeleteAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{12}
}

func (m *HardDeleteAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardDeleteAccessRequest.Unmarshal(m, b)
}
func (m *HardDeleteAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardDeleteAccessRequest.Marshal(b, m, deterministic)
}
func (m *HardDeleteAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardDeleteAccessRequest.Merge(m, src)
}
func (m *HardDeleteAccessRequest) XXX_Size() int {
	return xxx_messageInfo_HardDeleteAccessRequest.Size(m)
}
func (m *HardDeleteAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HardDeleteAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HardDeleteAccessRequest proto.InternalMessageInfo

func (m *HardDeleteAccessRequest) GetAccessList() []string {
	if m != nil {
		return m.AccessList
	}
	return nil
}

func (m *HardDeleteAccessRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type HardDeleteAccessResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardDeleteAccessResponse) Reset()         { *m = HardDeleteAccessResponse{} }
func (m *HardDeleteAccessResponse) String() string { return proto.CompactTextString(m) }
func (*HardDeleteAccessResponse) ProtoMessage()    {}
func (*HardDeleteAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{13}
}

func (m *HardDeleteAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardDeleteAccessResponse.Unmarshal(m, b)
}
func (m *HardDeleteAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardDeleteAccessResponse.Marshal(b, m, deterministic)
}
func (m *HardDeleteAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardDeleteAccessResponse.Merge(m, src)
}
func (m *HardDeleteAccessResponse) XXX_Size() int {
	return xxx_messageInfo_HardDeleteAccessResponse.Size(m)
}
func (m *HardDeleteAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HardDeleteAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HardDeleteAccessResponse proto.InternalMessageInfo

type RecoverSelectAccessRequest struct {
	AccessList           []string `protobuf:"bytes,1,rep,name=access_list,json=accessList,proto3" json:"access_list"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverSelectAccessRequest) Reset()         { *m = RecoverSelectAccessRequest{} }
func (m *RecoverSelectAccessRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverSelectAccessRequest) ProtoMessage()    {}
func (*RecoverSelectAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{14}
}

func (m *RecoverSelectAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverSelectAccessRequest.Unmarshal(m, b)
}
func (m *RecoverSelectAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverSelectAccessRequest.Marshal(b, m, deterministic)
}
func (m *RecoverSelectAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverSelectAccessRequest.Merge(m, src)
}
func (m *RecoverSelectAccessRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverSelectAccessRequest.Size(m)
}
func (m *RecoverSelectAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverSelectAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverSelectAccessRequest proto.InternalMessageInfo

func (m *RecoverSelectAccessRequest) GetAccessList() []string {
	if m != nil {
		return m.AccessList
	}
	return nil
}

func (m *RecoverSelectAccessRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *RecoverSelectAccessRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type RecoverSelectAccessResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverSelectAccessResponse) Reset()         { *m = RecoverSelectAccessResponse{} }
func (m *RecoverSelectAccessResponse) String() string { return proto.CompactTextString(m) }
func (*RecoverSelectAccessResponse) ProtoMessage()    {}
func (*RecoverSelectAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{15}
}

func (m *RecoverSelectAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverSelectAccessResponse.Unmarshal(m, b)
}
func (m *RecoverSelectAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverSelectAccessResponse.Marshal(b, m, deterministic)
}
func (m *RecoverSelectAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverSelectAccessResponse.Merge(m, src)
}
func (m *RecoverSelectAccessResponse) XXX_Size() int {
	return xxx_messageInfo_RecoverSelectAccessResponse.Size(m)
}
func (m *RecoverSelectAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverSelectAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverSelectAccessResponse proto.InternalMessageInfo

type DeleteSelectAccessRequest struct {
	AccessList           []string `protobuf:"bytes,1,rep,name=access_list,json=accessList,proto3" json:"access_list"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSelectAccessRequest) Reset()         { *m = DeleteSelectAccessRequest{} }
func (m *DeleteSelectAccessRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSelectAccessRequest) ProtoMessage()    {}
func (*DeleteSelectAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{16}
}

func (m *DeleteSelectAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSelectAccessRequest.Unmarshal(m, b)
}
func (m *DeleteSelectAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSelectAccessRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSelectAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSelectAccessRequest.Merge(m, src)
}
func (m *DeleteSelectAccessRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSelectAccessRequest.Size(m)
}
func (m *DeleteSelectAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSelectAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSelectAccessRequest proto.InternalMessageInfo

func (m *DeleteSelectAccessRequest) GetAccessList() []string {
	if m != nil {
		return m.AccessList
	}
	return nil
}

func (m *DeleteSelectAccessRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteSelectAccessRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteSelectAccessResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSelectAccessResponse) Reset()         { *m = DeleteSelectAccessResponse{} }
func (m *DeleteSelectAccessResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSelectAccessResponse) ProtoMessage()    {}
func (*DeleteSelectAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{17}
}

func (m *DeleteSelectAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSelectAccessResponse.Unmarshal(m, b)
}
func (m *DeleteSelectAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSelectAccessResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSelectAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSelectAccessResponse.Merge(m, src)
}
func (m *DeleteSelectAccessResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSelectAccessResponse.Size(m)
}
func (m *DeleteSelectAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSelectAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSelectAccessResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Access)(nil), "access.Access")
	proto.RegisterMapType((map[string]*AppData)(nil), "access.Access.AppsEntry")
	proto.RegisterType((*AppData)(nil), "access.AppData")
	proto.RegisterMapType((map[string]*DataAccess)(nil), "access.AppData.DataAccessEntry")
	proto.RegisterType((*DataAccess)(nil), "access.DataAccess")
	proto.RegisterType((*DataAction)(nil), "access.DataAction")
	proto.RegisterType((*FindUserAccesssRequest)(nil), "access.FindUserAccesssRequest")
	proto.RegisterType((*FindUserAccesssResponse)(nil), "access.FindUserAccesssResponse")
	proto.RegisterType((*FindAccessRequest)(nil), "access.FindAccessRequest")
	proto.RegisterType((*FindAccessResponse)(nil), "access.FindAccessResponse")
	proto.RegisterType((*FindOneAccessRequest)(nil), "access.FindOneAccessRequest")
	proto.RegisterType((*FindOneAccessResponse)(nil), "access.FindOneAccessResponse")
	proto.RegisterType((*AddAccessRequest)(nil), "access.AddAccessRequest")
	proto.RegisterMapType((map[string]*AppData)(nil), "access.AddAccessRequest.AppsEntry")
	proto.RegisterType((*AddAccessResponse)(nil), "access.AddAccessResponse")
	proto.RegisterType((*HardDeleteAccessRequest)(nil), "access.HardDeleteAccessRequest")
	proto.RegisterType((*HardDeleteAccessResponse)(nil), "access.HardDeleteAccessResponse")
	proto.RegisterType((*RecoverSelectAccessRequest)(nil), "access.RecoverSelectAccessRequest")
	proto.RegisterType((*RecoverSelectAccessResponse)(nil), "access.RecoverSelectAccessResponse")
	proto.RegisterType((*DeleteSelectAccessRequest)(nil), "access.DeleteSelectAccessRequest")
	proto.RegisterType((*DeleteSelectAccessResponse)(nil), "access.DeleteSelectAccessResponse")
}

func init() { proto.RegisterFile("access.proto", fileDescriptor_a098e900d2c3a6f2) }

var fileDescriptor_a098e900d2c3a6f2 = []byte{
	// 851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0x5e, 0xe7, 0xc7, 0x89, 0x4f, 0xf8, 0x9d, 0xe5, 0xc7, 0x31, 0x64, 0x03, 0x5e, 0xed, 0x8a,
	0x8b, 0x15, 0xbb, 0x62, 0xa5, 0xaa, 0xe2, 0xa6, 0x0d, 0x82, 0x0a, 0xd4, 0xaa, 0xa8, 0x41, 0xb4,
	0x57, 0x28, 0x9d, 0xd8, 0xd3, 0xca, 0x6a, 0x64, 0x1b, 0x8f, 0x03, 0xf2, 0x33, 0xf4, 0x1d, 0xda,
	0x57, 0xea, 0x6d, 0xdf, 0xa5, 0x17, 0xd5, 0xfc, 0x78, 0x62, 0x3b, 0x76, 0xd4, 0x4a, 0xa8, 0x37,
	0xe0, 0x39, 0xdf, 0x9c, 0x73, 0xbe, 0xf3, 0xcd, 0x39, 0x07, 0x60, 0x09, 0x3b, 0x0e, 0xa1, 0xf4,
	0x30, 0x8c, 0x82, 0x38, 0x40, 0xba, 0x38, 0xd9, 0x1f, 0xeb, 0xa0, 0x0f, 0xf8, 0x27, 0xda, 0x01,
	0x43, 0x18, 0x47, 0x9e, 0x6b, 0x6a, 0x7b, 0xda, 0x81, 0x31, 0x6c, 0x0b, 0xc3, 0x85, 0x8b, 0xb6,
	0xa1, 0x15, 0x05, 0x13, 0xc2, 0xa0, 0x1a, 0x87, 0x74, 0x76, 0xbc, 0x70, 0x51, 0x17, 0xda, 0xef,
	0xa3, 0x60, 0x1a, 0x32, 0xa4, 0xce, 0x91, 0x16, 0x3f, 0x5f, 0xb8, 0xe8, 0x1f, 0x68, 0xe0, 0x30,
	0xa4, 0x66, 0x63, 0xaf, 0x7e, 0xd0, 0x39, 0x32, 0x0f, 0x25, 0x81, 0x81, 0xfc, 0x15, 0x86, 0xf4,
	0xcc, 0x8f, 0xa3, 0x64, 0xc8, 0x6f, 0xa1, 0x1e, 0x80, 0x13, 0x11, 0x1c, 0x13, 0x77, 0x84, 0x63,
	0xb3, 0xc9, 0x43, 0x19, 0xd2, 0x32, 0x88, 0xb3, 0xf0, 0x38, 0x31, 0xf5, 0x1c, 0x7c, 0x92, 0x30,
	0x78, 0x1a, 0xba, 0xa9, 0x77, 0x4b, 0xc0, 0xd2, 0x22, 0xbc, 0x53, 0x78, 0x9c, 0x98, 0xed, 0x1c,
	0x2c, 0xbc, 0x5d, 0x32, 0x21, 0xd2, 0xdb, 0x10, 0xb0, 0xb4, 0x08, 0xef, 0x14, 0x1e, 0x27, 0x26,
	0xe4, 0xe0, 0x93, 0xc4, 0x3a, 0x07, 0x43, 0x15, 0x83, 0xd6, 0xa0, 0xfe, 0x81, 0x24, 0x52, 0x3f,
	0xf6, 0x89, 0xfe, 0x82, 0xe6, 0x1d, 0x9e, 0x4c, 0x09, 0x17, 0xae, 0x73, 0xb4, 0xaa, 0x74, 0x08,
	0xc3, 0x53, 0x1c, 0xe3, 0xa1, 0x40, 0x8f, 0x6b, 0x8f, 0x35, 0xfb, 0x93, 0x06, 0x2d, 0x69, 0x46,
	0x4f, 0xa1, 0xe3, 0xe2, 0x18, 0x8f, 0xc4, 0x6d, 0x53, 0xe3, 0x22, 0xf6, 0x0b, 0xce, 0x87, 0xec,
	0x87, 0x10, 0x54, 0x68, 0x09, 0xae, 0x32, 0x58, 0xaf, 0x60, 0xb5, 0x00, 0x97, 0xb0, 0x3b, 0xc8,
	0xb3, 0x43, 0x69, 0x82, 0x99, 0x67, 0x96, 0xe0, 0x0d, 0xc0, 0x0c, 0x40, 0xfb, 0xb0, 0xc4, 0xd2,
	0xd1, 0x38, 0x88, 0xc8, 0xac, 0x69, 0x3a, 0xca, 0xc6, 0x7b, 0xa0, 0x85, 0x9d, 0xd8, 0x0b, 0x7c,
	0x6a, 0xd6, 0x78, 0x05, 0x85, 0x04, 0x0c, 0x1a, 0xa6, 0x57, 0xec, 0xcf, 0x5a, 0x1a, 0x9f, 0x9d,
	0x73, 0xbd, 0xa5, 0xe5, 0x7b, 0xab, 0x07, 0x20, 0x9b, 0x95, 0xd5, 0x23, 0x5a, 0x52, 0xb6, 0xef,
	0x73, 0x92, 0x30, 0x4f, 0x07, 0xfb, 0xa3, 0x77, 0x9e, 0x2f, 0xba, 0xb2, 0x3d, 0x6c, 0x39, 0xd8,
	0x7f, 0xe6, 0xf9, 0xdc, 0x93, 0x41, 0xe2, 0xf1, 0xcd, 0x06, 0x07, 0x0d, 0x07, 0xfb, 0xd7, 0xdc,
	0x90, 0xc2, 0xe2, 0x75, 0x79, 0x1b, 0x0a, 0xf8, 0x94, 0x1b, 0xec, 0x2f, 0x1a, 0x6c, 0xb1, 0x30,
	0xd7, 0x94, 0x44, 0x42, 0x05, 0x3a, 0x24, 0xb7, 0x53, 0x42, 0xe3, 0xec, 0x88, 0xb0, 0xc7, 0x2a,
	0x1f, 0x91, 0x5a, 0xbe, 0x8c, 0x4d, 0xd0, 0x71, 0x98, 0x99, 0x9d, 0x26, 0x0e, 0x99, 0xb9, 0x28,
	0x6c, 0x63, 0x5e, 0xd8, 0x0d, 0x68, 0x06, 0xf7, 0x3e, 0x89, 0xe4, 0xa4, 0x88, 0x03, 0xda, 0x02,
	0x5d, 0x68, 0x29, 0x27, 0x44, 0x9e, 0x90, 0x05, 0x6d, 0xe6, 0x3c, 0xc6, 0x94, 0xc8, 0xe1, 0x50,
	0x67, 0xfb, 0x18, 0xb6, 0xe7, 0x2a, 0xa2, 0x61, 0xe0, 0x53, 0x82, 0xfa, 0xd0, 0x99, 0xa9, 0x4c,
	0x65, 0x59, 0xa0, 0x64, 0xa6, 0xb6, 0x03, 0xeb, 0xcc, 0x57, 0x36, 0x4a, 0x99, 0x10, 0xda, 0x8f,
	0x09, 0x91, 0x25, 0x58, 0x2f, 0x10, 0x3c, 0x03, 0x94, 0x4d, 0x22, 0xb9, 0xfd, 0xab, 0xb8, 0x4d,
	0x3c, 0x1a, 0xcb, 0xf9, 0x58, 0xc9, 0x2f, 0x99, 0x94, 0xeb, 0x0b, 0x8f, 0xc6, 0xf6, 0x25, 0x6c,
	0xb0, 0x30, 0x97, 0x3e, 0xc9, 0xd3, 0x5d, 0xb8, 0xf7, 0xb2, 0xbc, 0x6a, 0x05, 0x5e, 0x4f, 0x60,
	0xb3, 0x10, 0x50, 0x52, 0xfb, 0x1b, 0x74, 0x35, 0xb5, 0x5a, 0x09, 0xab, 0x74, 0xf9, 0x7e, 0xd3,
	0x60, 0x6d, 0xe0, 0x3e, 0x80, 0x7a, 0x8f, 0xe4, 0xa6, 0xad, 0x73, 0x11, 0x6c, 0x95, 0xae, 0x10,
	0x7b, 0x6e, 0xe7, 0x6e, 0x81, 0x7e, 0x1f, 0x79, 0x31, 0x89, 0x64, 0x87, 0xc9, 0x53, 0xae, 0xea,
	0x66, 0xbe, 0xea, 0x07, 0xdc, 0x76, 0xff, 0xc1, 0x7a, 0x86, 0xa1, 0xd4, 0x6e, 0xd1, 0x6b, 0xd8,
	0xaf, 0x61, 0xfb, 0x1c, 0x47, 0xae, 0x98, 0xc5, 0xbc, 0x6c, 0xfd, 0xf9, 0x76, 0x30, 0xb2, 0xcf,
	0xbf, 0xf0, 0x25, 0x2d, 0x30, 0xe7, 0xe3, 0x0a, 0x42, 0xf6, 0x2d, 0x58, 0x43, 0xe2, 0x04, 0x77,
	0x24, 0xba, 0x22, 0x13, 0xe2, 0xc4, 0x3f, 0x99, 0x76, 0x26, 0x71, 0xad, 0x52, 0xe2, 0x62, 0xc3,
	0xf7, 0x60, 0xa7, 0x34, 0xa5, 0x64, 0x14, 0x42, 0x57, 0x30, 0xfd, 0x65, 0x84, 0x76, 0xc1, 0x2a,
	0xcb, 0x28, 0xf8, 0x1c, 0x7d, 0x6d, 0xc0, 0xb2, 0x30, 0x5d, 0x91, 0xe8, 0xce, 0x73, 0x08, 0xba,
	0x82, 0x95, 0xfc, 0x4a, 0x41, 0x7f, 0xa4, 0x7d, 0x50, 0xbe, 0x3c, 0xad, 0x7e, 0x25, 0x2e, 0x8b,
	0xfe, 0x0d, 0x9d, 0x01, 0xcc, 0xd6, 0x00, 0xea, 0x66, 0x1d, 0x72, 0x12, 0x58, 0x56, 0x19, 0xa4,
	0xc2, 0xbc, 0x84, 0xe5, 0xdc, 0xd4, 0xa2, 0xdd, 0xec, 0xf5, 0xe2, 0x76, 0xb0, 0x7a, 0x15, 0xa8,
	0x8a, 0x77, 0x02, 0x86, 0xea, 0x62, 0x64, 0x56, 0x8d, 0x9e, 0xd5, 0x2d, 0x41, 0x54, 0x8c, 0x1b,
	0x40, 0xf3, 0xfa, 0xa2, 0x7d, 0xf5, 0xa7, 0xb2, 0xea, 0xb5, 0x2d, 0x7b, 0xd1, 0x15, 0x15, 0xfe,
	0x0d, 0xac, 0x15, 0xdb, 0x1b, 0x29, 0xc1, 0x2b, 0x06, 0xca, 0xda, 0xab, 0xbe, 0xa0, 0x02, 0xbf,
	0x85, 0xdf, 0x4b, 0x1a, 0x15, 0x29, 0x56, 0xd5, 0x83, 0x63, 0xfd, 0xb9, 0xf0, 0x4e, 0x9a, 0x61,
	0xac, 0xf3, 0x7f, 0x57, 0xff, 0xff, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x90, 0x0a, 0xfb, 0xbf, 0xbe,
	0x0a, 0x00, 0x00,
}
