// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: upload.proto

package upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UploadService service

func NewUploadServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UploadService service

type UploadService interface {
	CSVUpload(ctx context.Context, in *CSVRequest, opts ...client.CallOption) (*CSVResponse, error)
	InventoryUpload(ctx context.Context, in *InventoryRequest, opts ...client.CallOption) (*InventoryResponse, error)
	MappingUpload(ctx context.Context, in *MappingRequest, opts ...client.CallOption) (*MappingResponse, error)
}

type uploadService struct {
	c    client.Client
	name string
}

func NewUploadService(name string, c client.Client) UploadService {
	return &uploadService{
		c:    c,
		name: name,
	}
}

func (c *uploadService) CSVUpload(ctx context.Context, in *CSVRequest, opts ...client.CallOption) (*CSVResponse, error) {
	req := c.c.NewRequest(c.name, "UploadService.CSVUpload", in)
	out := new(CSVResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadService) InventoryUpload(ctx context.Context, in *InventoryRequest, opts ...client.CallOption) (*InventoryResponse, error) {
	req := c.c.NewRequest(c.name, "UploadService.InventoryUpload", in)
	out := new(InventoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadService) MappingUpload(ctx context.Context, in *MappingRequest, opts ...client.CallOption) (*MappingResponse, error) {
	req := c.c.NewRequest(c.name, "UploadService.MappingUpload", in)
	out := new(MappingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UploadService service

type UploadServiceHandler interface {
	CSVUpload(context.Context, *CSVRequest, *CSVResponse) error
	InventoryUpload(context.Context, *InventoryRequest, *InventoryResponse) error
	MappingUpload(context.Context, *MappingRequest, *MappingResponse) error
}

func RegisterUploadServiceHandler(s server.Server, hdlr UploadServiceHandler, opts ...server.HandlerOption) error {
	type uploadService interface {
		CSVUpload(ctx context.Context, in *CSVRequest, out *CSVResponse) error
		InventoryUpload(ctx context.Context, in *InventoryRequest, out *InventoryResponse) error
		MappingUpload(ctx context.Context, in *MappingRequest, out *MappingResponse) error
	}
	type UploadService struct {
		uploadService
	}
	h := &uploadServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UploadService{h}, opts...))
}

type uploadServiceHandler struct {
	UploadServiceHandler
}

func (h *uploadServiceHandler) CSVUpload(ctx context.Context, in *CSVRequest, out *CSVResponse) error {
	return h.UploadServiceHandler.CSVUpload(ctx, in, out)
}

func (h *uploadServiceHandler) InventoryUpload(ctx context.Context, in *InventoryRequest, out *InventoryResponse) error {
	return h.UploadServiceHandler.InventoryUpload(ctx, in, out)
}

func (h *uploadServiceHandler) MappingUpload(ctx context.Context, in *MappingRequest, out *MappingResponse) error {
	return h.UploadServiceHandler.MappingUpload(ctx, in, out)
}
