// Code generated by protoc-gen-go. DO NOT EDIT.
// source: journal.proto

package journal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 分录
type Journal struct {
	JournalId            string     `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id"`
	JournalName          string     `protobuf:"bytes,2,opt,name=journal_name,json=journalName,proto3" json:"journal_name"`
	Patterns             []*Pattern `protobuf:"bytes,3,rep,name=patterns,proto3" json:"patterns"`
	AppId                string     `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id"`
	CreatedAt            string     `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string     `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string     `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string     `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Journal) Reset()         { *m = Journal{} }
func (m *Journal) String() string { return proto.CompactTextString(m) }
func (*Journal) ProtoMessage()    {}
func (*Journal) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{0}
}

func (m *Journal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Journal.Unmarshal(m, b)
}
func (m *Journal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Journal.Marshal(b, m, deterministic)
}
func (m *Journal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Journal.Merge(m, src)
}
func (m *Journal) XXX_Size() int {
	return xxx_messageInfo_Journal.Size(m)
}
func (m *Journal) XXX_DiscardUnknown() {
	xxx_messageInfo_Journal.DiscardUnknown(m)
}

var xxx_messageInfo_Journal proto.InternalMessageInfo

func (m *Journal) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *Journal) GetJournalName() string {
	if m != nil {
		return m.JournalName
	}
	return ""
}

func (m *Journal) GetPatterns() []*Pattern {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *Journal) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Journal) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Journal) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Journal) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Journal) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

// 分录pattern
type Pattern struct {
	PatternId            string     `protobuf:"bytes,1,opt,name=pattern_id,json=patternId,proto3" json:"pattern_id"`
	PatternName          string     `protobuf:"bytes,2,opt,name=pattern_name,json=patternName,proto3" json:"pattern_name"`
	Subjects             []*Subject `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pattern) Reset()         { *m = Pattern{} }
func (m *Pattern) String() string { return proto.CompactTextString(m) }
func (*Pattern) ProtoMessage()    {}
func (*Pattern) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{1}
}

func (m *Pattern) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pattern.Unmarshal(m, b)
}
func (m *Pattern) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pattern.Marshal(b, m, deterministic)
}
func (m *Pattern) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pattern.Merge(m, src)
}
func (m *Pattern) XXX_Size() int {
	return xxx_messageInfo_Pattern.Size(m)
}
func (m *Pattern) XXX_DiscardUnknown() {
	xxx_messageInfo_Pattern.DiscardUnknown(m)
}

var xxx_messageInfo_Pattern proto.InternalMessageInfo

func (m *Pattern) GetPatternId() string {
	if m != nil {
		return m.PatternId
	}
	return ""
}

func (m *Pattern) GetPatternName() string {
	if m != nil {
		return m.PatternName
	}
	return ""
}

func (m *Pattern) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

// 分录subject
type Subject struct {
	SubjectKey           string   `protobuf:"bytes,1,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key"`
	LendingDivision      string   `protobuf:"bytes,2,opt,name=lending_division,json=lendingDivision,proto3" json:"lending_division"`
	DefaultName          string   `protobuf:"bytes,3,opt,name=default_name,json=defaultName,proto3" json:"default_name"`
	SubjectName          string   `protobuf:"bytes,4,opt,name=subject_name,json=subjectName,proto3" json:"subject_name"`
	AmountName           string   `protobuf:"bytes,5,opt,name=amount_name,json=amountName,proto3" json:"amount_name"`
	AmountField          string   `protobuf:"bytes,6,opt,name=amount_field,json=amountField,proto3" json:"amount_field"`
	ChangeFlag           string   `protobuf:"bytes,7,opt,name=change_flag,json=changeFlag,proto3" json:"change_flag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{2}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetSubjectKey() string {
	if m != nil {
		return m.SubjectKey
	}
	return ""
}

func (m *Subject) GetLendingDivision() string {
	if m != nil {
		return m.LendingDivision
	}
	return ""
}

func (m *Subject) GetDefaultName() string {
	if m != nil {
		return m.DefaultName
	}
	return ""
}

func (m *Subject) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *Subject) GetAmountName() string {
	if m != nil {
		return m.AmountName
	}
	return ""
}

func (m *Subject) GetAmountField() string {
	if m != nil {
		return m.AmountField
	}
	return ""
}

func (m *Subject) GetChangeFlag() string {
	if m != nil {
		return m.ChangeFlag
	}
	return ""
}

// 查找多条记录
type JournalsRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JournalsRequest) Reset()         { *m = JournalsRequest{} }
func (m *JournalsRequest) String() string { return proto.CompactTextString(m) }
func (*JournalsRequest) ProtoMessage()    {}
func (*JournalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{3}
}

func (m *JournalsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalsRequest.Unmarshal(m, b)
}
func (m *JournalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalsRequest.Marshal(b, m, deterministic)
}
func (m *JournalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalsRequest.Merge(m, src)
}
func (m *JournalsRequest) XXX_Size() int {
	return xxx_messageInfo_JournalsRequest.Size(m)
}
func (m *JournalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JournalsRequest proto.InternalMessageInfo

func (m *JournalsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *JournalsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type JournalsResponse struct {
	Journals             []*Journal `protobuf:"bytes,1,rep,name=journals,proto3" json:"journals"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JournalsResponse) Reset()         { *m = JournalsResponse{} }
func (m *JournalsResponse) String() string { return proto.CompactTextString(m) }
func (*JournalsResponse) ProtoMessage()    {}
func (*JournalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{4}
}

func (m *JournalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalsResponse.Unmarshal(m, b)
}
func (m *JournalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalsResponse.Marshal(b, m, deterministic)
}
func (m *JournalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalsResponse.Merge(m, src)
}
func (m *JournalsResponse) XXX_Size() int {
	return xxx_messageInfo_JournalsResponse.Size(m)
}
func (m *JournalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JournalsResponse proto.InternalMessageInfo

func (m *JournalsResponse) GetJournals() []*Journal {
	if m != nil {
		return m.Journals
	}
	return nil
}

// 查询单条记录
type JournalRequest struct {
	JournalId            string   `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JournalRequest) Reset()         { *m = JournalRequest{} }
func (m *JournalRequest) String() string { return proto.CompactTextString(m) }
func (*JournalRequest) ProtoMessage()    {}
func (*JournalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{5}
}

func (m *JournalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalRequest.Unmarshal(m, b)
}
func (m *JournalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalRequest.Marshal(b, m, deterministic)
}
func (m *JournalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalRequest.Merge(m, src)
}
func (m *JournalRequest) XXX_Size() int {
	return xxx_messageInfo_JournalRequest.Size(m)
}
func (m *JournalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JournalRequest proto.InternalMessageInfo

func (m *JournalRequest) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *JournalRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *JournalRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type JournalResponse struct {
	Journal              *Journal `protobuf:"bytes,1,opt,name=journal,proto3" json:"journal"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JournalResponse) Reset()         { *m = JournalResponse{} }
func (m *JournalResponse) String() string { return proto.CompactTextString(m) }
func (*JournalResponse) ProtoMessage()    {}
func (*JournalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{6}
}

func (m *JournalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalResponse.Unmarshal(m, b)
}
func (m *JournalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalResponse.Marshal(b, m, deterministic)
}
func (m *JournalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalResponse.Merge(m, src)
}
func (m *JournalResponse) XXX_Size() int {
	return xxx_messageInfo_JournalResponse.Size(m)
}
func (m *JournalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JournalResponse proto.InternalMessageInfo

func (m *JournalResponse) GetJournal() *Journal {
	if m != nil {
		return m.Journal
	}
	return nil
}

// 导入数据
type ImportRequest struct {
	Journals             []*Journal `protobuf:"bytes,1,rep,name=journals,proto3" json:"journals"`
	Database             string     `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	Writer               string     `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ImportRequest) Reset()         { *m = ImportRequest{} }
func (m *ImportRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()    {}
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{7}
}

func (m *ImportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRequest.Unmarshal(m, b)
}
func (m *ImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRequest.Marshal(b, m, deterministic)
}
func (m *ImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRequest.Merge(m, src)
}
func (m *ImportRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRequest.Size(m)
}
func (m *ImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRequest proto.InternalMessageInfo

func (m *ImportRequest) GetJournals() []*Journal {
	if m != nil {
		return m.Journals
	}
	return nil
}

func (m *ImportRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ImportRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

type ImportResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportResponse) Reset()         { *m = ImportResponse{} }
func (m *ImportResponse) String() string { return proto.CompactTextString(m) }
func (*ImportResponse) ProtoMessage()    {}
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{8}
}

func (m *ImportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportResponse.Unmarshal(m, b)
}
func (m *ImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportResponse.Marshal(b, m, deterministic)
}
func (m *ImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportResponse.Merge(m, src)
}
func (m *ImportResponse) XXX_Size() int {
	return xxx_messageInfo_ImportResponse.Size(m)
}
func (m *ImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportResponse proto.InternalMessageInfo

// 更新记录
type ModifyRequest struct {
	JournalId            string   `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id"`
	PatternId            string   `protobuf:"bytes,3,opt,name=pattern_id,json=patternId,proto3" json:"pattern_id"`
	SubjectKey           string   `protobuf:"bytes,4,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key"`
	LendingDivision      string   `protobuf:"bytes,5,opt,name=lending_division,json=lendingDivision,proto3" json:"lending_division"`
	ChangeFlag           string   `protobuf:"bytes,11,opt,name=change_flag,json=changeFlag,proto3" json:"change_flag"`
	SubjectName          string   `protobuf:"bytes,6,opt,name=subject_name,json=subjectName,proto3" json:"subject_name"`
	AmountName           string   `protobuf:"bytes,7,opt,name=amount_name,json=amountName,proto3" json:"amount_name"`
	AmountField          string   `protobuf:"bytes,8,opt,name=amount_field,json=amountField,proto3" json:"amount_field"`
	Database             string   `protobuf:"bytes,9,opt,name=database,proto3" json:"database"`
	Writer               string   `protobuf:"bytes,10,opt,name=writer,proto3" json:"writer"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequest) Reset()         { *m = ModifyRequest{} }
func (m *ModifyRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequest) ProtoMessage()    {}
func (*ModifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{9}
}

func (m *ModifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequest.Unmarshal(m, b)
}
func (m *ModifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequest.Marshal(b, m, deterministic)
}
func (m *ModifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequest.Merge(m, src)
}
func (m *ModifyRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequest.Size(m)
}
func (m *ModifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequest proto.InternalMessageInfo

func (m *ModifyRequest) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *ModifyRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ModifyRequest) GetPatternId() string {
	if m != nil {
		return m.PatternId
	}
	return ""
}

func (m *ModifyRequest) GetSubjectKey() string {
	if m != nil {
		return m.SubjectKey
	}
	return ""
}

func (m *ModifyRequest) GetLendingDivision() string {
	if m != nil {
		return m.LendingDivision
	}
	return ""
}

func (m *ModifyRequest) GetChangeFlag() string {
	if m != nil {
		return m.ChangeFlag
	}
	return ""
}

func (m *ModifyRequest) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *ModifyRequest) GetAmountName() string {
	if m != nil {
		return m.AmountName
	}
	return ""
}

func (m *ModifyRequest) GetAmountField() string {
	if m != nil {
		return m.AmountField
	}
	return ""
}

func (m *ModifyRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ModifyRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

type ModifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyResponse) Reset()         { *m = ModifyResponse{} }
func (m *ModifyResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyResponse) ProtoMessage()    {}
func (*ModifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{10}
}

func (m *ModifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyResponse.Unmarshal(m, b)
}
func (m *ModifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyResponse.Marshal(b, m, deterministic)
}
func (m *ModifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyResponse.Merge(m, src)
}
func (m *ModifyResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyResponse.Size(m)
}
func (m *ModifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyResponse proto.InternalMessageInfo

// 添加分录下载设定
type AddDownloadSettingRequest struct {
	AppId                string       `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	LayoutName           string       `protobuf:"bytes,2,opt,name=layout_name,json=layoutName,proto3" json:"layout_name"`
	CharEncoding         string       `protobuf:"bytes,3,opt,name=char_encoding,json=charEncoding,proto3" json:"char_encoding"`
	HeaderRow            string       `protobuf:"bytes,4,opt,name=header_row,json=headerRow,proto3" json:"header_row"`
	SeparatorChar        string       `protobuf:"bytes,5,opt,name=separator_char,json=separatorChar,proto3" json:"separator_char"`
	LineBreaks           string       `protobuf:"bytes,6,opt,name=line_breaks,json=lineBreaks,proto3" json:"line_breaks"`
	FixedLength          bool         `protobuf:"varint,7,opt,name=fixed_length,json=fixedLength,proto3" json:"fixed_length"`
	NumberItems          int64        `protobuf:"varint,8,opt,name=number_items,json=numberItems,proto3" json:"number_items"`
	ValidFlag            string       `protobuf:"bytes,9,opt,name=valid_flag,json=validFlag,proto3" json:"valid_flag"`
	FieldRule            []*FieldRule `protobuf:"bytes,10,rep,name=field_rule,json=fieldRule,proto3" json:"field_rule"`
	Database             string       `protobuf:"bytes,11,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddDownloadSettingRequest) Reset()         { *m = AddDownloadSettingRequest{} }
func (m *AddDownloadSettingRequest) String() string { return proto.CompactTextString(m) }
func (*AddDownloadSettingRequest) ProtoMessage()    {}
func (*AddDownloadSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{11}
}

func (m *AddDownloadSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDownloadSettingRequest.Unmarshal(m, b)
}
func (m *AddDownloadSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDownloadSettingRequest.Marshal(b, m, deterministic)
}
func (m *AddDownloadSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDownloadSettingRequest.Merge(m, src)
}
func (m *AddDownloadSettingRequest) XXX_Size() int {
	return xxx_messageInfo_AddDownloadSettingRequest.Size(m)
}
func (m *AddDownloadSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDownloadSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDownloadSettingRequest proto.InternalMessageInfo

func (m *AddDownloadSettingRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddDownloadSettingRequest) GetLayoutName() string {
	if m != nil {
		return m.LayoutName
	}
	return ""
}

func (m *AddDownloadSettingRequest) GetCharEncoding() string {
	if m != nil {
		return m.CharEncoding
	}
	return ""
}

func (m *AddDownloadSettingRequest) GetHeaderRow() string {
	if m != nil {
		return m.HeaderRow
	}
	return ""
}

func (m *AddDownloadSettingRequest) GetSeparatorChar() string {
	if m != nil {
		return m.SeparatorChar
	}
	return ""
}

func (m *AddDownloadSettingRequest) GetLineBreaks() string {
	if m != nil {
		return m.LineBreaks
	}
	return ""
}

func (m *AddDownloadSettingRequest) GetFixedLength() bool {
	if m != nil {
		return m.FixedLength
	}
	return false
}

func (m *AddDownloadSettingRequest) GetNumberItems() int64 {
	if m != nil {
		return m.NumberItems
	}
	return 0
}

func (m *AddDownloadSettingRequest) GetValidFlag() string {
	if m != nil {
		return m.ValidFlag
	}
	return ""
}

func (m *AddDownloadSettingRequest) GetFieldRule() []*FieldRule {
	if m != nil {
		return m.FieldRule
	}
	return nil
}

func (m *AddDownloadSettingRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddDownloadSettingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDownloadSettingResponse) Reset()         { *m = AddDownloadSettingResponse{} }
func (m *AddDownloadSettingResponse) String() string { return proto.CompactTextString(m) }
func (*AddDownloadSettingResponse) ProtoMessage()    {}
func (*AddDownloadSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{12}
}

func (m *AddDownloadSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDownloadSettingResponse.Unmarshal(m, b)
}
func (m *AddDownloadSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDownloadSettingResponse.Marshal(b, m, deterministic)
}
func (m *AddDownloadSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDownloadSettingResponse.Merge(m, src)
}
func (m *AddDownloadSettingResponse) XXX_Size() int {
	return xxx_messageInfo_AddDownloadSettingResponse.Size(m)
}
func (m *AddDownloadSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDownloadSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDownloadSettingResponse proto.InternalMessageInfo

// 字段规则
type FieldRule struct {
	DownloadName         string            `protobuf:"bytes,1,opt,name=download_name,json=downloadName,proto3" json:"download_name"`
	FieldConditions      []*FieldCondition `protobuf:"bytes,2,rep,name=field_conditions,json=fieldConditions,proto3" json:"field_conditions"`
	FieldId              string            `protobuf:"bytes,3,opt,name=field_id,json=fieldId,proto3" json:"field_id"`
	SettingMethod        string            `protobuf:"bytes,4,opt,name=setting_method,json=settingMethod,proto3" json:"setting_method"`
	FieldType            string            `protobuf:"bytes,5,opt,name=field_type,json=fieldType,proto3" json:"field_type"`
	DatastoreId          string            `protobuf:"bytes,6,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	Format               string            `protobuf:"bytes,7,opt,name=format,proto3" json:"format"`
	EditContent          string            `protobuf:"bytes,8,opt,name=edit_content,json=editContent,proto3" json:"edit_content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FieldRule) Reset()         { *m = FieldRule{} }
func (m *FieldRule) String() string { return proto.CompactTextString(m) }
func (*FieldRule) ProtoMessage()    {}
func (*FieldRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{13}
}

func (m *FieldRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldRule.Unmarshal(m, b)
}
func (m *FieldRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldRule.Marshal(b, m, deterministic)
}
func (m *FieldRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldRule.Merge(m, src)
}
func (m *FieldRule) XXX_Size() int {
	return xxx_messageInfo_FieldRule.Size(m)
}
func (m *FieldRule) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldRule.DiscardUnknown(m)
}

var xxx_messageInfo_FieldRule proto.InternalMessageInfo

func (m *FieldRule) GetDownloadName() string {
	if m != nil {
		return m.DownloadName
	}
	return ""
}

func (m *FieldRule) GetFieldConditions() []*FieldCondition {
	if m != nil {
		return m.FieldConditions
	}
	return nil
}

func (m *FieldRule) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

func (m *FieldRule) GetSettingMethod() string {
	if m != nil {
		return m.SettingMethod
	}
	return ""
}

func (m *FieldRule) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *FieldRule) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *FieldRule) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *FieldRule) GetEditContent() string {
	if m != nil {
		return m.EditContent
	}
	return ""
}

// 自定义条件
type FieldCondition struct {
	ConditionId          string        `protobuf:"bytes,1,opt,name=condition_id,json=conditionId,proto3" json:"condition_id"`
	ConditionName        string        `protobuf:"bytes,2,opt,name=condition_name,json=conditionName,proto3" json:"condition_name"`
	FieldGroups          []*FieldGroup `protobuf:"bytes,3,rep,name=field_groups,json=fieldGroups,proto3" json:"field_groups"`
	ThenValue            string        `protobuf:"bytes,4,opt,name=then_value,json=thenValue,proto3" json:"then_value"`
	ElseValue            string        `protobuf:"bytes,5,opt,name=else_value,json=elseValue,proto3" json:"else_value"`
	ThenType             string        `protobuf:"bytes,6,opt,name=then_type,json=thenType,proto3" json:"then_type"`
	ElseType             string        `protobuf:"bytes,7,opt,name=else_type,json=elseType,proto3" json:"else_type"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FieldCondition) Reset()         { *m = FieldCondition{} }
func (m *FieldCondition) String() string { return proto.CompactTextString(m) }
func (*FieldCondition) ProtoMessage()    {}
func (*FieldCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{14}
}

func (m *FieldCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldCondition.Unmarshal(m, b)
}
func (m *FieldCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldCondition.Marshal(b, m, deterministic)
}
func (m *FieldCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldCondition.Merge(m, src)
}
func (m *FieldCondition) XXX_Size() int {
	return xxx_messageInfo_FieldCondition.Size(m)
}
func (m *FieldCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldCondition.DiscardUnknown(m)
}

var xxx_messageInfo_FieldCondition proto.InternalMessageInfo

func (m *FieldCondition) GetConditionId() string {
	if m != nil {
		return m.ConditionId
	}
	return ""
}

func (m *FieldCondition) GetConditionName() string {
	if m != nil {
		return m.ConditionName
	}
	return ""
}

func (m *FieldCondition) GetFieldGroups() []*FieldGroup {
	if m != nil {
		return m.FieldGroups
	}
	return nil
}

func (m *FieldCondition) GetThenValue() string {
	if m != nil {
		return m.ThenValue
	}
	return ""
}

func (m *FieldCondition) GetElseValue() string {
	if m != nil {
		return m.ElseValue
	}
	return ""
}

func (m *FieldCondition) GetThenType() string {
	if m != nil {
		return m.ThenType
	}
	return ""
}

func (m *FieldCondition) GetElseType() string {
	if m != nil {
		return m.ElseType
	}
	return ""
}

// 条件组
type FieldGroup struct {
	GroupId              string      `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	GroupName            string      `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	Type                 string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	SwitchType           string      `protobuf:"bytes,4,opt,name=switch_type,json=switchType,proto3" json:"switch_type"`
	FieldCons            []*FieldCon `protobuf:"bytes,5,rep,name=field_cons,json=fieldCons,proto3" json:"field_cons"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FieldGroup) Reset()         { *m = FieldGroup{} }
func (m *FieldGroup) String() string { return proto.CompactTextString(m) }
func (*FieldGroup) ProtoMessage()    {}
func (*FieldGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{15}
}

func (m *FieldGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldGroup.Unmarshal(m, b)
}
func (m *FieldGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldGroup.Marshal(b, m, deterministic)
}
func (m *FieldGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldGroup.Merge(m, src)
}
func (m *FieldGroup) XXX_Size() int {
	return xxx_messageInfo_FieldGroup.Size(m)
}
func (m *FieldGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldGroup.DiscardUnknown(m)
}

var xxx_messageInfo_FieldGroup proto.InternalMessageInfo

func (m *FieldGroup) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *FieldGroup) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *FieldGroup) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FieldGroup) GetSwitchType() string {
	if m != nil {
		return m.SwitchType
	}
	return ""
}

func (m *FieldGroup) GetFieldCons() []*FieldCon {
	if m != nil {
		return m.FieldCons
	}
	return nil
}

// 小条件
type FieldCon struct {
	ConId                string   `protobuf:"bytes,1,opt,name=con_id,json=conId,proto3" json:"con_id"`
	ConName              string   `protobuf:"bytes,2,opt,name=con_name,json=conName,proto3" json:"con_name"`
	ConField             string   `protobuf:"bytes,3,opt,name=con_field,json=conField,proto3" json:"con_field"`
	ConOperator          string   `protobuf:"bytes,4,opt,name=con_operator,json=conOperator,proto3" json:"con_operator"`
	ConValue             string   `protobuf:"bytes,5,opt,name=con_value,json=conValue,proto3" json:"con_value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldCon) Reset()         { *m = FieldCon{} }
func (m *FieldCon) String() string { return proto.CompactTextString(m) }
func (*FieldCon) ProtoMessage()    {}
func (*FieldCon) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{16}
}

func (m *FieldCon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldCon.Unmarshal(m, b)
}
func (m *FieldCon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldCon.Marshal(b, m, deterministic)
}
func (m *FieldCon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldCon.Merge(m, src)
}
func (m *FieldCon) XXX_Size() int {
	return xxx_messageInfo_FieldCon.Size(m)
}
func (m *FieldCon) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldCon.DiscardUnknown(m)
}

var xxx_messageInfo_FieldCon proto.InternalMessageInfo

func (m *FieldCon) GetConId() string {
	if m != nil {
		return m.ConId
	}
	return ""
}

func (m *FieldCon) GetConName() string {
	if m != nil {
		return m.ConName
	}
	return ""
}

func (m *FieldCon) GetConField() string {
	if m != nil {
		return m.ConField
	}
	return ""
}

func (m *FieldCon) GetConOperator() string {
	if m != nil {
		return m.ConOperator
	}
	return ""
}

func (m *FieldCon) GetConValue() string {
	if m != nil {
		return m.ConValue
	}
	return ""
}

// 查询分录下载设定
type FindDownloadSettingRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindDownloadSettingRequest) Reset()         { *m = FindDownloadSettingRequest{} }
func (m *FindDownloadSettingRequest) String() string { return proto.CompactTextString(m) }
func (*FindDownloadSettingRequest) ProtoMessage()    {}
func (*FindDownloadSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{17}
}

func (m *FindDownloadSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDownloadSettingRequest.Unmarshal(m, b)
}
func (m *FindDownloadSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDownloadSettingRequest.Marshal(b, m, deterministic)
}
func (m *FindDownloadSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDownloadSettingRequest.Merge(m, src)
}
func (m *FindDownloadSettingRequest) XXX_Size() int {
	return xxx_messageInfo_FindDownloadSettingRequest.Size(m)
}
func (m *FindDownloadSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDownloadSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindDownloadSettingRequest proto.InternalMessageInfo

func (m *FindDownloadSettingRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindDownloadSettingRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindDownloadSettingResponse struct {
	AppId                string       `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	LayoutName           string       `protobuf:"bytes,2,opt,name=layout_name,json=layoutName,proto3" json:"layout_name"`
	CharEncoding         string       `protobuf:"bytes,3,opt,name=char_encoding,json=charEncoding,proto3" json:"char_encoding"`
	HeaderRow            string       `protobuf:"bytes,4,opt,name=header_row,json=headerRow,proto3" json:"header_row"`
	SeparatorChar        string       `protobuf:"bytes,5,opt,name=separator_char,json=separatorChar,proto3" json:"separator_char"`
	LineBreaks           string       `protobuf:"bytes,6,opt,name=line_breaks,json=lineBreaks,proto3" json:"line_breaks"`
	FixedLength          bool         `protobuf:"varint,7,opt,name=fixed_length,json=fixedLength,proto3" json:"fixed_length"`
	NumberItems          int64        `protobuf:"varint,8,opt,name=number_items,json=numberItems,proto3" json:"number_items"`
	ValidFlag            string       `protobuf:"bytes,9,opt,name=valid_flag,json=validFlag,proto3" json:"valid_flag"`
	FieldRule            []*FieldRule `protobuf:"bytes,10,rep,name=field_rule,json=fieldRule,proto3" json:"field_rule"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FindDownloadSettingResponse) Reset()         { *m = FindDownloadSettingResponse{} }
func (m *FindDownloadSettingResponse) String() string { return proto.CompactTextString(m) }
func (*FindDownloadSettingResponse) ProtoMessage()    {}
func (*FindDownloadSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{18}
}

func (m *FindDownloadSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDownloadSettingResponse.Unmarshal(m, b)
}
func (m *FindDownloadSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDownloadSettingResponse.Marshal(b, m, deterministic)
}
func (m *FindDownloadSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDownloadSettingResponse.Merge(m, src)
}
func (m *FindDownloadSettingResponse) XXX_Size() int {
	return xxx_messageInfo_FindDownloadSettingResponse.Size(m)
}
func (m *FindDownloadSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDownloadSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindDownloadSettingResponse proto.InternalMessageInfo

func (m *FindDownloadSettingResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindDownloadSettingResponse) GetLayoutName() string {
	if m != nil {
		return m.LayoutName
	}
	return ""
}

func (m *FindDownloadSettingResponse) GetCharEncoding() string {
	if m != nil {
		return m.CharEncoding
	}
	return ""
}

func (m *FindDownloadSettingResponse) GetHeaderRow() string {
	if m != nil {
		return m.HeaderRow
	}
	return ""
}

func (m *FindDownloadSettingResponse) GetSeparatorChar() string {
	if m != nil {
		return m.SeparatorChar
	}
	return ""
}

func (m *FindDownloadSettingResponse) GetLineBreaks() string {
	if m != nil {
		return m.LineBreaks
	}
	return ""
}

func (m *FindDownloadSettingResponse) GetFixedLength() bool {
	if m != nil {
		return m.FixedLength
	}
	return false
}

func (m *FindDownloadSettingResponse) GetNumberItems() int64 {
	if m != nil {
		return m.NumberItems
	}
	return 0
}

func (m *FindDownloadSettingResponse) GetValidFlag() string {
	if m != nil {
		return m.ValidFlag
	}
	return ""
}

func (m *FindDownloadSettingResponse) GetFieldRule() []*FieldRule {
	if m != nil {
		return m.FieldRule
	}
	return nil
}

// 查询分录下载设定
type FindDownloadSettingsRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindDownloadSettingsRequest) Reset()         { *m = FindDownloadSettingsRequest{} }
func (m *FindDownloadSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*FindDownloadSettingsRequest) ProtoMessage()    {}
func (*FindDownloadSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{19}
}

func (m *FindDownloadSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDownloadSettingsRequest.Unmarshal(m, b)
}
func (m *FindDownloadSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDownloadSettingsRequest.Marshal(b, m, deterministic)
}
func (m *FindDownloadSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDownloadSettingsRequest.Merge(m, src)
}
func (m *FindDownloadSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_FindDownloadSettingsRequest.Size(m)
}
func (m *FindDownloadSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDownloadSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindDownloadSettingsRequest proto.InternalMessageInfo

func (m *FindDownloadSettingsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindDownloadSettingsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindDownloadSettingsResponse struct {
	FieldConf            []*FindDownloadSettingResponse `protobuf:"bytes,1,rep,name=field_conf,json=fieldConf,proto3" json:"field_conf"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *FindDownloadSettingsResponse) Reset()         { *m = FindDownloadSettingsResponse{} }
func (m *FindDownloadSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*FindDownloadSettingsResponse) ProtoMessage()    {}
func (*FindDownloadSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{20}
}

func (m *FindDownloadSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDownloadSettingsResponse.Unmarshal(m, b)
}
func (m *FindDownloadSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDownloadSettingsResponse.Marshal(b, m, deterministic)
}
func (m *FindDownloadSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDownloadSettingsResponse.Merge(m, src)
}
func (m *FindDownloadSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_FindDownloadSettingsResponse.Size(m)
}
func (m *FindDownloadSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDownloadSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindDownloadSettingsResponse proto.InternalMessageInfo

func (m *FindDownloadSettingsResponse) GetFieldConf() []*FindDownloadSettingResponse {
	if m != nil {
		return m.FieldConf
	}
	return nil
}

func init() {
	proto.RegisterType((*Journal)(nil), "journal.Journal")
	proto.RegisterType((*Pattern)(nil), "journal.Pattern")
	proto.RegisterType((*Subject)(nil), "journal.Subject")
	proto.RegisterType((*JournalsRequest)(nil), "journal.JournalsRequest")
	proto.RegisterType((*JournalsResponse)(nil), "journal.JournalsResponse")
	proto.RegisterType((*JournalRequest)(nil), "journal.JournalRequest")
	proto.RegisterType((*JournalResponse)(nil), "journal.JournalResponse")
	proto.RegisterType((*ImportRequest)(nil), "journal.ImportRequest")
	proto.RegisterType((*ImportResponse)(nil), "journal.ImportResponse")
	proto.RegisterType((*ModifyRequest)(nil), "journal.ModifyRequest")
	proto.RegisterType((*ModifyResponse)(nil), "journal.ModifyResponse")
	proto.RegisterType((*AddDownloadSettingRequest)(nil), "journal.AddDownloadSettingRequest")
	proto.RegisterType((*AddDownloadSettingResponse)(nil), "journal.AddDownloadSettingResponse")
	proto.RegisterType((*FieldRule)(nil), "journal.FieldRule")
	proto.RegisterType((*FieldCondition)(nil), "journal.FieldCondition")
	proto.RegisterType((*FieldGroup)(nil), "journal.FieldGroup")
	proto.RegisterType((*FieldCon)(nil), "journal.FieldCon")
	proto.RegisterType((*FindDownloadSettingRequest)(nil), "journal.FindDownloadSettingRequest")
	proto.RegisterType((*FindDownloadSettingResponse)(nil), "journal.FindDownloadSettingResponse")
	proto.RegisterType((*FindDownloadSettingsRequest)(nil), "journal.FindDownloadSettingsRequest")
	proto.RegisterType((*FindDownloadSettingsResponse)(nil), "journal.FindDownloadSettingsResponse")
}

func init() { proto.RegisterFile("journal.proto", fileDescriptor_04fd98cceb1b9191) }

var fileDescriptor_04fd98cceb1b9191 = []byte{
	// 1271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0x8f, 0xed, 0x24, 0xb6, 0x9f, 0xe3, 0x24, 0x6c, 0xa1, 0x71, 0x9c, 0xa2, 0xb4, 0x1b, 0x2a,
	0x15, 0x84, 0x2a, 0x28, 0x12, 0x37, 0x24, 0x9a, 0xa4, 0x41, 0x06, 0x4a, 0x2b, 0x07, 0x71, 0x5d,
	0x8d, 0x77, 0xc6, 0xf6, 0xb6, 0xeb, 0x99, 0xed, 0xee, 0x6c, 0x82, 0x6f, 0x9c, 0x11, 0x37, 0x4e,
	0x7c, 0x08, 0x4e, 0x7c, 0x10, 0xbe, 0x08, 0x5f, 0x80, 0x1b, 0x9a, 0x37, 0x6f, 0xd6, 0xeb, 0x3f,
	0x49, 0x5a, 0x55, 0xdc, 0x7a, 0xf3, 0xfe, 0xde, 0x9b, 0x99, 0xdf, 0xfc, 0x7e, 0xef, 0xcd, 0x8c,
	0xa1, 0xfd, 0x42, 0xe5, 0xa9, 0x64, 0xf1, 0xc3, 0x24, 0x55, 0x5a, 0x79, 0x75, 0xfa, 0xf4, 0x7f,
	0xab, 0x42, 0xfd, 0x5b, 0xfb, 0xdb, 0xfb, 0x10, 0x80, 0xe0, 0x20, 0xe2, 0x9d, 0xca, 0xdd, 0xca,
	0x83, 0x66, 0xbf, 0x49, 0x48, 0x8f, 0x7b, 0xf7, 0x60, 0xcb, 0x85, 0x25, 0x9b, 0x88, 0x4e, 0x15,
	0x13, 0x5a, 0x84, 0xfd, 0xc0, 0x26, 0xc2, 0xfb, 0x14, 0x1a, 0x09, 0xd3, 0x5a, 0xa4, 0x32, 0xeb,
	0xd4, 0xee, 0xd6, 0x1e, 0xb4, 0x1e, 0xed, 0x3e, 0x74, 0x0b, 0x3f, 0xb7, 0x81, 0x7e, 0x91, 0xe1,
	0x7d, 0x00, 0x9b, 0x2c, 0x49, 0xcc, 0x5a, 0xeb, 0x38, 0xd5, 0x06, 0x4b, 0x92, 0x1e, 0x37, 0x34,
	0xc2, 0x54, 0x30, 0x2d, 0x78, 0xc0, 0x74, 0x67, 0xc3, 0xd2, 0x20, 0xe4, 0xb1, 0x2e, 0x87, 0x07,
	0xd3, 0xce, 0xe6, 0x5c, 0xf8, 0x78, 0x6a, 0xc2, 0x79, 0xc2, 0xdd, 0xe8, 0xba, 0x0d, 0x13, 0x62,
	0x47, 0xbb, 0xf0, 0x60, 0xda, 0x69, 0xcc, 0x85, 0x8f, 0xa7, 0xfe, 0x14, 0xea, 0xc4, 0xd3, 0x64,
	0x12, 0xd3, 0x92, 0x1a, 0x84, 0x58, 0x35, 0x5c, 0xb8, 0xac, 0x06, 0x61, 0x4e, 0x8d, 0x2c, 0x1f,
	0xbc, 0x10, 0xa1, 0x5e, 0x56, 0xe3, 0xdc, 0x06, 0xfa, 0x45, 0x86, 0xff, 0x4b, 0x15, 0xea, 0x84,
	0x7a, 0x87, 0xd0, 0x22, 0x3c, 0x78, 0x29, 0xa6, 0xb4, 0x38, 0x10, 0xf4, 0x9d, 0x98, 0x7a, 0x1f,
	0xc3, 0x6e, 0x2c, 0x24, 0x8f, 0xe4, 0x28, 0xe0, 0xd1, 0x45, 0x94, 0x45, 0x4a, 0x12, 0x83, 0x1d,
	0xc2, 0x4f, 0x09, 0x36, 0x44, 0xb9, 0x18, 0xb2, 0x3c, 0xd6, 0x96, 0x68, 0xcd, 0x12, 0x25, 0x0c,
	0x89, 0xde, 0x83, 0x2d, 0xb7, 0x1c, 0xa6, 0x58, 0x3b, 0x1c, 0x05, 0x4c, 0x39, 0x84, 0x16, 0x9b,
	0xa8, 0x5c, 0x52, 0x86, 0x75, 0x05, 0x2c, 0xe4, 0xe6, 0xa0, 0x84, 0x61, 0x24, 0x62, 0x4e, 0xc6,
	0xd0, 0xa0, 0x33, 0x03, 0x99, 0x39, 0xc2, 0x31, 0x93, 0x23, 0x11, 0x0c, 0x63, 0x36, 0x22, 0x6f,
	0xc0, 0x42, 0x67, 0x31, 0x1b, 0xf9, 0xa7, 0xb0, 0x43, 0xb5, 0x98, 0xf5, 0xc5, 0xab, 0x5c, 0x64,
	0xba, 0x54, 0x23, 0x95, 0x72, 0x8d, 0x74, 0xa1, 0xc1, 0x99, 0x66, 0x03, 0x96, 0x39, 0xe5, 0x8b,
	0x6f, 0xff, 0x6b, 0xd8, 0x9d, 0xcd, 0x92, 0x25, 0x4a, 0x66, 0x68, 0x05, 0x29, 0x9f, 0x75, 0x2a,
	0x0b, 0x56, 0x50, 0x72, 0xbf, 0xc8, 0xf0, 0x07, 0xb0, 0xed, 0x40, 0xa2, 0x71, 0x43, 0x6b, 0xcc,
	0x58, 0x56, 0xaf, 0x62, 0x59, 0x5b, 0x60, 0xf9, 0x55, 0xb1, 0xd7, 0x82, 0xe4, 0x27, 0xe0, 0xda,
	0x12, 0x57, 0x58, 0xc5, 0xb1, 0xe8, 0xdb, 0x57, 0xd0, 0xee, 0x4d, 0x12, 0x95, 0x6a, 0xc7, 0xf0,
	0x8d, 0x76, 0x78, 0x9d, 0x7e, 0xde, 0x6d, 0xd8, 0xbc, 0x4c, 0x23, 0x2d, 0x52, 0xe2, 0x4c, 0x5f,
	0xfe, 0x2e, 0x6c, 0xbb, 0x25, 0x2d, 0x61, 0xff, 0x9f, 0x2a, 0xb4, 0x9f, 0x2a, 0x1e, 0x0d, 0xa7,
	0x6f, 0xa7, 0xd3, 0x7c, 0xab, 0xd5, 0x16, 0x5b, 0x6d, 0xa1, 0x1b, 0xd6, 0x5f, 0xab, 0x1b, 0x36,
	0x56, 0x77, 0xc3, 0x42, 0x0d, 0xb6, 0x16, 0x6b, 0x70, 0xa9, 0x17, 0x36, 0x6f, 0xec, 0x85, 0xfa,
	0x8d, 0xbd, 0xd0, 0x58, 0xee, 0x85, 0xb2, 0x01, 0xcd, 0x2b, 0x0d, 0x80, 0x45, 0x03, 0x9c, 0xda,
	0x64, 0xc0, 0xef, 0x35, 0xd8, 0x7f, 0xcc, 0xf9, 0xa9, 0xba, 0x94, 0xb1, 0x62, 0xfc, 0x5c, 0x68,
	0x1d, 0xc9, 0xd1, 0x0d, 0xbd, 0x73, 0x08, 0xad, 0x98, 0x4d, 0x55, 0xae, 0xcb, 0x07, 0x17, 0x58,
	0x08, 0xe9, 0x1f, 0x41, 0x3b, 0x1c, 0xb3, 0x34, 0x10, 0x32, 0x54, 0x46, 0x3c, 0x72, 0x64, 0xcb,
	0x80, 0x4f, 0x08, 0x33, 0x9e, 0x8d, 0x05, 0xe3, 0x22, 0x0d, 0x52, 0x75, 0x49, 0x9e, 0x34, 0x2d,
	0xd2, 0x57, 0x97, 0xde, 0x7d, 0xd8, 0xce, 0x44, 0xc2, 0x52, 0xa6, 0x55, 0x1a, 0x98, 0x81, 0x64,
	0x48, 0xbb, 0x40, 0x4f, 0xc6, 0x2c, 0x45, 0x2e, 0x91, 0x14, 0xc1, 0x20, 0x15, 0xec, 0x65, 0x46,
	0x62, 0x83, 0x81, 0x8e, 0x11, 0x31, 0x52, 0x0e, 0xa3, 0x9f, 0x05, 0x0f, 0x62, 0x21, 0x47, 0x7a,
	0x8c, 0x62, 0x37, 0xfa, 0x2d, 0xc4, 0xbe, 0x47, 0xc8, 0xa4, 0xc8, 0x7c, 0x32, 0x10, 0x69, 0x10,
	0x69, 0x31, 0xc9, 0x50, 0xed, 0x5a, 0xbf, 0x65, 0xb1, 0x9e, 0x81, 0x0c, 0xd9, 0x0b, 0x16, 0x47,
	0xdc, 0x9a, 0x6e, 0xf5, 0x6e, 0x22, 0x82, 0x9e, 0x7f, 0x0e, 0x80, 0x46, 0x05, 0x69, 0x1e, 0x8b,
	0x0e, 0x60, 0xf7, 0x78, 0x45, 0xf7, 0xa0, 0x61, 0xfd, 0x3c, 0x16, 0xfd, 0xe6, 0xd0, 0xfd, 0x9c,
	0xf3, 0xaf, 0xb5, 0xd0, 0xda, 0x77, 0xa0, 0xbb, 0xca, 0x14, 0xf2, 0xec, 0xaf, 0x2a, 0x34, 0x8b,
	0x29, 0x8d, 0xd6, 0x9c, 0x12, 0xad, 0x1d, 0xd6, 0xaa, 0x2d, 0x07, 0xa2, 0x21, 0xc7, 0xb0, 0x6b,
	0xf9, 0x85, 0x4a, 0xf2, 0x48, 0x47, 0x4a, 0x66, 0x9d, 0x2a, 0xb2, 0xdc, 0x9b, 0x67, 0x79, 0xe2,
	0xe2, 0xfd, 0x9d, 0xe1, 0xdc, 0x77, 0xe6, 0xed, 0x43, 0xc3, 0xce, 0x51, 0x74, 0x58, 0x1d, 0xbf,
	0x7b, 0xdc, 0x7a, 0x85, 0x24, 0x83, 0x89, 0xd0, 0x63, 0xe5, 0xee, 0xe3, 0x36, 0xa1, 0x4f, 0x11,
	0x34, 0x22, 0xda, 0x19, 0xf4, 0x34, 0x71, 0x37, 0x80, 0x55, 0xe4, 0xc7, 0x69, 0x82, 0x45, 0x6f,
	0x14, 0xc8, 0xb4, 0x4a, 0x85, 0x59, 0x84, 0x1a, 0xa7, 0xc0, 0x7a, 0xdc, 0x14, 0xf6, 0x50, 0xa5,
	0x93, 0xe2, 0x5e, 0xa6, 0x2f, 0x33, 0x54, 0xf0, 0x48, 0x9b, 0xed, 0x69, 0x21, 0xb5, 0xeb, 0x17,
	0x83, 0x9d, 0x58, 0xc8, 0xff, 0xb5, 0x0a, 0xdb, 0xf3, 0x5b, 0x34, 0xa3, 0x0a, 0x3d, 0x66, 0x45,
	0xde, 0x2a, 0x30, 0xbb, 0xb3, 0x59, 0x4a, 0xa9, 0xda, 0xdb, 0x05, 0x8a, 0xfa, 0x7e, 0x69, 0x8a,
	0xcc, 0xec, 0x6c, 0x94, 0xaa, 0x3c, 0x71, 0x97, 0xf5, 0xad, 0x79, 0x6d, 0xbf, 0x31, 0x31, 0x53,
	0x79, 0xee, 0x37, 0x96, 0x95, 0x1e, 0x0b, 0x19, 0x5c, 0xb0, 0x38, 0x77, 0xb7, 0x66, 0xd3, 0x20,
	0x3f, 0x19, 0xc0, 0x84, 0x45, 0x9c, 0x09, 0x0a, 0x93, 0x60, 0x06, 0xb1, 0xe1, 0x03, 0xc0, 0x5c,
	0x2b, 0xa7, 0x55, 0xab, 0x61, 0x00, 0x54, 0xf3, 0x00, 0x30, 0xd3, 0x06, 0xad, 0x5a, 0x0d, 0x03,
	0x98, 0xa0, 0xff, 0x67, 0x05, 0x60, 0xc6, 0xc9, 0x58, 0x8b, 0xc4, 0x67, 0x22, 0xd4, 0xf1, 0xdb,
	0x9e, 0xac, 0x36, 0x54, 0xda, 0x7c, 0x13, 0x11, 0xdc, 0xb8, 0x07, 0xeb, 0xb8, 0x80, 0x2d, 0x08,
	0xfc, 0x8d, 0xa7, 0xed, 0x65, 0xa4, 0xc3, 0xb1, 0x5d, 0xdb, 0x9d, 0xb6, 0x08, 0x21, 0xb5, 0xcf,
	0x5c, 0x1d, 0x84, 0xa6, 0x0e, 0x37, 0x50, 0xab, 0xf7, 0x96, 0xea, 0x90, 0x4a, 0xe3, 0x44, 0xc9,
	0xcc, 0xff, 0xa3, 0x02, 0x0d, 0x87, 0x9b, 0x53, 0x29, 0x2c, 0x1b, 0xb6, 0x11, 0xa2, 0x55, 0xfb,
	0xd0, 0x08, 0xe7, 0x4d, 0xaa, 0x87, 0x64, 0xcf, 0x01, 0x34, 0x4d, 0xc8, 0x9e, 0xa5, 0x74, 0x8f,
	0x86, 0x4a, 0xda, 0x83, 0xd4, 0x56, 0x41, 0xa0, 0x12, 0x81, 0xa7, 0x8a, 0x7b, 0xbb, 0x84, 0x4a,
	0x3e, 0x23, 0xc8, 0x8d, 0x2f, 0xdb, 0x60, 0xc6, 0xa3, 0x0b, 0xfe, 0x33, 0xe8, 0x9e, 0x45, 0xf2,
	0x0d, 0x8f, 0xd0, 0xeb, 0x9e, 0x1f, 0xff, 0x56, 0xe1, 0x60, 0xe5, 0x8c, 0x74, 0xcb, 0xbf, 0x3b,
	0x95, 0xff, 0xb7, 0x53, 0xd9, 0x7f, 0xbe, 0x52, 0xfa, 0xb7, 0x79, 0x4c, 0x86, 0x70, 0x67, 0xf5,
	0x8c, 0xe4, 0xe6, 0x49, 0xa9, 0x19, 0x86, 0xf4, 0xf0, 0xfa, 0xa8, 0x44, 0xf2, 0xca, 0x3a, 0x98,
	0xf5, 0xc7, 0xf0, 0xd1, 0xdf, 0xeb, 0xc5, 0x83, 0xf3, 0x5c, 0xa4, 0x17, 0x51, 0x28, 0xbc, 0x27,
	0xb0, 0x65, 0x06, 0xbb, 0x87, 0xac, 0xd7, 0x59, 0x7c, 0xcc, 0xb9, 0x4d, 0x75, 0xf7, 0x57, 0x44,
	0xe8, 0xaa, 0x59, 0xf3, 0x8e, 0xa1, 0x55, 0x9a, 0xc6, 0xdb, 0x5b, 0x7a, 0x12, 0xd2, 0x24, 0x9d,
	0xe5, 0x40, 0x69, 0x0e, 0x7a, 0x6a, 0xba, 0x59, 0x6e, 0x17, 0xc9, 0x73, 0x4f, 0xd0, 0xee, 0xde,
	0x12, 0x5e, 0x9e, 0xc3, 0x3e, 0x5d, 0x96, 0xe7, 0x98, 0x7b, 0x40, 0x96, 0xe6, 0x58, 0x78, 0xea,
	0xac, 0x79, 0x01, 0x78, 0xcb, 0xd7, 0xaa, 0xe7, 0x17, 0x03, 0xae, 0x7c, 0x08, 0x75, 0x8f, 0xae,
	0xcd, 0x29, 0x16, 0x18, 0xc0, 0xad, 0x15, 0x86, 0x79, 0x47, 0xd7, 0xdb, 0x69, 0x97, 0x78, 0x2d,
	0xcf, 0xfd, 0x35, 0x4f, 0xc0, 0xfb, 0xab, 0xea, 0xc9, 0xbb, 0x76, 0x7c, 0xe1, 0xf5, 0xfd, 0x1b,
	0xb2, 0xdc, 0x32, 0x83, 0x4d, 0xfc, 0x9b, 0xff, 0xc5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a,
	0xc8, 0xc4, 0x21, 0xf7, 0x0f, 0x00, 0x00,
}
