// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package query

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 条件
type Condition struct {
	FieldId              string   `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id"`
	FieldType            string   `protobuf:"bytes,2,opt,name=field_type,json=fieldType,proto3" json:"field_type"`
	SearchValue          string   `protobuf:"bytes,3,opt,name=search_value,json=searchValue,proto3" json:"search_value"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator"`
	ConditionType        string   `protobuf:"bytes,5,opt,name=condition_type,json=conditionType,proto3" json:"condition_type"`
	IsDynamic            bool     `protobuf:"varint,6,opt,name=is_dynamic,json=isDynamic,proto3" json:"is_dynamic"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

func (m *Condition) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *Condition) GetSearchValue() string {
	if m != nil {
		return m.SearchValue
	}
	return ""
}

func (m *Condition) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Condition) GetConditionType() string {
	if m != nil {
		return m.ConditionType
	}
	return ""
}

func (m *Condition) GetIsDynamic() bool {
	if m != nil {
		return m.IsDynamic
	}
	return false
}

// 快捷方式
type Query struct {
	QueryId              string       `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id"`
	UserId               string       `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	DatastoreId          string       `protobuf:"bytes,3,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	QueryName            string       `protobuf:"bytes,4,opt,name=query_name,json=queryName,proto3" json:"query_name"`
	Description          string       `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	ConditionType        string       `protobuf:"bytes,7,opt,name=condition_type,json=conditionType,proto3" json:"condition_type"`
	Conditions           []*Condition `protobuf:"bytes,8,rep,name=conditions,proto3" json:"conditions"`
	Fields               []string     `protobuf:"bytes,15,rep,name=fields,proto3" json:"fields"`
	AppId                string       `protobuf:"bytes,16,opt,name=app_id,json=appId,proto3" json:"app_id"`
	CreatedAt            string       `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string       `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string       `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string       `protobuf:"bytes,12,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	DeletedAt            string       `protobuf:"bytes,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	DeletedBy            string       `protobuf:"bytes,14,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *Query) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Query) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *Query) GetQueryName() string {
	if m != nil {
		return m.QueryName
	}
	return ""
}

func (m *Query) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Query) GetConditionType() string {
	if m != nil {
		return m.ConditionType
	}
	return ""
}

func (m *Query) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Query) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Query) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Query) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Query) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Query) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Query) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Query) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Query) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

// 查找多个快捷方式
type FindQueriesRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	QueryName            string   `protobuf:"bytes,2,opt,name=query_name,json=queryName,proto3" json:"query_name"`
	DatastoreId          string   `protobuf:"bytes,3,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	AppId                string   `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindQueriesRequest) Reset()         { *m = FindQueriesRequest{} }
func (m *FindQueriesRequest) String() string { return proto.CompactTextString(m) }
func (*FindQueriesRequest) ProtoMessage()    {}
func (*FindQueriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2}
}

func (m *FindQueriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindQueriesRequest.Unmarshal(m, b)
}
func (m *FindQueriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindQueriesRequest.Marshal(b, m, deterministic)
}
func (m *FindQueriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindQueriesRequest.Merge(m, src)
}
func (m *FindQueriesRequest) XXX_Size() int {
	return xxx_messageInfo_FindQueriesRequest.Size(m)
}
func (m *FindQueriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindQueriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindQueriesRequest proto.InternalMessageInfo

func (m *FindQueriesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FindQueriesRequest) GetQueryName() string {
	if m != nil {
		return m.QueryName
	}
	return ""
}

func (m *FindQueriesRequest) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *FindQueriesRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FindQueriesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindQueriesResponse struct {
	QueryList            []*Query `protobuf:"bytes,1,rep,name=query_list,json=queryList,proto3" json:"query_list"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindQueriesResponse) Reset()         { *m = FindQueriesResponse{} }
func (m *FindQueriesResponse) String() string { return proto.CompactTextString(m) }
func (*FindQueriesResponse) ProtoMessage()    {}
func (*FindQueriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{3}
}

func (m *FindQueriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindQueriesResponse.Unmarshal(m, b)
}
func (m *FindQueriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindQueriesResponse.Marshal(b, m, deterministic)
}
func (m *FindQueriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindQueriesResponse.Merge(m, src)
}
func (m *FindQueriesResponse) XXX_Size() int {
	return xxx_messageInfo_FindQueriesResponse.Size(m)
}
func (m *FindQueriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindQueriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindQueriesResponse proto.InternalMessageInfo

func (m *FindQueriesResponse) GetQueryList() []*Query {
	if m != nil {
		return m.QueryList
	}
	return nil
}

// 查找单个快捷方式
type FindQueryRequest struct {
	QueryId              string   `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindQueryRequest) Reset()         { *m = FindQueryRequest{} }
func (m *FindQueryRequest) String() string { return proto.CompactTextString(m) }
func (*FindQueryRequest) ProtoMessage()    {}
func (*FindQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{4}
}

func (m *FindQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindQueryRequest.Unmarshal(m, b)
}
func (m *FindQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindQueryRequest.Marshal(b, m, deterministic)
}
func (m *FindQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindQueryRequest.Merge(m, src)
}
func (m *FindQueryRequest) XXX_Size() int {
	return xxx_messageInfo_FindQueryRequest.Size(m)
}
func (m *FindQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindQueryRequest proto.InternalMessageInfo

func (m *FindQueryRequest) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *FindQueryRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindQueryResponse struct {
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindQueryResponse) Reset()         { *m = FindQueryResponse{} }
func (m *FindQueryResponse) String() string { return proto.CompactTextString(m) }
func (*FindQueryResponse) ProtoMessage()    {}
func (*FindQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{5}
}

func (m *FindQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindQueryResponse.Unmarshal(m, b)
}
func (m *FindQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindQueryResponse.Marshal(b, m, deterministic)
}
func (m *FindQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindQueryResponse.Merge(m, src)
}
func (m *FindQueryResponse) XXX_Size() int {
	return xxx_messageInfo_FindQueryResponse.Size(m)
}
func (m *FindQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindQueryResponse proto.InternalMessageInfo

func (m *FindQueryResponse) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

// 添加单个快捷方式
type AddRequest struct {
	UserId               string       `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	DatastoreId          string       `protobuf:"bytes,2,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	QueryName            string       `protobuf:"bytes,3,opt,name=query_name,json=queryName,proto3" json:"query_name"`
	Description          string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Conditions           []*Condition `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions"`
	Fields               []string     `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields"`
	AppId                string       `protobuf:"bytes,10,opt,name=app_id,json=appId,proto3" json:"app_id"`
	ConditionType        string       `protobuf:"bytes,6,opt,name=condition_type,json=conditionType,proto3" json:"condition_type"`
	Writer               string       `protobuf:"bytes,7,opt,name=writer,proto3" json:"writer"`
	Database             string       `protobuf:"bytes,8,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{6}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddRequest) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *AddRequest) GetQueryName() string {
	if m != nil {
		return m.QueryName
	}
	return ""
}

func (m *AddRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddRequest) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *AddRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *AddRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddRequest) GetConditionType() string {
	if m != nil {
		return m.ConditionType
	}
	return ""
}

func (m *AddRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddResponse struct {
	QueryId              string   `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{7}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

// 删除单个快捷方式
type DeleteRequest struct {
	QueryId              string   `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *DeleteRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

// 删除多个快捷方式
type DeleteSelectQueriesRequest struct {
	QueryIdList          []string `protobuf:"bytes,1,rep,name=query_id_list,json=queryIdList,proto3" json:"query_id_list"`
	Writer               string   `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSelectQueriesRequest) Reset()         { *m = DeleteSelectQueriesRequest{} }
func (m *DeleteSelectQueriesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSelectQueriesRequest) ProtoMessage()    {}
func (*DeleteSelectQueriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{9}
}

func (m *DeleteSelectQueriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSelectQueriesRequest.Unmarshal(m, b)
}
func (m *DeleteSelectQueriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSelectQueriesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSelectQueriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSelectQueriesRequest.Merge(m, src)
}
func (m *DeleteSelectQueriesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSelectQueriesRequest.Size(m)
}
func (m *DeleteSelectQueriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSelectQueriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSelectQueriesRequest proto.InternalMessageInfo

func (m *DeleteSelectQueriesRequest) GetQueryIdList() []string {
	if m != nil {
		return m.QueryIdList
	}
	return nil
}

func (m *DeleteSelectQueriesRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteSelectQueriesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

// 物理删除多个快捷方式
type HardDeleteQueriesRequest struct {
	QueryIdList          []string `protobuf:"bytes,1,rep,name=query_id_list,json=queryIdList,proto3" json:"query_id_list"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardDeleteQueriesRequest) Reset()         { *m = HardDeleteQueriesRequest{} }
func (m *HardDeleteQueriesRequest) String() string { return proto.CompactTextString(m) }
func (*HardDeleteQueriesRequest) ProtoMessage()    {}
func (*HardDeleteQueriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{10}
}

func (m *HardDeleteQueriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardDeleteQueriesRequest.Unmarshal(m, b)
}
func (m *HardDeleteQueriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardDeleteQueriesRequest.Marshal(b, m, deterministic)
}
func (m *HardDeleteQueriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardDeleteQueriesRequest.Merge(m, src)
}
func (m *HardDeleteQueriesRequest) XXX_Size() int {
	return xxx_messageInfo_HardDeleteQueriesRequest.Size(m)
}
func (m *HardDeleteQueriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HardDeleteQueriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HardDeleteQueriesRequest proto.InternalMessageInfo

func (m *HardDeleteQueriesRequest) GetQueryIdList() []string {
	if m != nil {
		return m.QueryIdList
	}
	return nil
}

func (m *HardDeleteQueriesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{11}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Condition)(nil), "query.Condition")
	proto.RegisterType((*Query)(nil), "query.Query")
	proto.RegisterType((*FindQueriesRequest)(nil), "query.FindQueriesRequest")
	proto.RegisterType((*FindQueriesResponse)(nil), "query.FindQueriesResponse")
	proto.RegisterType((*FindQueryRequest)(nil), "query.FindQueryRequest")
	proto.RegisterType((*FindQueryResponse)(nil), "query.FindQueryResponse")
	proto.RegisterType((*AddRequest)(nil), "query.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "query.AddResponse")
	proto.RegisterType((*DeleteRequest)(nil), "query.DeleteRequest")
	proto.RegisterType((*DeleteSelectQueriesRequest)(nil), "query.DeleteSelectQueriesRequest")
	proto.RegisterType((*HardDeleteQueriesRequest)(nil), "query.HardDeleteQueriesRequest")
	proto.RegisterType((*DeleteResponse)(nil), "query.DeleteResponse")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4f, 0x4f, 0xdb, 0x4a,
	0x10, 0x7f, 0x49, 0x88, 0xb1, 0xc7, 0x09, 0x2f, 0x2c, 0x0f, 0x58, 0x2c, 0xa1, 0x17, 0x2c, 0x3d,
	0x29, 0xd2, 0x93, 0x50, 0x05, 0x87, 0x5e, 0x7a, 0x28, 0x14, 0xa1, 0x46, 0x6a, 0x2b, 0x11, 0xaa,
	0x1e, 0x7a, 0x68, 0xb4, 0xf1, 0x6e, 0xd5, 0x95, 0x42, 0x6c, 0xbc, 0x1b, 0x2a, 0x7f, 0x9d, 0xde,
	0xfb, 0x31, 0x7a, 0xe9, 0xb7, 0xe8, 0x37, 0xa9, 0xf6, 0x8f, 0x1d, 0xdb, 0x49, 0x80, 0x72, 0x9c,
	0xf9, 0xcd, 0xce, 0xcc, 0x6f, 0x7e, 0x33, 0x96, 0xc1, 0xbf, 0x9d, 0xb3, 0x34, 0x3b, 0x4e, 0xd2,
	0x58, 0xc6, 0xa8, 0xad, 0x8d, 0xf0, 0x67, 0x03, 0xbc, 0x57, 0xf1, 0x8c, 0x72, 0xc9, 0xe3, 0x19,
	0x3a, 0x00, 0xf7, 0x33, 0x67, 0x53, 0x3a, 0xe6, 0x14, 0x37, 0xfa, 0x8d, 0x81, 0x37, 0xda, 0xd4,
	0xf6, 0x90, 0xa2, 0x43, 0x00, 0x03, 0xc9, 0x2c, 0x61, 0xb8, 0xa9, 0x41, 0x4f, 0x7b, 0xde, 0x67,
	0x09, 0x43, 0x47, 0xd0, 0x11, 0x8c, 0xa4, 0xd1, 0x97, 0xf1, 0x1d, 0x99, 0xce, 0x19, 0x6e, 0xe9,
	0x00, 0xdf, 0xf8, 0x3e, 0x28, 0x17, 0x0a, 0xc0, 0x8d, 0x13, 0x96, 0x12, 0x19, 0xa7, 0x78, 0x43,
	0xc3, 0x85, 0x8d, 0xfe, 0x83, 0xad, 0x28, 0xef, 0xc2, 0x54, 0x68, 0xeb, 0x88, 0x6e, 0xe1, 0xd5,
	0x55, 0x0e, 0x01, 0xb8, 0x18, 0xd3, 0x6c, 0x46, 0x6e, 0x78, 0x84, 0x9d, 0x7e, 0x63, 0xe0, 0x8e,
	0x3c, 0x2e, 0x2e, 0x8c, 0x23, 0xfc, 0xd5, 0x82, 0xf6, 0x95, 0xa2, 0xa5, 0x88, 0x68, 0x7e, 0x25,
	0x22, 0xda, 0x1e, 0x52, 0xb4, 0x0f, 0x9b, 0x73, 0xc1, 0x52, 0x85, 0x18, 0x16, 0x8e, 0x32, 0x87,
	0x54, 0x51, 0xa0, 0x44, 0x12, 0x21, 0xe3, 0x94, 0x29, 0xd4, 0x52, 0x28, 0x7c, 0x66, 0x08, 0x26,
	0xed, 0x8c, 0xdc, 0x30, 0x4b, 0xc2, 0xd3, 0x9e, 0x77, 0xe4, 0x86, 0xa1, 0x3e, 0xf8, 0x94, 0x89,
	0x28, 0xe5, 0x89, 0xea, 0x58, 0xf7, 0xa7, 0x12, 0x2c, 0x5c, 0x2b, 0x78, 0x6e, 0xae, 0xe2, 0xf9,
	0x0c, 0xa0, 0x70, 0x08, 0xec, 0xf6, 0x5b, 0x03, 0xff, 0xa4, 0x77, 0x6c, 0xe4, 0x2b, 0xd4, 0x1a,
	0x95, 0x62, 0xd0, 0x1e, 0x38, 0x5a, 0x0c, 0x81, 0xff, 0xee, 0xb7, 0x14, 0x29, 0x63, 0xa1, 0x5d,
	0x70, 0x48, 0x92, 0x28, 0x3a, 0x3d, 0x5d, 0xa8, 0x4d, 0x92, 0xc4, 0x10, 0x89, 0x52, 0x46, 0x24,
	0xa3, 0x63, 0x22, 0xb1, 0x67, 0x88, 0x58, 0xcf, 0x99, 0x2c, 0xc3, 0x93, 0x0c, 0x43, 0x05, 0x3e,
	0xcf, 0x14, 0x3c, 0x4f, 0x68, 0xfe, 0xda, 0x37, 0xb0, 0xf5, 0x98, 0xd7, 0x39, 0x3c, 0xc9, 0x70,
	0xa7, 0x02, 0x9b, 0xd7, 0x94, 0x4d, 0x99, 0x7d, 0xdd, 0x35, 0xb0, 0xf5, 0x98, 0xd7, 0x39, 0x3c,
	0xc9, 0xf0, 0x56, 0x05, 0x3e, 0xcf, 0xc2, 0x6f, 0x0d, 0x40, 0x97, 0x7c, 0x46, 0x95, 0xce, 0x9c,
	0x89, 0x11, 0xbb, 0x9d, 0x33, 0x21, 0xcb, 0xaa, 0x36, 0x2a, 0xaa, 0x56, 0x25, 0x6b, 0xd6, 0x25,
	0x7b, 0x84, 0xe8, 0x8b, 0x11, 0xb6, 0xcb, 0x23, 0x0c, 0xc0, 0x55, 0x51, 0x13, 0x22, 0xf2, 0x4d,
	0x28, 0xec, 0xf0, 0x1c, 0x76, 0x2a, 0x3d, 0x8a, 0x24, 0x9e, 0x09, 0x86, 0xfe, 0xcf, 0x7b, 0x99,
	0x72, 0x21, 0x71, 0x43, 0xcb, 0xda, 0xb1, 0xb2, 0xea, 0xbd, 0xb5, 0x9d, 0xbd, 0xe1, 0x42, 0x86,
	0x43, 0xe8, 0xe5, 0x39, 0xb2, 0x9c, 0xe5, 0x3d, 0x6b, 0x5d, 0x6e, 0xa7, 0x59, 0x6b, 0xe7, 0x39,
	0x6c, 0x97, 0x52, 0xd9, 0x66, 0x42, 0x30, 0x9f, 0x00, 0x9d, 0xa8, 0xde, 0x87, 0xfd, 0x3a, 0xfc,
	0x68, 0x02, 0x9c, 0x51, 0xfa, 0xe0, 0x90, 0xeb, 0x53, 0x6c, 0x3e, 0x74, 0x3a, 0xad, 0x07, 0x4e,
	0x67, 0x63, 0xf9, 0x74, 0xaa, 0x37, 0xd1, 0xfe, 0xa3, 0x9b, 0xf0, 0xd6, 0xdc, 0x04, 0x94, 0x05,
	0x5d, 0xbe, 0x4d, 0x67, 0xd5, 0x6d, 0xee, 0x81, 0xf3, 0x35, 0xe5, 0x92, 0xa5, 0xf6, 0x74, 0xad,
	0x55, 0x11, 0xc0, 0xad, 0x09, 0x30, 0x00, 0x5f, 0x8f, 0xd1, 0x8e, 0x7e, 0xbd, 0x8c, 0xe1, 0x27,
	0xe8, 0x5e, 0xe8, 0x5d, 0x7f, 0x84, 0xe4, 0x8b, 0x4e, 0x9a, 0x6b, 0x3b, 0x69, 0xd5, 0x3a, 0x91,
	0x10, 0x98, 0xfc, 0xd7, 0x6c, 0xca, 0x22, 0x59, 0xbb, 0xa2, 0x10, 0xba, 0x79, 0xb1, 0xc5, 0x8e,
	0x7a, 0x23, 0xdf, 0x56, 0x54, 0x7b, 0xf9, 0xa4, 0xaa, 0x1f, 0x01, 0xbf, 0x26, 0x29, 0x35, 0x95,
	0x9f, 0x50, 0xf3, 0xbe, 0xe5, 0xee, 0xc1, 0x56, 0x3e, 0x31, 0x33, 0xde, 0x93, 0xef, 0x2d, 0xe8,
	0xe8, 0x35, 0xbe, 0x66, 0xe9, 0x1d, 0x8f, 0x18, 0xba, 0x04, 0xbf, 0x74, 0x8e, 0xe8, 0xc0, 0x6e,
	0xcd, 0xf2, 0x67, 0x24, 0x08, 0x56, 0x41, 0x26, 0x6d, 0xf8, 0x17, 0x7a, 0x09, 0x5e, 0x71, 0x47,
	0x68, 0xbf, 0x16, 0x9a, 0x1f, 0x69, 0x80, 0x97, 0x81, 0x22, 0xc3, 0x29, 0xb8, 0x67, 0xd4, 0x26,
	0xd8, 0xb6, 0x71, 0x8b, 0x03, 0x0b, 0x50, 0xd9, 0x55, 0x3c, 0x7a, 0x01, 0xfe, 0x62, 0x72, 0x19,
	0xfa, 0xc7, 0x06, 0x55, 0xf6, 0x24, 0xd8, 0xad, 0x79, 0x8b, 0xd7, 0x57, 0xb0, 0xb3, 0x42, 0x71,
	0x74, 0x54, 0x89, 0x5f, 0xb5, 0x0d, 0xeb, 0x53, 0xbe, 0x85, 0xed, 0x25, 0x39, 0xd1, 0xbf, 0x36,
	0x7a, 0x9d, 0xd0, 0x6b, 0xd3, 0x4d, 0x1c, 0xfd, 0x47, 0x72, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x39, 0x04, 0x1c, 0xa5, 0xa0, 0x08, 0x00, 0x00,
}
