// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template.proto

package template

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value struct {
	DataType             string   `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// 台账数据
type TemplateItem struct {
	ItemId               string            `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id"`
	AppId                string            `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id"`
	DatastoreId          string            `protobuf:"bytes,3,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	Items                map[string]*Value `protobuf:"bytes,4,rep,name=items,proto3" json:"items" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TemplateId           string            `protobuf:"bytes,6,opt,name=template_id,json=templateId,proto3" json:"template_id"`
	DatastoreKey         string            `protobuf:"bytes,7,opt,name=datastore_key,json=datastoreKey,proto3" json:"datastore_key"`
	CreatedAt            string            `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string            `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TemplateItem) Reset()         { *m = TemplateItem{} }
func (m *TemplateItem) String() string { return proto.CompactTextString(m) }
func (*TemplateItem) ProtoMessage()    {}
func (*TemplateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{1}
}

func (m *TemplateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateItem.Unmarshal(m, b)
}
func (m *TemplateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateItem.Marshal(b, m, deterministic)
}
func (m *TemplateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateItem.Merge(m, src)
}
func (m *TemplateItem) XXX_Size() int {
	return xxx_messageInfo_TemplateItem.Size(m)
}
func (m *TemplateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateItem.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateItem proto.InternalMessageInfo

func (m *TemplateItem) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *TemplateItem) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *TemplateItem) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *TemplateItem) GetItems() map[string]*Value {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *TemplateItem) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *TemplateItem) GetDatastoreKey() string {
	if m != nil {
		return m.DatastoreKey
	}
	return ""
}

func (m *TemplateItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *TemplateItem) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

// 查找多条记录
type ItemsRequest struct {
	TemplateId           string   `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id"`
	DatastoreKey         string   `protobuf:"bytes,2,opt,name=datastore_key,json=datastoreKey,proto3" json:"datastore_key"`
	PageIndex            int64    `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index"`
	PageSize             int64    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	Collection           string   `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsRequest) Reset()         { *m = ItemsRequest{} }
func (m *ItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ItemsRequest) ProtoMessage()    {}
func (*ItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{2}
}

func (m *ItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsRequest.Unmarshal(m, b)
}
func (m *ItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsRequest.Marshal(b, m, deterministic)
}
func (m *ItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsRequest.Merge(m, src)
}
func (m *ItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ItemsRequest.Size(m)
}
func (m *ItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsRequest proto.InternalMessageInfo

func (m *ItemsRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ItemsRequest) GetDatastoreKey() string {
	if m != nil {
		return m.DatastoreKey
	}
	return ""
}

func (m *ItemsRequest) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *ItemsRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ItemsRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *ItemsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type ItemsResponse struct {
	Items                []*TemplateItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	Total                int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ItemsResponse) Reset()         { *m = ItemsResponse{} }
func (m *ItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ItemsResponse) ProtoMessage()    {}
func (*ItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{3}
}

func (m *ItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsResponse.Unmarshal(m, b)
}
func (m *ItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsResponse.Marshal(b, m, deterministic)
}
func (m *ItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsResponse.Merge(m, src)
}
func (m *ItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ItemsResponse.Size(m)
}
func (m *ItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsResponse proto.InternalMessageInfo

func (m *ItemsResponse) GetItems() []*TemplateItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ItemsResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// MutilAddItem 批量添加数据(契约台账数据新规审批时，把支付，试算，偿却信息添加进来)
type MutilAddRequest struct {
	AppId                string       `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Data                 []*ListItems `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	Writer               string       `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer"`
	Collection           string       `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection"`
	Database             string       `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MutilAddRequest) Reset()         { *m = MutilAddRequest{} }
func (m *MutilAddRequest) String() string { return proto.CompactTextString(m) }
func (*MutilAddRequest) ProtoMessage()    {}
func (*MutilAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{4}
}

func (m *MutilAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutilAddRequest.Unmarshal(m, b)
}
func (m *MutilAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutilAddRequest.Marshal(b, m, deterministic)
}
func (m *MutilAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutilAddRequest.Merge(m, src)
}
func (m *MutilAddRequest) XXX_Size() int {
	return xxx_messageInfo_MutilAddRequest.Size(m)
}
func (m *MutilAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutilAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutilAddRequest proto.InternalMessageInfo

func (m *MutilAddRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *MutilAddRequest) GetData() []*ListItems {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MutilAddRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *MutilAddRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *MutilAddRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type MutilAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutilAddResponse) Reset()         { *m = MutilAddResponse{} }
func (m *MutilAddResponse) String() string { return proto.CompactTextString(m) }
func (*MutilAddResponse) ProtoMessage()    {}
func (*MutilAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{5}
}

func (m *MutilAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutilAddResponse.Unmarshal(m, b)
}
func (m *MutilAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutilAddResponse.Marshal(b, m, deterministic)
}
func (m *MutilAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutilAddResponse.Merge(m, src)
}
func (m *MutilAddResponse) XXX_Size() int {
	return xxx_messageInfo_MutilAddResponse.Size(m)
}
func (m *MutilAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutilAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutilAddResponse proto.InternalMessageInfo

type ListItems struct {
	Items                map[string]*Value `protobuf:"bytes,1,rep,name=items,proto3" json:"items" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DatastoreId          string            `protobuf:"bytes,2,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	TemplateId           string            `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id"`
	DatastoreKey         string            `protobuf:"bytes,4,opt,name=datastore_key,json=datastoreKey,proto3" json:"datastore_key"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListItems) Reset()         { *m = ListItems{} }
func (m *ListItems) String() string { return proto.CompactTextString(m) }
func (*ListItems) ProtoMessage()    {}
func (*ListItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{6}
}

func (m *ListItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItems.Unmarshal(m, b)
}
func (m *ListItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItems.Marshal(b, m, deterministic)
}
func (m *ListItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItems.Merge(m, src)
}
func (m *ListItems) XXX_Size() int {
	return xxx_messageInfo_ListItems.Size(m)
}
func (m *ListItems) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItems.DiscardUnknown(m)
}

var xxx_messageInfo_ListItems proto.InternalMessageInfo

func (m *ListItems) GetItems() map[string]*Value {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListItems) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *ListItems) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ListItems) GetDatastoreKey() string {
	if m != nil {
		return m.DatastoreKey
	}
	return ""
}

// 删除数据记录
type DeleteRequest struct {
	TemplateId           string   `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *DeleteRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *DeleteRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Value)(nil), "template.Value")
	proto.RegisterType((*TemplateItem)(nil), "template.TemplateItem")
	proto.RegisterMapType((map[string]*Value)(nil), "template.TemplateItem.ItemsEntry")
	proto.RegisterType((*ItemsRequest)(nil), "template.ItemsRequest")
	proto.RegisterType((*ItemsResponse)(nil), "template.ItemsResponse")
	proto.RegisterType((*MutilAddRequest)(nil), "template.MutilAddRequest")
	proto.RegisterType((*MutilAddResponse)(nil), "template.MutilAddResponse")
	proto.RegisterType((*ListItems)(nil), "template.ListItems")
	proto.RegisterMapType((map[string]*Value)(nil), "template.ListItems.ItemsEntry")
	proto.RegisterType((*DeleteRequest)(nil), "template.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "template.DeleteResponse")
}

func init() { proto.RegisterFile("template.proto", fileDescriptor_b1b68e1b5f001c74) }

var fileDescriptor_b1b68e1b5f001c74 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x76, 0x9c, 0xc6, 0x37, 0x69, 0x13, 0xa6, 0xa1, 0x35, 0x46, 0x94, 0xd6, 0x08, 0xd1,
	0x05, 0xca, 0x22, 0x20, 0x81, 0xca, 0xaa, 0x15, 0x54, 0x32, 0x0f, 0x21, 0x25, 0x15, 0x0b, 0x36,
	0x91, 0x93, 0xb9, 0x42, 0x23, 0x9c, 0xd8, 0xd8, 0x93, 0x82, 0xfb, 0x3f, 0xfc, 0x0d, 0x3f, 0xc2,
	0x07, 0xc0, 0x1a, 0xcd, 0xd8, 0x13, 0x3f, 0x12, 0xb5, 0x2c, 0xd8, 0x54, 0xbd, 0x8f, 0xdc, 0x7b,
	0xce, 0xb9, 0x67, 0x12, 0xd8, 0xe1, 0x38, 0x8f, 0x02, 0x9f, 0xe3, 0x20, 0x8a, 0x43, 0x1e, 0x92,
	0x96, 0x8a, 0xdd, 0x13, 0x30, 0x3f, 0xfa, 0xc1, 0x12, 0xc9, 0x3d, 0xb0, 0xa8, 0xcf, 0xfd, 0x09,
	0x4f, 0x23, 0xb4, 0xb5, 0x43, 0xed, 0xd8, 0x1a, 0xb5, 0x44, 0xe2, 0x22, 0x8d, 0x90, 0xf4, 0xc1,
	0xbc, 0x14, 0x5d, 0xb6, 0x2e, 0x0b, 0x59, 0xe0, 0xfe, 0xd2, 0xa1, 0x73, 0x91, 0x0f, 0xf2, 0x38,
	0xce, 0xc9, 0x3e, 0x6c, 0x31, 0x8e, 0xf3, 0x09, 0xa3, 0xf9, 0x84, 0xa6, 0x08, 0x3d, 0x4a, 0xee,
	0x40, 0xd3, 0x8f, 0x22, 0x91, 0xcf, 0x07, 0xf8, 0x51, 0xe4, 0x51, 0x72, 0x04, 0x1d, 0xb1, 0x22,
	0xe1, 0x61, 0x8c, 0xa2, 0x68, 0xc8, 0x62, 0x7b, 0x95, 0xf3, 0x28, 0x79, 0x0e, 0xa6, 0x98, 0x91,
	0xd8, 0x8d, 0x43, 0xe3, 0xb8, 0x3d, 0x3c, 0x1a, 0xac, 0x98, 0x94, 0x37, 0x0f, 0xc4, 0x9f, 0xe4,
	0xf5, 0x82, 0xc7, 0xe9, 0x28, 0xeb, 0x27, 0x0f, 0xa0, 0xad, 0x5a, 0xc5, 0xe8, 0xa6, 0x1c, 0x0d,
	0x2a, 0xe5, 0x51, 0xf2, 0x10, 0xb6, 0x8b, 0xe5, 0x5f, 0x30, 0xb5, 0xb7, 0x64, 0x4b, 0x81, 0xe8,
	0x2d, 0xa6, 0xe4, 0x3e, 0xc0, 0x2c, 0x46, 0x9f, 0x23, 0x9d, 0xf8, 0xdc, 0x6e, 0xc9, 0x0e, 0x2b,
	0xcf, 0x9c, 0xf2, 0x72, 0x79, 0x9a, 0xda, 0x56, 0xa5, 0x7c, 0x96, 0x3a, 0x1e, 0x40, 0x01, 0x8c,
	0xf4, 0xc0, 0x10, 0x6b, 0x32, 0x65, 0xc4, 0xbf, 0xe4, 0x51, 0x59, 0xd6, 0xf6, 0xb0, 0x5b, 0x90,
	0x93, 0x37, 0xc9, 0x75, 0x3e, 0xd1, 0x5f, 0x68, 0xee, 0x4f, 0x0d, 0x3a, 0x72, 0xd6, 0x08, 0xbf,
	0x2e, 0x31, 0xe1, 0x75, 0x7e, 0xda, 0xcd, 0xfc, 0xf4, 0xcd, 0xfc, 0x22, 0xff, 0x33, 0x4e, 0xd8,
	0x82, 0xe2, 0x77, 0xa9, 0xbf, 0x31, 0xb2, 0x44, 0xc6, 0x13, 0x09, 0x61, 0x0a, 0x59, 0x4e, 0xd8,
	0x15, 0xda, 0x0d, 0x59, 0x6d, 0x89, 0xc4, 0x98, 0x5d, 0x21, 0x39, 0x00, 0x98, 0x85, 0x41, 0x80,
	0x33, 0xce, 0xc2, 0x85, 0x6d, 0x66, 0x00, 0x8a, 0x0c, 0x71, 0x40, 0x1a, 0x68, 0xea, 0x27, 0x98,
	0xcb, 0xbf, 0x8a, 0xdd, 0x31, 0x6c, 0xe7, 0x6c, 0x92, 0x28, 0x5c, 0x24, 0x48, 0x9e, 0xa8, 0x3b,
	0x6b, 0xf2, 0xce, 0x7b, 0x9b, 0xef, 0xac, 0x8e, 0xdb, 0x07, 0x93, 0x87, 0xdc, 0x0f, 0x24, 0x27,
	0x63, 0x94, 0x05, 0xee, 0x0f, 0x0d, 0xba, 0xef, 0x97, 0x9c, 0x05, 0xa7, 0x94, 0x2a, 0x99, 0x0a,
	0xe7, 0x69, 0x65, 0xe7, 0x3d, 0x86, 0x86, 0xc0, 0x62, 0xeb, 0x72, 0xdb, 0x6e, 0xb1, 0xed, 0x1d,
	0x4b, 0x78, 0x86, 0x4c, 0x36, 0x90, 0x3d, 0x68, 0x7e, 0x8b, 0x19, 0xc7, 0x38, 0x37, 0x67, 0x1e,
	0xd5, 0xc8, 0x37, 0xae, 0x25, 0x6f, 0xd6, 0xc8, 0x13, 0xe8, 0x15, 0x30, 0x33, 0xfe, 0xee, 0x6f,
	0x0d, 0xac, 0xd5, 0x6e, 0xf2, 0xac, 0xaa, 0xc6, 0xc1, 0x06, 0x7c, 0x1b, 0x2c, 0x5f, 0x7f, 0x4e,
	0xfa, 0xfa, 0x73, 0xaa, 0xb9, 0xc6, 0xb8, 0xd9, 0x35, 0x8d, 0x75, 0xd7, 0xfc, 0x4f, 0x5f, 0x07,
	0xb0, 0xfd, 0x0a, 0x03, 0xe4, 0xf8, 0xcf, 0xbe, 0xae, 0x2a, 0xaf, 0x5f, 0xab, 0xbc, 0x51, 0x53,
	0xbe, 0x07, 0x3b, 0x6a, 0x5b, 0xa6, 0xfb, 0xf0, 0x8f, 0x06, 0x5d, 0xe5, 0xb0, 0x31, 0xc6, 0x97,
	0x6c, 0x86, 0xe4, 0x1c, 0x6e, 0x9f, 0xb3, 0x05, 0x2d, 0x1b, 0x2f, 0x21, 0x25, 0x47, 0x96, 0xdf,
	0xa1, 0xb3, 0xbf, 0x96, 0xcf, 0x2f, 0x7a, 0x8b, 0x7c, 0x80, 0xbe, 0xba, 0x73, 0xe5, 0x6b, 0xf2,
	0x6e, 0xf1, 0x91, 0x9a, 0x5d, 0x1d, 0x67, 0x53, 0x69, 0x35, 0xf0, 0x0d, 0xec, 0x66, 0xf0, 0xab,
	0xd0, 0x4a, 0x10, 0x2a, 0x5a, 0x3a, 0xf6, 0x7a, 0x41, 0xcd, 0x3a, 0xeb, 0x7c, 0x82, 0xc1, 0x4b,
	0x55, 0x9e, 0x36, 0xe5, 0xef, 0xc2, 0xd3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x6c, 0x58,
	0xcc, 0x29, 0x06, 0x00, 0x00,
}
