// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package group

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 用户组
type Group struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	ParentGroupId        string   `protobuf:"bytes,2,opt,name=parent_group_id,json=parentGroupId,proto3" json:"parent_group_id"`
	GroupName            string   `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	DisplayOrder         int64    `protobuf:"varint,4,opt,name=display_order,json=displayOrder,proto3" json:"display_order"`
	AccessKey            string   `protobuf:"bytes,5,opt,name=access_key,json=accessKey,proto3" json:"access_key"`
	Domain               string   `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string   `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string   `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	DeletedAt            string   `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	DeletedBy            string   `protobuf:"bytes,12,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Group) GetParentGroupId() string {
	if m != nil {
		return m.ParentGroupId
	}
	return ""
}

func (m *Group) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Group) GetDisplayOrder() int64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Group) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *Group) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Group) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Group) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Group) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Group) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Group) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Group) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

type FindGroupsRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	GroupName            string   `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGroupsRequest) Reset()         { *m = FindGroupsRequest{} }
func (m *FindGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*FindGroupsRequest) ProtoMessage()    {}
func (*FindGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *FindGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGroupsRequest.Unmarshal(m, b)
}
func (m *FindGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGroupsRequest.Marshal(b, m, deterministic)
}
func (m *FindGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGroupsRequest.Merge(m, src)
}
func (m *FindGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_FindGroupsRequest.Size(m)
}
func (m *FindGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindGroupsRequest proto.InternalMessageInfo

func (m *FindGroupsRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *FindGroupsRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *FindGroupsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindGroupsResponse struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGroupsResponse) Reset()         { *m = FindGroupsResponse{} }
func (m *FindGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*FindGroupsResponse) ProtoMessage()    {}
func (*FindGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *FindGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGroupsResponse.Unmarshal(m, b)
}
func (m *FindGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGroupsResponse.Marshal(b, m, deterministic)
}
func (m *FindGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGroupsResponse.Merge(m, src)
}
func (m *FindGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_FindGroupsResponse.Size(m)
}
func (m *FindGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindGroupsResponse proto.InternalMessageInfo

func (m *FindGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type FindGroupRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGroupRequest) Reset()         { *m = FindGroupRequest{} }
func (m *FindGroupRequest) String() string { return proto.CompactTextString(m) }
func (*FindGroupRequest) ProtoMessage()    {}
func (*FindGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *FindGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGroupRequest.Unmarshal(m, b)
}
func (m *FindGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGroupRequest.Marshal(b, m, deterministic)
}
func (m *FindGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGroupRequest.Merge(m, src)
}
func (m *FindGroupRequest) XXX_Size() int {
	return xxx_messageInfo_FindGroupRequest.Size(m)
}
func (m *FindGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindGroupRequest proto.InternalMessageInfo

func (m *FindGroupRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *FindGroupRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindGroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGroupResponse) Reset()         { *m = FindGroupResponse{} }
func (m *FindGroupResponse) String() string { return proto.CompactTextString(m) }
func (*FindGroupResponse) ProtoMessage()    {}
func (*FindGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *FindGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGroupResponse.Unmarshal(m, b)
}
func (m *FindGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGroupResponse.Marshal(b, m, deterministic)
}
func (m *FindGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGroupResponse.Merge(m, src)
}
func (m *FindGroupResponse) XXX_Size() int {
	return xxx_messageInfo_FindGroupResponse.Size(m)
}
func (m *FindGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindGroupResponse proto.InternalMessageInfo

func (m *FindGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type FindGroupAccessRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGroupAccessRequest) Reset()         { *m = FindGroupAccessRequest{} }
func (m *FindGroupAccessRequest) String() string { return proto.CompactTextString(m) }
func (*FindGroupAccessRequest) ProtoMessage()    {}
func (*FindGroupAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *FindGroupAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGroupAccessRequest.Unmarshal(m, b)
}
func (m *FindGroupAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGroupAccessRequest.Marshal(b, m, deterministic)
}
func (m *FindGroupAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGroupAccessRequest.Merge(m, src)
}
func (m *FindGroupAccessRequest) XXX_Size() int {
	return xxx_messageInfo_FindGroupAccessRequest.Size(m)
}
func (m *FindGroupAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGroupAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindGroupAccessRequest proto.InternalMessageInfo

func (m *FindGroupAccessRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *FindGroupAccessRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindGroupAccessResponse struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindGroupAccessResponse) Reset()         { *m = FindGroupAccessResponse{} }
func (m *FindGroupAccessResponse) String() string { return proto.CompactTextString(m) }
func (*FindGroupAccessResponse) ProtoMessage()    {}
func (*FindGroupAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *FindGroupAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindGroupAccessResponse.Unmarshal(m, b)
}
func (m *FindGroupAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindGroupAccessResponse.Marshal(b, m, deterministic)
}
func (m *FindGroupAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindGroupAccessResponse.Merge(m, src)
}
func (m *FindGroupAccessResponse) XXX_Size() int {
	return xxx_messageInfo_FindGroupAccessResponse.Size(m)
}
func (m *FindGroupAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindGroupAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindGroupAccessResponse proto.InternalMessageInfo

func (m *FindGroupAccessResponse) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

type AddGroupRequest struct {
	ParentGroupId        string   `protobuf:"bytes,1,opt,name=parent_group_id,json=parentGroupId,proto3" json:"parent_group_id"`
	GroupName            string   `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	DisplayOrder         int64    `protobuf:"varint,3,opt,name=display_order,json=displayOrder,proto3" json:"display_order"`
	Domain               string   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain"`
	Writer               string   `protobuf:"bytes,5,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupRequest) Reset()         { *m = AddGroupRequest{} }
func (m *AddGroupRequest) String() string { return proto.CompactTextString(m) }
func (*AddGroupRequest) ProtoMessage()    {}
func (*AddGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *AddGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupRequest.Unmarshal(m, b)
}
func (m *AddGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupRequest.Marshal(b, m, deterministic)
}
func (m *AddGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupRequest.Merge(m, src)
}
func (m *AddGroupRequest) XXX_Size() int {
	return xxx_messageInfo_AddGroupRequest.Size(m)
}
func (m *AddGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupRequest proto.InternalMessageInfo

func (m *AddGroupRequest) GetParentGroupId() string {
	if m != nil {
		return m.ParentGroupId
	}
	return ""
}

func (m *AddGroupRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *AddGroupRequest) GetDisplayOrder() int64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *AddGroupRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddGroupRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddGroupRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddGroupResponse struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupResponse) Reset()         { *m = AddGroupResponse{} }
func (m *AddGroupResponse) String() string { return proto.CompactTextString(m) }
func (*AddGroupResponse) ProtoMessage()    {}
func (*AddGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *AddGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupResponse.Unmarshal(m, b)
}
func (m *AddGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupResponse.Marshal(b, m, deterministic)
}
func (m *AddGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupResponse.Merge(m, src)
}
func (m *AddGroupResponse) XXX_Size() int {
	return xxx_messageInfo_AddGroupResponse.Size(m)
}
func (m *AddGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupResponse proto.InternalMessageInfo

func (m *AddGroupResponse) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type ModifyGroupRequest struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	ParentGroupId        string   `protobuf:"bytes,2,opt,name=parent_group_id,json=parentGroupId,proto3" json:"parent_group_id"`
	GroupName            string   `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	Writer               string   `protobuf:"bytes,4,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	Datastore            string   `protobuf:"bytes,9,opt,name=datastore,proto3" json:"datastore"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyGroupRequest) Reset()         { *m = ModifyGroupRequest{} }
func (m *ModifyGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyGroupRequest) ProtoMessage()    {}
func (*ModifyGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{9}
}

func (m *ModifyGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyGroupRequest.Unmarshal(m, b)
}
func (m *ModifyGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyGroupRequest.Marshal(b, m, deterministic)
}
func (m *ModifyGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyGroupRequest.Merge(m, src)
}
func (m *ModifyGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyGroupRequest.Size(m)
}
func (m *ModifyGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyGroupRequest proto.InternalMessageInfo

func (m *ModifyGroupRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *ModifyGroupRequest) GetParentGroupId() string {
	if m != nil {
		return m.ParentGroupId
	}
	return ""
}

func (m *ModifyGroupRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *ModifyGroupRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *ModifyGroupRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ModifyGroupRequest) GetDatastore() string {
	if m != nil {
		return m.Datastore
	}
	return ""
}

type ModifyGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyGroupResponse) Reset()         { *m = ModifyGroupResponse{} }
func (m *ModifyGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyGroupResponse) ProtoMessage()    {}
func (*ModifyGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{10}
}

func (m *ModifyGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyGroupResponse.Unmarshal(m, b)
}
func (m *ModifyGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyGroupResponse.Marshal(b, m, deterministic)
}
func (m *ModifyGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyGroupResponse.Merge(m, src)
}
func (m *ModifyGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyGroupResponse.Size(m)
}
func (m *ModifyGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyGroupResponse proto.InternalMessageInfo

type HardDeleteGroupsRequest struct {
	GroupIdList          []string `protobuf:"bytes,1,rep,name=group_id_list,json=groupIdList,proto3" json:"group_id_list"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardDeleteGroupsRequest) Reset()         { *m = HardDeleteGroupsRequest{} }
func (m *HardDeleteGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*HardDeleteGroupsRequest) ProtoMessage()    {}
func (*HardDeleteGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{11}
}

func (m *HardDeleteGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardDeleteGroupsRequest.Unmarshal(m, b)
}
func (m *HardDeleteGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardDeleteGroupsRequest.Marshal(b, m, deterministic)
}
func (m *HardDeleteGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardDeleteGroupsRequest.Merge(m, src)
}
func (m *HardDeleteGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_HardDeleteGroupsRequest.Size(m)
}
func (m *HardDeleteGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HardDeleteGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HardDeleteGroupsRequest proto.InternalMessageInfo

func (m *HardDeleteGroupsRequest) GetGroupIdList() []string {
	if m != nil {
		return m.GroupIdList
	}
	return nil
}

func (m *HardDeleteGroupsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type HardDeleteGroupsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardDeleteGroupsResponse) Reset()         { *m = HardDeleteGroupsResponse{} }
func (m *HardDeleteGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*HardDeleteGroupsResponse) ProtoMessage()    {}
func (*HardDeleteGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{12}
}

func (m *HardDeleteGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardDeleteGroupsResponse.Unmarshal(m, b)
}
func (m *HardDeleteGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardDeleteGroupsResponse.Marshal(b, m, deterministic)
}
func (m *HardDeleteGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardDeleteGroupsResponse.Merge(m, src)
}
func (m *HardDeleteGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_HardDeleteGroupsResponse.Size(m)
}
func (m *HardDeleteGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HardDeleteGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HardDeleteGroupsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Group)(nil), "group.Group")
	proto.RegisterType((*FindGroupsRequest)(nil), "group.FindGroupsRequest")
	proto.RegisterType((*FindGroupsResponse)(nil), "group.FindGroupsResponse")
	proto.RegisterType((*FindGroupRequest)(nil), "group.FindGroupRequest")
	proto.RegisterType((*FindGroupResponse)(nil), "group.FindGroupResponse")
	proto.RegisterType((*FindGroupAccessRequest)(nil), "group.FindGroupAccessRequest")
	proto.RegisterType((*FindGroupAccessResponse)(nil), "group.FindGroupAccessResponse")
	proto.RegisterType((*AddGroupRequest)(nil), "group.AddGroupRequest")
	proto.RegisterType((*AddGroupResponse)(nil), "group.AddGroupResponse")
	proto.RegisterType((*ModifyGroupRequest)(nil), "group.ModifyGroupRequest")
	proto.RegisterType((*ModifyGroupResponse)(nil), "group.ModifyGroupResponse")
	proto.RegisterType((*HardDeleteGroupsRequest)(nil), "group.HardDeleteGroupsRequest")
	proto.RegisterType((*HardDeleteGroupsResponse)(nil), "group.HardDeleteGroupsResponse")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xb5, 0xb0, 0x74, 0xe9, 0x05, 0x02, 0x8e, 0x11, 0x66, 0x1b, 0x57, 0x49, 0x35, 0x86, 0x17,
	0xf7, 0x61, 0x7d, 0xd0, 0x98, 0x98, 0xc8, 0x6a, 0x76, 0xdd, 0xf8, 0xb1, 0x49, 0x8d, 0x0f, 0x3e,
	0x35, 0x03, 0x33, 0x6b, 0x1a, 0x81, 0xd6, 0x4e, 0xd1, 0xf4, 0x17, 0xaa, 0xbf, 0x4a, 0xd3, 0xf9,
	0x28, 0xed, 0x14, 0x76, 0x4d, 0xf4, 0x8d, 0x39, 0xe7, 0xde, 0xdb, 0x39, 0xb7, 0xe7, 0x14, 0xe8,
	0x7c, 0x4e, 0xa2, 0x75, 0x7c, 0x14, 0x27, 0x51, 0x1a, 0xa1, 0x96, 0x38, 0x78, 0xbf, 0x1b, 0xd0,
	0x3a, 0xcb, 0x7f, 0xa1, 0x03, 0x68, 0x0b, 0x28, 0x08, 0x29, 0xb6, 0xc6, 0xd6, 0xc4, 0xf1, 0xf7,
	0xc5, 0xf9, 0x9c, 0xa2, 0x87, 0xd0, 0x8f, 0x49, 0xc2, 0x56, 0x69, 0x50, 0x54, 0x34, 0x44, 0x45,
	0x4f, 0xc2, 0x67, 0xaa, 0xee, 0x10, 0x40, 0x16, 0xac, 0xc8, 0x92, 0xe1, 0xa6, 0x28, 0x71, 0x04,
	0xf2, 0x9e, 0x2c, 0x19, 0xba, 0x0f, 0x3d, 0x1a, 0xf2, 0x78, 0x41, 0xb2, 0x20, 0x4a, 0x28, 0x4b,
	0xf0, 0xde, 0xd8, 0x9a, 0x34, 0xfd, 0xae, 0x02, 0x2f, 0x72, 0x2c, 0x9f, 0x41, 0xe6, 0x73, 0xc6,
	0x79, 0xf0, 0x85, 0x65, 0xb8, 0x25, 0x67, 0x48, 0xe4, 0x0d, 0xcb, 0xd0, 0x10, 0x6c, 0x1a, 0x2d,
	0x49, 0xb8, 0xc2, 0xb6, 0xa0, 0xd4, 0x29, 0x6f, 0x9b, 0x27, 0x8c, 0xa4, 0x8c, 0x06, 0x24, 0xc5,
	0xfb, 0xb2, 0x4d, 0x21, 0xd3, 0xb4, 0x4c, 0xcf, 0x32, 0xdc, 0xae, 0xd0, 0x27, 0x59, 0x4e, 0xaf,
	0x63, 0xaa, 0xbb, 0x1d, 0x49, 0x2b, 0x44, 0x76, 0x6b, 0x7a, 0x96, 0x61, 0xa8, 0xd0, 0xb2, 0x9b,
	0xb2, 0x05, 0x53, 0xdd, 0x1d, 0x49, 0x2b, 0x44, 0x76, 0x6b, 0x7a, 0x96, 0xe1, 0x6e, 0x85, 0x3e,
	0xc9, 0xbc, 0x4b, 0xb8, 0x79, 0x1a, 0xae, 0xa8, 0xd8, 0x21, 0xf7, 0xd9, 0xd7, 0x35, 0xe3, 0x69,
	0x49, 0xa6, 0x65, 0xca, 0x2c, 0x6d, 0xb8, 0x61, 0x6e, 0xd8, 0x85, 0x36, 0x25, 0x29, 0x99, 0x11,
	0xae, 0xd7, 0x5f, 0x9c, 0xbd, 0x67, 0x80, 0xca, 0xcf, 0xe1, 0x71, 0xb4, 0xe2, 0x0c, 0x3d, 0x00,
	0x5b, 0xb4, 0x73, 0x6c, 0x8d, 0x9b, 0x93, 0xce, 0x71, 0xf7, 0x48, 0x9a, 0x44, 0x94, 0xf9, 0x8a,
	0xf3, 0xce, 0x61, 0x50, 0xf4, 0xea, 0x2b, 0x5e, 0xe1, 0x97, 0xf2, 0x35, 0x1a, 0xc6, 0x35, 0x9e,
	0x94, 0xe4, 0x16, 0xb7, 0xf0, 0x40, 0xda, 0x51, 0x0c, 0x32, 0x2f, 0xa1, 0x9c, 0x7a, 0x01, 0xc3,
	0xa2, 0x71, 0x2a, 0xfc, 0xf0, 0x8f, 0x37, 0x79, 0x0a, 0xa3, 0xda, 0x40, 0x75, 0x9f, 0xaa, 0x09,
	0x2d, 0xc3, 0x84, 0xde, 0x2f, 0x0b, 0xfa, 0x53, 0x5a, 0x5d, 0xc7, 0x96, 0x8c, 0x58, 0xd7, 0x67,
	0xa4, 0x71, 0x6d, 0x46, 0x9a, 0x5b, 0x32, 0xb2, 0x71, 0xc7, 0x5e, 0xc5, 0x1d, 0x43, 0xb0, 0xbf,
	0x27, 0x61, 0xca, 0x12, 0x95, 0x1b, 0x75, 0xaa, 0x6c, 0xc1, 0x36, 0xb6, 0xf0, 0x08, 0x06, 0x1b,
	0x29, 0x4a, 0xfe, 0xee, 0x85, 0x7a, 0x3f, 0x2d, 0x40, 0xef, 0x22, 0x1a, 0x5e, 0x66, 0x7f, 0x6b,
	0x86, 0xff, 0xf4, 0xf1, 0xd8, 0x68, 0xdb, 0xdb, 0xa9, 0xad, 0x55, 0xd5, 0x86, 0xee, 0x80, 0x93,
	0xff, 0xe6, 0x69, 0x94, 0x30, 0x9d, 0xea, 0x02, 0xf0, 0x6e, 0xc3, 0xad, 0x8a, 0x12, 0x29, 0xde,
	0xfb, 0x04, 0xa3, 0xd7, 0x24, 0xa1, 0xaf, 0x44, 0x40, 0xab, 0xa9, 0xf4, 0xa0, 0xa7, 0x35, 0x04,
	0x8b, 0x90, 0xa7, 0x22, 0x33, 0x8e, 0xdf, 0x51, 0x52, 0xdf, 0x86, 0x3c, 0xbd, 0xd2, 0x71, 0x2e,
	0xe0, 0xfa, 0x68, 0xf9, 0xd8, 0xe3, 0x1f, 0x4d, 0xe8, 0x0a, 0xe8, 0x03, 0x4b, 0xbe, 0x85, 0x73,
	0x86, 0x5e, 0x02, 0x6c, 0xf2, 0x8a, 0xb0, 0x8a, 0x44, 0xed, 0x53, 0xe1, 0x1e, 0x6c, 0x61, 0x94,
	0x94, 0x1b, 0xe8, 0x05, 0x38, 0x05, 0x8e, 0x46, 0x66, 0xa5, 0x1e, 0x81, 0xeb, 0x44, 0x31, 0xc1,
	0x87, 0xbe, 0x91, 0x12, 0x74, 0x68, 0x96, 0x57, 0xe2, 0xe8, 0xde, 0xdd, 0x45, 0x17, 0x33, 0x9f,
	0x43, 0x5b, 0x7b, 0x0e, 0x0d, 0x55, 0xb5, 0x91, 0x27, 0x77, 0x54, 0xc3, 0x8b, 0xf6, 0x53, 0xe8,
	0x94, 0x5e, 0x1c, 0xd2, 0x0b, 0xa8, 0xdb, 0xd2, 0x75, 0xb7, 0x51, 0xc5, 0x9c, 0x8f, 0x30, 0x30,
	0x5f, 0x07, 0xd2, 0x97, 0xdf, 0x61, 0x01, 0xf7, 0xde, 0x4e, 0x5e, 0x8f, 0x9d, 0xd9, 0xe2, 0x0f,
	0xf6, 0xf1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x08, 0xae, 0x79, 0x6f, 0x07, 0x00, 0x00,
}
