// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subject.proto

package subject

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 科目
type Subject struct {
	SubjectKey           string   `protobuf:"bytes,1,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key"`
	SubjectName          string   `protobuf:"bytes,2,opt,name=subject_name,json=subjectName,proto3" json:"subject_name"`
	DefaultName          string   `protobuf:"bytes,3,opt,name=default_name,json=defaultName,proto3" json:"default_name"`
	AssetsType           string   `protobuf:"bytes,4,opt,name=assets_type,json=assetsType,proto3" json:"assets_type"`
	AppId                string   `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id"`
	JournalId            string   `protobuf:"bytes,6,opt,name=journal_id,json=journalId,proto3" json:"journal_id"`
	PatternId            string   `protobuf:"bytes,7,opt,name=pattern_id,json=patternId,proto3" json:"pattern_id"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string   `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string   `protobuf:"bytes,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subject) Reset()         { *m = Subject{} }
func (m *Subject) String() string { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()    {}
func (*Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{0}
}

func (m *Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subject.Unmarshal(m, b)
}
func (m *Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subject.Marshal(b, m, deterministic)
}
func (m *Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subject.Merge(m, src)
}
func (m *Subject) XXX_Size() int {
	return xxx_messageInfo_Subject.Size(m)
}
func (m *Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_Subject proto.InternalMessageInfo

func (m *Subject) GetSubjectKey() string {
	if m != nil {
		return m.SubjectKey
	}
	return ""
}

func (m *Subject) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *Subject) GetDefaultName() string {
	if m != nil {
		return m.DefaultName
	}
	return ""
}

func (m *Subject) GetAssetsType() string {
	if m != nil {
		return m.AssetsType
	}
	return ""
}

func (m *Subject) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Subject) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *Subject) GetPatternId() string {
	if m != nil {
		return m.PatternId
	}
	return ""
}

func (m *Subject) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Subject) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Subject) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Subject) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

// 查找多条记录
type SubjectsRequest struct {
	AssetsType           string   `protobuf:"bytes,1,opt,name=assets_type,json=assetsType,proto3" json:"assets_type"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubjectsRequest) Reset()         { *m = SubjectsRequest{} }
func (m *SubjectsRequest) String() string { return proto.CompactTextString(m) }
func (*SubjectsRequest) ProtoMessage()    {}
func (*SubjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{1}
}

func (m *SubjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectsRequest.Unmarshal(m, b)
}
func (m *SubjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectsRequest.Marshal(b, m, deterministic)
}
func (m *SubjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectsRequest.Merge(m, src)
}
func (m *SubjectsRequest) XXX_Size() int {
	return xxx_messageInfo_SubjectsRequest.Size(m)
}
func (m *SubjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectsRequest proto.InternalMessageInfo

func (m *SubjectsRequest) GetAssetsType() string {
	if m != nil {
		return m.AssetsType
	}
	return ""
}

func (m *SubjectsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SubjectsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type SubjectsResponse struct {
	Subjects             []*Subject `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SubjectsResponse) Reset()         { *m = SubjectsResponse{} }
func (m *SubjectsResponse) String() string { return proto.CompactTextString(m) }
func (*SubjectsResponse) ProtoMessage()    {}
func (*SubjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{2}
}

func (m *SubjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectsResponse.Unmarshal(m, b)
}
func (m *SubjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectsResponse.Marshal(b, m, deterministic)
}
func (m *SubjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectsResponse.Merge(m, src)
}
func (m *SubjectsResponse) XXX_Size() int {
	return xxx_messageInfo_SubjectsResponse.Size(m)
}
func (m *SubjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectsResponse proto.InternalMessageInfo

func (m *SubjectsResponse) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

// 查询单条记录
type SubjectRequest struct {
	SubjectKey           string   `protobuf:"bytes,1,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key"`
	AssetsType           string   `protobuf:"bytes,2,opt,name=assets_type,json=assetsType,proto3" json:"assets_type"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubjectRequest) Reset()         { *m = SubjectRequest{} }
func (m *SubjectRequest) String() string { return proto.CompactTextString(m) }
func (*SubjectRequest) ProtoMessage()    {}
func (*SubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{3}
}

func (m *SubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectRequest.Unmarshal(m, b)
}
func (m *SubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectRequest.Marshal(b, m, deterministic)
}
func (m *SubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectRequest.Merge(m, src)
}
func (m *SubjectRequest) XXX_Size() int {
	return xxx_messageInfo_SubjectRequest.Size(m)
}
func (m *SubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectRequest proto.InternalMessageInfo

func (m *SubjectRequest) GetSubjectKey() string {
	if m != nil {
		return m.SubjectKey
	}
	return ""
}

func (m *SubjectRequest) GetAssetsType() string {
	if m != nil {
		return m.AssetsType
	}
	return ""
}

func (m *SubjectRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SubjectRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type SubjectResponse struct {
	Subject              *Subject `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubjectResponse) Reset()         { *m = SubjectResponse{} }
func (m *SubjectResponse) String() string { return proto.CompactTextString(m) }
func (*SubjectResponse) ProtoMessage()    {}
func (*SubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{4}
}

func (m *SubjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectResponse.Unmarshal(m, b)
}
func (m *SubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectResponse.Marshal(b, m, deterministic)
}
func (m *SubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectResponse.Merge(m, src)
}
func (m *SubjectResponse) XXX_Size() int {
	return xxx_messageInfo_SubjectResponse.Size(m)
}
func (m *SubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectResponse proto.InternalMessageInfo

func (m *SubjectResponse) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

// 导入科目数据
type ImportRequest struct {
	Subjects             []*Subject `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects"`
	Database             string     `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	Writer               string     `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ImportRequest) Reset()         { *m = ImportRequest{} }
func (m *ImportRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()    {}
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{5}
}

func (m *ImportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRequest.Unmarshal(m, b)
}
func (m *ImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRequest.Marshal(b, m, deterministic)
}
func (m *ImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRequest.Merge(m, src)
}
func (m *ImportRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRequest.Size(m)
}
func (m *ImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRequest proto.InternalMessageInfo

func (m *ImportRequest) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *ImportRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ImportRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

type ImportResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportResponse) Reset()         { *m = ImportResponse{} }
func (m *ImportResponse) String() string { return proto.CompactTextString(m) }
func (*ImportResponse) ProtoMessage()    {}
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{6}
}

func (m *ImportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportResponse.Unmarshal(m, b)
}
func (m *ImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportResponse.Marshal(b, m, deterministic)
}
func (m *ImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportResponse.Merge(m, src)
}
func (m *ImportResponse) XXX_Size() int {
	return xxx_messageInfo_ImportResponse.Size(m)
}
func (m *ImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportResponse proto.InternalMessageInfo

// 更新记录
type ModifyRequest struct {
	SubjectKey           string   `protobuf:"bytes,1,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key"`
	AssetsType           string   `protobuf:"bytes,2,opt,name=assets_type,json=assetsType,proto3" json:"assets_type"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id"`
	SubjectName          string   `protobuf:"bytes,4,opt,name=subject_name,json=subjectName,proto3" json:"subject_name"`
	DefaultName          string   `protobuf:"bytes,5,opt,name=default_name,json=defaultName,proto3" json:"default_name"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	Writer               string   `protobuf:"bytes,7,opt,name=writer,proto3" json:"writer"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyRequest) Reset()         { *m = ModifyRequest{} }
func (m *ModifyRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequest) ProtoMessage()    {}
func (*ModifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{7}
}

func (m *ModifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequest.Unmarshal(m, b)
}
func (m *ModifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequest.Marshal(b, m, deterministic)
}
func (m *ModifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequest.Merge(m, src)
}
func (m *ModifyRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequest.Size(m)
}
func (m *ModifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequest proto.InternalMessageInfo

func (m *ModifyRequest) GetSubjectKey() string {
	if m != nil {
		return m.SubjectKey
	}
	return ""
}

func (m *ModifyRequest) GetAssetsType() string {
	if m != nil {
		return m.AssetsType
	}
	return ""
}

func (m *ModifyRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ModifyRequest) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *ModifyRequest) GetDefaultName() string {
	if m != nil {
		return m.DefaultName
	}
	return ""
}

func (m *ModifyRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ModifyRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

type ModifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyResponse) Reset()         { *m = ModifyResponse{} }
func (m *ModifyResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyResponse) ProtoMessage()    {}
func (*ModifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{8}
}

func (m *ModifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyResponse.Unmarshal(m, b)
}
func (m *ModifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyResponse.Marshal(b, m, deterministic)
}
func (m *ModifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyResponse.Merge(m, src)
}
func (m *ModifyResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyResponse.Size(m)
}
func (m *ModifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyResponse proto.InternalMessageInfo

// 删除数据记录
type DeleteRequest struct {
	SubjectKey           string   `protobuf:"bytes,1,opt,name=subject_key,json=subjectKey,proto3" json:"subject_key"`
	AssetsType           string   `protobuf:"bytes,2,opt,name=assets_type,json=assetsType,proto3" json:"assets_type"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetSubjectKey() string {
	if m != nil {
		return m.SubjectKey
	}
	return ""
}

func (m *DeleteRequest) GetAssetsType() string {
	if m != nil {
		return m.AssetsType
	}
	return ""
}

func (m *DeleteRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3181af8fcb9beccf, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Subject)(nil), "subject.Subject")
	proto.RegisterType((*SubjectsRequest)(nil), "subject.SubjectsRequest")
	proto.RegisterType((*SubjectsResponse)(nil), "subject.SubjectsResponse")
	proto.RegisterType((*SubjectRequest)(nil), "subject.SubjectRequest")
	proto.RegisterType((*SubjectResponse)(nil), "subject.SubjectResponse")
	proto.RegisterType((*ImportRequest)(nil), "subject.ImportRequest")
	proto.RegisterType((*ImportResponse)(nil), "subject.ImportResponse")
	proto.RegisterType((*ModifyRequest)(nil), "subject.ModifyRequest")
	proto.RegisterType((*ModifyResponse)(nil), "subject.ModifyResponse")
	proto.RegisterType((*DeleteRequest)(nil), "subject.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "subject.DeleteResponse")
}

func init() { proto.RegisterFile("subject.proto", fileDescriptor_3181af8fcb9beccf) }

var fileDescriptor_3181af8fcb9beccf = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xad, 0x9d, 0xc4, 0x49, 0xc6, 0x4d, 0x7e, 0xd1, 0x4a, 0xbf, 0x76, 0x89, 0x84, 0x5a, 0x7c,
	0xaa, 0x10, 0xea, 0xa1, 0x9c, 0x91, 0x20, 0x02, 0xa4, 0x0a, 0xc1, 0x21, 0xe5, 0x1e, 0xad, 0xe3,
	0xa9, 0xe4, 0x92, 0xd8, 0x5b, 0xef, 0x1a, 0xe4, 0x3b, 0x7c, 0xd1, 0x5e, 0xf8, 0x1a, 0x28, 0xde,
	0x59, 0xd7, 0x7f, 0xda, 0x20, 0x0e, 0x88, 0x5b, 0x3c, 0x6f, 0xf6, 0xed, 0xbc, 0xb7, 0x6f, 0x14,
	0x98, 0xa8, 0x3c, 0xbc, 0xc1, 0xb5, 0x3e, 0x97, 0x59, 0xaa, 0x53, 0x36, 0xa4, 0xcf, 0xe0, 0xce,
	0x85, 0xe1, 0x95, 0xf9, 0xcd, 0x4e, 0xc0, 0xa7, 0xf2, 0xea, 0x0b, 0x16, 0xdc, 0x39, 0x75, 0xce,
	0xc6, 0x4b, 0xa0, 0xd2, 0x07, 0x2c, 0xd8, 0x33, 0x38, 0xb4, 0x0d, 0x89, 0xd8, 0x22, 0x77, 0xcb,
	0x0e, 0x7b, 0xe8, 0x93, 0xd8, 0xe2, 0xae, 0x25, 0xc2, 0x6b, 0x91, 0x6f, 0xa8, 0xa5, 0x67, 0x5a,
	0xa8, 0x56, 0xb6, 0x9c, 0x80, 0x2f, 0x94, 0x42, 0xad, 0x56, 0xba, 0x90, 0xc8, 0xfb, 0xe6, 0x1a,
	0x53, 0xfa, 0x5c, 0x48, 0x64, 0xff, 0x83, 0x27, 0xa4, 0x5c, 0xc5, 0x11, 0x1f, 0x94, 0xd8, 0x40,
	0x48, 0x79, 0x19, 0xb1, 0xa7, 0x00, 0x37, 0x69, 0x9e, 0x25, 0x62, 0xb3, 0x83, 0xbc, 0x12, 0x1a,
	0x53, 0xc5, 0xc0, 0x52, 0x68, 0x8d, 0x59, 0xb2, 0x83, 0x87, 0x06, 0xa6, 0x8a, 0x81, 0xd7, 0x19,
	0x0a, 0x8d, 0xd1, 0x4a, 0x68, 0x3e, 0x32, 0x30, 0x55, 0xde, 0xe8, 0x3a, 0x1c, 0x16, 0x7c, 0xdc,
	0x80, 0x17, 0xc5, 0x0e, 0xce, 0x65, 0x64, 0x4f, 0x83, 0x81, 0xa9, 0x62, 0x4e, 0x5b, 0x38, 0x2c,
	0xb8, 0xdf, 0x80, 0x17, 0x45, 0x80, 0xf0, 0x1f, 0x79, 0xac, 0x96, 0x78, 0x9b, 0xa3, 0xd2, 0x6d,
	0x13, 0x9c, 0x3d, 0x26, 0xb8, 0x75, 0x13, 0xe6, 0x30, 0x8a, 0x84, 0x16, 0xa1, 0x50, 0xd6, 0xdb,
	0xea, 0x3b, 0x78, 0x0d, 0xb3, 0xfb, 0x6b, 0x94, 0x4c, 0x13, 0x85, 0xec, 0x05, 0x8c, 0xe8, 0x79,
	0x14, 0x77, 0x4e, 0x7b, 0x67, 0xfe, 0xc5, 0xec, 0xdc, 0x46, 0x81, 0x9a, 0x97, 0x55, 0x47, 0xf0,
	0xc3, 0x81, 0xa9, 0xad, 0xde, 0x0f, 0xba, 0x3f, 0x14, 0x2d, 0x25, 0xee, 0x1e, 0x25, 0xbd, 0xc7,
	0x94, 0xf4, 0x5b, 0x4a, 0x5e, 0x55, 0x86, 0x55, 0x42, 0x9e, 0x83, 0xcd, 0x6c, 0x39, 0xc3, 0x43,
	0x3a, 0xaa, 0x50, 0xdf, 0xc2, 0xe4, 0x72, 0x2b, 0xd3, 0xac, 0x12, 0xf1, 0x47, 0x2e, 0x34, 0x26,
	0x73, 0x9b, 0x93, 0xb1, 0x23, 0xf0, 0xbe, 0x65, 0xb1, 0xc6, 0x8c, 0xc4, 0xd0, 0x57, 0x30, 0x83,
	0xa9, 0xbd, 0xd2, 0x0c, 0x1c, 0xdc, 0x39, 0x30, 0xf9, 0x98, 0x46, 0xf1, 0x75, 0xf1, 0xd7, 0xad,
	0x6c, 0xef, 0x65, 0xff, 0xf7, 0x7b, 0x39, 0xe8, 0xee, 0x65, 0x5d, 0xb6, 0xf7, 0xa8, 0xec, 0x61,
	0x5b, 0xb6, 0xd5, 0x48, 0xb2, 0xbf, 0x3b, 0x30, 0x79, 0x8b, 0x1b, 0xd4, 0xf8, 0x4f, 0x13, 0x34,
	0x83, 0xa9, 0x9d, 0xc2, 0x0c, 0x76, 0xf1, 0xd3, 0xad, 0xb2, 0x7d, 0x85, 0xd9, 0xd7, 0x78, 0x8d,
	0xec, 0x1d, 0x1c, 0xbe, 0x8f, 0x93, 0xc8, 0x2e, 0x0d, 0xe3, 0xed, 0x50, 0xd8, 0x75, 0x9d, 0x3f,
	0x79, 0x00, 0x21, 0xc1, 0x07, 0x6c, 0x01, 0x7e, 0x8d, 0x86, 0x1d, 0x77, 0xa2, 0x45, 0x24, 0xbc,
	0x0b, 0xd4, 0x38, 0x28, 0xb2, 0x96, 0xe5, 0xa8, 0x6a, 0x6e, 0x44, 0x79, 0x7e, 0xdc, 0xa9, 0xd7,
	0x39, 0xcc, 0x63, 0x74, 0x39, 0x1a, 0x41, 0xac, 0x71, 0xb4, 0x1e, 0xaf, 0xe4, 0x30, 0xbe, 0x75,
	0x39, 0x1a, 0xaf, 0x5a, 0xe3, 0x68, 0xfa, 0x1c, 0x1c, 0x84, 0x5e, 0xf9, 0x1f, 0xf3, 0xf2, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0xf3, 0x7e, 0x50, 0x74, 0x06, 0x00, 0x00,
}
