// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed.proto

package feed

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 台账数据
type ImportItem struct {
	AppId                string            `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	DatastoreId          string            `protobuf:"bytes,2,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	MappingId            string            `protobuf:"bytes,6,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id"`
	JobId                string            `protobuf:"bytes,7,opt,name=job_id,json=jobId,proto3" json:"job_id"`
	Items                map[string]string `protobuf:"bytes,3,rep,name=items,proto3" json:"items" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt            string            `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string            `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ImportItem) Reset()         { *m = ImportItem{} }
func (m *ImportItem) String() string { return proto.CompactTextString(m) }
func (*ImportItem) ProtoMessage()    {}
func (*ImportItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{0}
}

func (m *ImportItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportItem.Unmarshal(m, b)
}
func (m *ImportItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportItem.Marshal(b, m, deterministic)
}
func (m *ImportItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportItem.Merge(m, src)
}
func (m *ImportItem) XXX_Size() int {
	return xxx_messageInfo_ImportItem.Size(m)
}
func (m *ImportItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportItem.DiscardUnknown(m)
}

var xxx_messageInfo_ImportItem proto.InternalMessageInfo

func (m *ImportItem) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ImportItem) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *ImportItem) GetMappingId() string {
	if m != nil {
		return m.MappingId
	}
	return ""
}

func (m *ImportItem) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ImportItem) GetItems() map[string]string {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ImportItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ImportItem) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

// 查找多条记录
type ImportsRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	DatastoreId          string   `protobuf:"bytes,2,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	JobId                string   `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id"`
	Writer               string   `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportsRequest) Reset()         { *m = ImportsRequest{} }
func (m *ImportsRequest) String() string { return proto.CompactTextString(m) }
func (*ImportsRequest) ProtoMessage()    {}
func (*ImportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{1}
}

func (m *ImportsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportsRequest.Unmarshal(m, b)
}
func (m *ImportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportsRequest.Marshal(b, m, deterministic)
}
func (m *ImportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportsRequest.Merge(m, src)
}
func (m *ImportsRequest) XXX_Size() int {
	return xxx_messageInfo_ImportsRequest.Size(m)
}
func (m *ImportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportsRequest proto.InternalMessageInfo

func (m *ImportsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ImportsRequest) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *ImportsRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ImportsRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *ImportsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type ImportsResponse struct {
	Items                []*ImportItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ImportsResponse) Reset()         { *m = ImportsResponse{} }
func (m *ImportsResponse) String() string { return proto.CompactTextString(m) }
func (*ImportsResponse) ProtoMessage()    {}
func (*ImportsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{2}
}

func (m *ImportsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportsResponse.Unmarshal(m, b)
}
func (m *ImportsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportsResponse.Marshal(b, m, deterministic)
}
func (m *ImportsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportsResponse.Merge(m, src)
}
func (m *ImportsResponse) XXX_Size() int {
	return xxx_messageInfo_ImportsResponse.Size(m)
}
func (m *ImportsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportsResponse proto.InternalMessageInfo

func (m *ImportsResponse) GetItems() []*ImportItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 查找多条记录
type ImportItemsRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	DatastoreId          string   `protobuf:"bytes,2,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	JobId                string   `protobuf:"bytes,6,opt,name=job_id,json=jobId,proto3" json:"job_id"`
	Writer               string   `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer"`
	MappingId            string   `protobuf:"bytes,4,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportItemsRequest) Reset()         { *m = ImportItemsRequest{} }
func (m *ImportItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ImportItemsRequest) ProtoMessage()    {}
func (*ImportItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{3}
}

func (m *ImportItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportItemsRequest.Unmarshal(m, b)
}
func (m *ImportItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportItemsRequest.Marshal(b, m, deterministic)
}
func (m *ImportItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportItemsRequest.Merge(m, src)
}
func (m *ImportItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ImportItemsRequest.Size(m)
}
func (m *ImportItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportItemsRequest proto.InternalMessageInfo

func (m *ImportItemsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ImportItemsRequest) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *ImportItemsRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ImportItemsRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *ImportItemsRequest) GetMappingId() string {
	if m != nil {
		return m.MappingId
	}
	return ""
}

func (m *ImportItemsRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type ImportItemsResponse struct {
	Items                []*ImportItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ImportItemsResponse) Reset()         { *m = ImportItemsResponse{} }
func (m *ImportItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ImportItemsResponse) ProtoMessage()    {}
func (*ImportItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{4}
}

func (m *ImportItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportItemsResponse.Unmarshal(m, b)
}
func (m *ImportItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportItemsResponse.Marshal(b, m, deterministic)
}
func (m *ImportItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportItemsResponse.Merge(m, src)
}
func (m *ImportItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ImportItemsResponse.Size(m)
}
func (m *ImportItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportItemsResponse proto.InternalMessageInfo

func (m *ImportItemsResponse) GetItems() []*ImportItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// 添加数据
type AddRequest struct {
	Items                []*ImportItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	Writer               string        `protobuf:"bytes,4,opt,name=writer,proto3" json:"writer"`
	Database             string        `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{5}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetItems() []*ImportItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *AddRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{6}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

// 删除数据记录
type DeleteRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	DatastoreId          string   `protobuf:"bytes,2,opt,name=datastore_id,json=datastoreId,proto3" json:"datastore_id"`
	JobId                string   `protobuf:"bytes,6,opt,name=job_id,json=jobId,proto3" json:"job_id"`
	Writer               string   `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer"`
	MappingId            string   `protobuf:"bytes,4,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteRequest) GetDatastoreId() string {
	if m != nil {
		return m.DatastoreId
	}
	return ""
}

func (m *DeleteRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *DeleteRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteRequest) GetMappingId() string {
	if m != nil {
		return m.MappingId
	}
	return ""
}

func (m *DeleteRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ImportItem)(nil), "feed.ImportItem")
	proto.RegisterMapType((map[string]string)(nil), "feed.ImportItem.ItemsEntry")
	proto.RegisterType((*ImportsRequest)(nil), "feed.ImportsRequest")
	proto.RegisterType((*ImportsResponse)(nil), "feed.ImportsResponse")
	proto.RegisterType((*ImportItemsRequest)(nil), "feed.ImportItemsRequest")
	proto.RegisterType((*ImportItemsResponse)(nil), "feed.ImportItemsResponse")
	proto.RegisterType((*AddRequest)(nil), "feed.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "feed.AddResponse")
	proto.RegisterType((*DeleteRequest)(nil), "feed.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "feed.DeleteResponse")
}

func init() { proto.RegisterFile("feed.proto", fileDescriptor_d7a672c1337cb5ac) }

var fileDescriptor_d7a672c1337cb5ac = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xcb, 0x6e, 0xd4, 0x30,
	0x14, 0x25, 0x93, 0x49, 0xa0, 0x77, 0x98, 0x76, 0x70, 0xa7, 0x28, 0x04, 0x21, 0x95, 0x2c, 0x50,
	0x57, 0x23, 0x51, 0x24, 0x54, 0x10, 0x08, 0x0d, 0x02, 0x44, 0xb6, 0xc3, 0x07, 0x54, 0x4e, 0x7d,
	0x81, 0x94, 0xce, 0xc4, 0xd8, 0x6e, 0x51, 0xfe, 0x82, 0x0d, 0xdf, 0xc0, 0x07, 0xb0, 0xe1, 0xf3,
	0x90, 0x1f, 0x49, 0x9c, 0x08, 0xa4, 0x22, 0xd8, 0x74, 0x13, 0xd9, 0xe7, 0x3e, 0x7c, 0xce, 0xb9,
	0x57, 0x01, 0x78, 0x8f, 0xc8, 0x16, 0x5c, 0x54, 0xaa, 0x22, 0x63, 0x7d, 0xce, 0xbe, 0x8f, 0x00,
	0xf2, 0x35, 0xaf, 0x84, 0xca, 0x15, 0xae, 0xc9, 0x1e, 0xc4, 0x94, 0xf3, 0xe3, 0x92, 0x25, 0xc1,
	0x7e, 0x70, 0xb0, 0xb5, 0x8a, 0x28, 0xe7, 0x39, 0x23, 0xf7, 0xe1, 0x26, 0xa3, 0x8a, 0x4a, 0x55,
	0x09, 0xd4, 0xc1, 0x91, 0x09, 0x4e, 0x5a, 0x2c, 0x67, 0xe4, 0x1e, 0xc0, 0x9a, 0x72, 0x5e, 0x6e,
	0x3e, 0xe8, 0x84, 0xd8, 0x24, 0x6c, 0x39, 0x24, 0x67, 0xba, 0xf1, 0x69, 0x55, 0xe8, 0xd0, 0x75,
	0xdb, 0xf8, 0xb4, 0x2a, 0x72, 0x46, 0x1e, 0x42, 0x54, 0x2a, 0x5c, 0xcb, 0x24, 0xdc, 0x0f, 0x0f,
	0x26, 0x87, 0x77, 0x17, 0x86, 0x60, 0x47, 0x68, 0xa1, 0x3f, 0xf2, 0xf5, 0x46, 0x89, 0x7a, 0x65,
	0x33, 0xf5, 0x43, 0x27, 0x02, 0xa9, 0x42, 0x76, 0x4c, 0x55, 0x32, 0xb6, 0x0f, 0x39, 0x64, 0xa9,
	0xfc, 0x70, 0x51, 0x27, 0x51, 0x2f, 0xfc, 0xb2, 0x4e, 0x8f, 0x00, 0xba, 0x96, 0x64, 0x06, 0xe1,
	0x27, 0xac, 0x9d, 0x56, 0x7d, 0x24, 0x73, 0x88, 0x2e, 0xe8, 0xd9, 0x39, 0x3a, 0x89, 0xf6, 0xf2,
	0x74, 0x74, 0x14, 0x64, 0xdf, 0x02, 0xd8, 0xb6, 0xc4, 0xe4, 0x0a, 0x3f, 0x9f, 0xa3, 0x54, 0xff,
	0xe0, 0x56, 0x67, 0x47, 0xe4, 0xdb, 0x71, 0x1b, 0xe2, 0x2f, 0xa2, 0x54, 0x28, 0x92, 0xd0, 0xc0,
	0xee, 0x46, 0x52, 0xb8, 0xa1, 0xab, 0x0b, 0x2a, 0xd1, 0x29, 0x6e, 0xef, 0xd9, 0x13, 0xd8, 0x69,
	0x69, 0x49, 0x5e, 0x6d, 0x24, 0x92, 0x07, 0x8d, 0xab, 0x81, 0x71, 0x75, 0x36, 0x74, 0xd5, 0x59,
	0x99, 0xfd, 0x0c, 0x80, 0x74, 0xe8, 0x7f, 0x95, 0x15, 0x5f, 0x46, 0x56, 0x7f, 0x67, 0xc6, 0xc3,
	0x9d, 0xf1, 0x55, 0x47, 0x03, 0xd5, 0xcf, 0x61, 0xb7, 0xc7, 0xfc, 0x2f, 0x95, 0x7f, 0x04, 0x58,
	0x32, 0xd6, 0x08, 0xbe, 0x64, 0x95, 0xa7, 0x63, 0xfc, 0xc7, 0xf1, 0x84, 0x03, 0xa2, 0x53, 0x98,
	0x98, 0x97, 0x2c, 0xc1, 0xec, 0x47, 0x00, 0xd3, 0x57, 0x78, 0x86, 0x0a, 0xaf, 0x92, 0xdb, 0x33,
	0xd8, 0x6e, 0x48, 0x5b, 0x1d, 0x87, 0x5f, 0x47, 0x30, 0xb5, 0x06, 0xbd, 0x43, 0x71, 0x51, 0x9e,
	0x20, 0x79, 0x06, 0x93, 0x37, 0xe5, 0x86, 0xb9, 0x5d, 0x24, 0x73, 0xdf, 0xc4, 0x66, 0xb5, 0xd2,
	0xbd, 0x01, 0xea, 0x5c, 0xb9, 0x46, 0xde, 0xc2, 0x4e, 0x57, 0x6d, 0x66, 0x4a, 0x92, 0xe1, 0x18,
	0xda, 0x2e, 0x77, 0x7e, 0x13, 0x69, 0x3b, 0x3d, 0x86, 0xe9, 0x92, 0x79, 0x8d, 0x88, 0x1b, 0x67,
	0x37, 0xef, 0xf4, 0x96, 0x87, 0xb4, 0x75, 0x2f, 0x60, 0x66, 0x35, 0x7a, 0xa5, 0xbb, 0x36, 0xb1,
	0x37, 0xb0, 0x74, 0xde, 0x07, 0x9b, 0x06, 0x45, 0x6c, 0xfe, 0xab, 0x8f, 0x7e, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x87, 0x62, 0xb2, 0x5d, 0x65, 0x05, 0x00, 0x00,
}
