// Code generated by protoc-gen-go. DO NOT EDIT.
// source: language.proto

package language

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 语言
type Language struct {
	LangCd               string          `protobuf:"bytes,1,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	Text                 string          `protobuf:"bytes,2,opt,name=text,proto3" json:"text"`
	Abbr                 string          `protobuf:"bytes,3,opt,name=abbr,proto3" json:"abbr"`
	Domain               string          `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain"`
	Apps                 map[string]*App `protobuf:"bytes,6,rep,name=apps,proto3" json:"apps" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Common               *Common         `protobuf:"bytes,14,opt,name=common,proto3" json:"common"`
	CreatedAt            string          `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	CreatedBy            string          `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	UpdatedAt            string          `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	UpdatedBy            string          `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by"`
	DeletedAt            string          `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	DeletedBy            string          `protobuf:"bytes,12,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Language) Reset()         { *m = Language{} }
func (m *Language) String() string { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()    {}
func (*Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{0}
}

func (m *Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Language.Unmarshal(m, b)
}
func (m *Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Language.Marshal(b, m, deterministic)
}
func (m *Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Language.Merge(m, src)
}
func (m *Language) XXX_Size() int {
	return xxx_messageInfo_Language.Size(m)
}
func (m *Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Language proto.InternalMessageInfo

func (m *Language) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *Language) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Language) GetAbbr() string {
	if m != nil {
		return m.Abbr
	}
	return ""
}

func (m *Language) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Language) GetApps() map[string]*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *Language) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Language) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Language) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Language) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Language) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Language) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Language) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

type Common struct {
	Groups               map[string]string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Workflows            map[string]string `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Common) Reset()         { *m = Common{} }
func (m *Common) String() string { return proto.CompactTextString(m) }
func (*Common) ProtoMessage()    {}
func (*Common) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{1}
}

func (m *Common) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common.Unmarshal(m, b)
}
func (m *Common) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common.Marshal(b, m, deterministic)
}
func (m *Common) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common.Merge(m, src)
}
func (m *Common) XXX_Size() int {
	return xxx_messageInfo_Common.Size(m)
}
func (m *Common) XXX_DiscardUnknown() {
	xxx_messageInfo_Common.DiscardUnknown(m)
}

var xxx_messageInfo_Common proto.InternalMessageInfo

func (m *Common) GetGroups() map[string]string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Common) GetWorkflows() map[string]string {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type App struct {
	AppName              string            `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name"`
	Datastores           map[string]string `protobuf:"bytes,2,rep,name=datastores,proto3" json:"datastores" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Fields               map[string]string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Queries              map[string]string `protobuf:"bytes,4,rep,name=queries,proto3" json:"queries" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Reports              map[string]string `protobuf:"bytes,5,rep,name=reports,proto3" json:"reports" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Dashboards           map[string]string `protobuf:"bytes,6,rep,name=dashboards,proto3" json:"dashboards" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Statuses             map[string]string `protobuf:"bytes,7,rep,name=statuses,proto3" json:"statuses" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Options              map[string]string `protobuf:"bytes,8,rep,name=options,proto3" json:"options" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Mappings             map[string]string `protobuf:"bytes,9,rep,name=mappings,proto3" json:"mappings" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Workflows            map[string]string `protobuf:"bytes,10,rep,name=workflows,proto3" json:"workflows" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{2}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *App) GetDatastores() map[string]string {
	if m != nil {
		return m.Datastores
	}
	return nil
}

func (m *App) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *App) GetQueries() map[string]string {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *App) GetReports() map[string]string {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *App) GetDashboards() map[string]string {
	if m != nil {
		return m.Dashboards
	}
	return nil
}

func (m *App) GetStatuses() map[string]string {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *App) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *App) GetMappings() map[string]string {
	if m != nil {
		return m.Mappings
	}
	return nil
}

func (m *App) GetWorkflows() map[string]string {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type LanData struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LanData) Reset()         { *m = LanData{} }
func (m *LanData) String() string { return proto.CompactTextString(m) }
func (*LanData) ProtoMessage()    {}
func (*LanData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{3}
}

func (m *LanData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LanData.Unmarshal(m, b)
}
func (m *LanData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LanData.Marshal(b, m, deterministic)
}
func (m *LanData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LanData.Merge(m, src)
}
func (m *LanData) XXX_Size() int {
	return xxx_messageInfo_LanData.Size(m)
}
func (m *LanData) XXX_DiscardUnknown() {
	xxx_messageInfo_LanData.DiscardUnknown(m)
}

var xxx_messageInfo_LanData proto.InternalMessageInfo

func (m *LanData) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *LanData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LanData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LanData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FindLanguagesRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLanguagesRequest) Reset()         { *m = FindLanguagesRequest{} }
func (m *FindLanguagesRequest) String() string { return proto.CompactTextString(m) }
func (*FindLanguagesRequest) ProtoMessage()    {}
func (*FindLanguagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{4}
}

func (m *FindLanguagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLanguagesRequest.Unmarshal(m, b)
}
func (m *FindLanguagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLanguagesRequest.Marshal(b, m, deterministic)
}
func (m *FindLanguagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLanguagesRequest.Merge(m, src)
}
func (m *FindLanguagesRequest) XXX_Size() int {
	return xxx_messageInfo_FindLanguagesRequest.Size(m)
}
func (m *FindLanguagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLanguagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindLanguagesRequest proto.InternalMessageInfo

func (m *FindLanguagesRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *FindLanguagesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindLanguagesResponse struct {
	LanguageList         []*Language `protobuf:"bytes,1,rep,name=language_list,json=languageList,proto3" json:"language_list"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FindLanguagesResponse) Reset()         { *m = FindLanguagesResponse{} }
func (m *FindLanguagesResponse) String() string { return proto.CompactTextString(m) }
func (*FindLanguagesResponse) ProtoMessage()    {}
func (*FindLanguagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{5}
}

func (m *FindLanguagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLanguagesResponse.Unmarshal(m, b)
}
func (m *FindLanguagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLanguagesResponse.Marshal(b, m, deterministic)
}
func (m *FindLanguagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLanguagesResponse.Merge(m, src)
}
func (m *FindLanguagesResponse) XXX_Size() int {
	return xxx_messageInfo_FindLanguagesResponse.Size(m)
}
func (m *FindLanguagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLanguagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindLanguagesResponse proto.InternalMessageInfo

func (m *FindLanguagesResponse) GetLanguageList() []*Language {
	if m != nil {
		return m.LanguageList
	}
	return nil
}

type FindLanguageRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	LangCd               string   `protobuf:"bytes,2,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLanguageRequest) Reset()         { *m = FindLanguageRequest{} }
func (m *FindLanguageRequest) String() string { return proto.CompactTextString(m) }
func (*FindLanguageRequest) ProtoMessage()    {}
func (*FindLanguageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{6}
}

func (m *FindLanguageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLanguageRequest.Unmarshal(m, b)
}
func (m *FindLanguageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLanguageRequest.Marshal(b, m, deterministic)
}
func (m *FindLanguageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLanguageRequest.Merge(m, src)
}
func (m *FindLanguageRequest) XXX_Size() int {
	return xxx_messageInfo_FindLanguageRequest.Size(m)
}
func (m *FindLanguageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLanguageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindLanguageRequest proto.InternalMessageInfo

func (m *FindLanguageRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *FindLanguageRequest) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *FindLanguageRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindLanguageResponse struct {
	Apps                 map[string]*App `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Common               *Common         `protobuf:"bytes,2,opt,name=common,proto3" json:"common"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FindLanguageResponse) Reset()         { *m = FindLanguageResponse{} }
func (m *FindLanguageResponse) String() string { return proto.CompactTextString(m) }
func (*FindLanguageResponse) ProtoMessage()    {}
func (*FindLanguageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{7}
}

func (m *FindLanguageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLanguageResponse.Unmarshal(m, b)
}
func (m *FindLanguageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLanguageResponse.Marshal(b, m, deterministic)
}
func (m *FindLanguageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLanguageResponse.Merge(m, src)
}
func (m *FindLanguageResponse) XXX_Size() int {
	return xxx_messageInfo_FindLanguageResponse.Size(m)
}
func (m *FindLanguageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLanguageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindLanguageResponse proto.InternalMessageInfo

func (m *FindLanguageResponse) GetApps() map[string]*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *FindLanguageResponse) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

type FindLanguageValueRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	LangCd               string   `protobuf:"bytes,2,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLanguageValueRequest) Reset()         { *m = FindLanguageValueRequest{} }
func (m *FindLanguageValueRequest) String() string { return proto.CompactTextString(m) }
func (*FindLanguageValueRequest) ProtoMessage()    {}
func (*FindLanguageValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{8}
}

func (m *FindLanguageValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLanguageValueRequest.Unmarshal(m, b)
}
func (m *FindLanguageValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLanguageValueRequest.Marshal(b, m, deterministic)
}
func (m *FindLanguageValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLanguageValueRequest.Merge(m, src)
}
func (m *FindLanguageValueRequest) XXX_Size() int {
	return xxx_messageInfo_FindLanguageValueRequest.Size(m)
}
func (m *FindLanguageValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLanguageValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindLanguageValueRequest proto.InternalMessageInfo

func (m *FindLanguageValueRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *FindLanguageValueRequest) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *FindLanguageValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FindLanguageValueRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type FindLanguageValueResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLanguageValueResponse) Reset()         { *m = FindLanguageValueResponse{} }
func (m *FindLanguageValueResponse) String() string { return proto.CompactTextString(m) }
func (*FindLanguageValueResponse) ProtoMessage()    {}
func (*FindLanguageValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{9}
}

func (m *FindLanguageValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLanguageValueResponse.Unmarshal(m, b)
}
func (m *FindLanguageValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLanguageValueResponse.Marshal(b, m, deterministic)
}
func (m *FindLanguageValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLanguageValueResponse.Merge(m, src)
}
func (m *FindLanguageValueResponse) XXX_Size() int {
	return xxx_messageInfo_FindLanguageValueResponse.Size(m)
}
func (m *FindLanguageValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLanguageValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindLanguageValueResponse proto.InternalMessageInfo

func (m *FindLanguageValueResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddLanguageRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	LangCd               string   `protobuf:"bytes,2,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text"`
	Abbr                 string   `protobuf:"bytes,4,opt,name=abbr,proto3" json:"abbr"`
	Writer               string   `protobuf:"bytes,5,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddLanguageRequest) Reset()         { *m = AddLanguageRequest{} }
func (m *AddLanguageRequest) String() string { return proto.CompactTextString(m) }
func (*AddLanguageRequest) ProtoMessage()    {}
func (*AddLanguageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{10}
}

func (m *AddLanguageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLanguageRequest.Unmarshal(m, b)
}
func (m *AddLanguageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLanguageRequest.Marshal(b, m, deterministic)
}
func (m *AddLanguageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLanguageRequest.Merge(m, src)
}
func (m *AddLanguageRequest) XXX_Size() int {
	return xxx_messageInfo_AddLanguageRequest.Size(m)
}
func (m *AddLanguageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLanguageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddLanguageRequest proto.InternalMessageInfo

func (m *AddLanguageRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddLanguageRequest) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *AddLanguageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *AddLanguageRequest) GetAbbr() string {
	if m != nil {
		return m.Abbr
	}
	return ""
}

func (m *AddLanguageRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddLanguageRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddLanguageResponse struct {
	LangCd               string   `protobuf:"bytes,1,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddLanguageResponse) Reset()         { *m = AddLanguageResponse{} }
func (m *AddLanguageResponse) String() string { return proto.CompactTextString(m) }
func (*AddLanguageResponse) ProtoMessage()    {}
func (*AddLanguageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{11}
}

func (m *AddLanguageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLanguageResponse.Unmarshal(m, b)
}
func (m *AddLanguageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLanguageResponse.Marshal(b, m, deterministic)
}
func (m *AddLanguageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLanguageResponse.Merge(m, src)
}
func (m *AddLanguageResponse) XXX_Size() int {
	return xxx_messageInfo_AddLanguageResponse.Size(m)
}
func (m *AddLanguageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLanguageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddLanguageResponse proto.InternalMessageInfo

func (m *AddLanguageResponse) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

type AddLanguageDataRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	LangCd               string   `protobuf:"bytes,2,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id"`
	AppName              string   `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name"`
	Writer               string   `protobuf:"bytes,5,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddLanguageDataRequest) Reset()         { *m = AddLanguageDataRequest{} }
func (m *AddLanguageDataRequest) String() string { return proto.CompactTextString(m) }
func (*AddLanguageDataRequest) ProtoMessage()    {}
func (*AddLanguageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{12}
}

func (m *AddLanguageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLanguageDataRequest.Unmarshal(m, b)
}
func (m *AddLanguageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLanguageDataRequest.Marshal(b, m, deterministic)
}
func (m *AddLanguageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLanguageDataRequest.Merge(m, src)
}
func (m *AddLanguageDataRequest) XXX_Size() int {
	return xxx_messageInfo_AddLanguageDataRequest.Size(m)
}
func (m *AddLanguageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLanguageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddLanguageDataRequest proto.InternalMessageInfo

func (m *AddLanguageDataRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddLanguageDataRequest) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *AddLanguageDataRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddLanguageDataRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AddLanguageDataRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddLanguageDataRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddAppLanguageDataRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	LangCd               string   `protobuf:"bytes,2,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value"`
	Writer               string   `protobuf:"bytes,7,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,8,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAppLanguageDataRequest) Reset()         { *m = AddAppLanguageDataRequest{} }
func (m *AddAppLanguageDataRequest) String() string { return proto.CompactTextString(m) }
func (*AddAppLanguageDataRequest) ProtoMessage()    {}
func (*AddAppLanguageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{13}
}

func (m *AddAppLanguageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAppLanguageDataRequest.Unmarshal(m, b)
}
func (m *AddAppLanguageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAppLanguageDataRequest.Marshal(b, m, deterministic)
}
func (m *AddAppLanguageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAppLanguageDataRequest.Merge(m, src)
}
func (m *AddAppLanguageDataRequest) XXX_Size() int {
	return xxx_messageInfo_AddAppLanguageDataRequest.Size(m)
}
func (m *AddAppLanguageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAppLanguageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAppLanguageDataRequest proto.InternalMessageInfo

func (m *AddAppLanguageDataRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddAppLanguageDataRequest) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *AddAppLanguageDataRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddAppLanguageDataRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddAppLanguageDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddAppLanguageDataRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AddAppLanguageDataRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddAppLanguageDataRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddManyLanDataRequest struct {
	Domain               string     `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	LangCd               string     `protobuf:"bytes,2,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	Lans                 []*LanData `protobuf:"bytes,3,rep,name=lans,proto3" json:"lans"`
	Writer               string     `protobuf:"bytes,4,opt,name=writer,proto3" json:"writer"`
	Database             string     `protobuf:"bytes,5,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddManyLanDataRequest) Reset()         { *m = AddManyLanDataRequest{} }
func (m *AddManyLanDataRequest) String() string { return proto.CompactTextString(m) }
func (*AddManyLanDataRequest) ProtoMessage()    {}
func (*AddManyLanDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{14}
}

func (m *AddManyLanDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddManyLanDataRequest.Unmarshal(m, b)
}
func (m *AddManyLanDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddManyLanDataRequest.Marshal(b, m, deterministic)
}
func (m *AddManyLanDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddManyLanDataRequest.Merge(m, src)
}
func (m *AddManyLanDataRequest) XXX_Size() int {
	return xxx_messageInfo_AddManyLanDataRequest.Size(m)
}
func (m *AddManyLanDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddManyLanDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddManyLanDataRequest proto.InternalMessageInfo

func (m *AddManyLanDataRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddManyLanDataRequest) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *AddManyLanDataRequest) GetLans() []*LanData {
	if m != nil {
		return m.Lans
	}
	return nil
}

func (m *AddManyLanDataRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddManyLanDataRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteAppLanguageDataRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key"`
	Writer               string   `protobuf:"bytes,5,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAppLanguageDataRequest) Reset()         { *m = DeleteAppLanguageDataRequest{} }
func (m *DeleteAppLanguageDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAppLanguageDataRequest) ProtoMessage()    {}
func (*DeleteAppLanguageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{15}
}

func (m *DeleteAppLanguageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppLanguageDataRequest.Unmarshal(m, b)
}
func (m *DeleteAppLanguageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppLanguageDataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAppLanguageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppLanguageDataRequest.Merge(m, src)
}
func (m *DeleteAppLanguageDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAppLanguageDataRequest.Size(m)
}
func (m *DeleteAppLanguageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppLanguageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppLanguageDataRequest proto.InternalMessageInfo

func (m *DeleteAppLanguageDataRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DeleteAppLanguageDataRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteAppLanguageDataRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DeleteAppLanguageDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteAppLanguageDataRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteAppLanguageDataRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type AddCommonDataRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	LangCd               string   `protobuf:"bytes,2,opt,name=lang_cd,json=langCd,proto3" json:"lang_cd"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value"`
	Writer               string   `protobuf:"bytes,7,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,8,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommonDataRequest) Reset()         { *m = AddCommonDataRequest{} }
func (m *AddCommonDataRequest) String() string { return proto.CompactTextString(m) }
func (*AddCommonDataRequest) ProtoMessage()    {}
func (*AddCommonDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{16}
}

func (m *AddCommonDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommonDataRequest.Unmarshal(m, b)
}
func (m *AddCommonDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommonDataRequest.Marshal(b, m, deterministic)
}
func (m *AddCommonDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommonDataRequest.Merge(m, src)
}
func (m *AddCommonDataRequest) XXX_Size() int {
	return xxx_messageInfo_AddCommonDataRequest.Size(m)
}
func (m *AddCommonDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommonDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommonDataRequest proto.InternalMessageInfo

func (m *AddCommonDataRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddCommonDataRequest) GetLangCd() string {
	if m != nil {
		return m.LangCd
	}
	return ""
}

func (m *AddCommonDataRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddCommonDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddCommonDataRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AddCommonDataRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *AddCommonDataRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteCommonDataRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key"`
	Writer               string   `protobuf:"bytes,5,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,6,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommonDataRequest) Reset()         { *m = DeleteCommonDataRequest{} }
func (m *DeleteCommonDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCommonDataRequest) ProtoMessage()    {}
func (*DeleteCommonDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{17}
}

func (m *DeleteCommonDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommonDataRequest.Unmarshal(m, b)
}
func (m *DeleteCommonDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommonDataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCommonDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommonDataRequest.Merge(m, src)
}
func (m *DeleteCommonDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCommonDataRequest.Size(m)
}
func (m *DeleteCommonDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommonDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommonDataRequest proto.InternalMessageInfo

func (m *DeleteCommonDataRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DeleteCommonDataRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DeleteCommonDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteCommonDataRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteCommonDataRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type DeleteLanguageDataRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id"`
	Writer               string   `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLanguageDataRequest) Reset()         { *m = DeleteLanguageDataRequest{} }
func (m *DeleteLanguageDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLanguageDataRequest) ProtoMessage()    {}
func (*DeleteLanguageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{18}
}

func (m *DeleteLanguageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLanguageDataRequest.Unmarshal(m, b)
}
func (m *DeleteLanguageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLanguageDataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLanguageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLanguageDataRequest.Merge(m, src)
}
func (m *DeleteLanguageDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLanguageDataRequest.Size(m)
}
func (m *DeleteLanguageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLanguageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLanguageDataRequest proto.InternalMessageInfo

func (m *DeleteLanguageDataRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DeleteLanguageDataRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteLanguageDataRequest) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *DeleteLanguageDataRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e123c61d1ddd0892, []int{19}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Language)(nil), "language.Language")
	proto.RegisterMapType((map[string]*App)(nil), "language.Language.AppsEntry")
	proto.RegisterType((*Common)(nil), "language.Common")
	proto.RegisterMapType((map[string]string)(nil), "language.Common.GroupsEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.Common.WorkflowsEntry")
	proto.RegisterType((*App)(nil), "language.App")
	proto.RegisterMapType((map[string]string)(nil), "language.App.DashboardsEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.DatastoresEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.FieldsEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.MappingsEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.OptionsEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.QueriesEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.ReportsEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.StatusesEntry")
	proto.RegisterMapType((map[string]string)(nil), "language.App.WorkflowsEntry")
	proto.RegisterType((*LanData)(nil), "language.LanData")
	proto.RegisterType((*FindLanguagesRequest)(nil), "language.FindLanguagesRequest")
	proto.RegisterType((*FindLanguagesResponse)(nil), "language.FindLanguagesResponse")
	proto.RegisterType((*FindLanguageRequest)(nil), "language.FindLanguageRequest")
	proto.RegisterType((*FindLanguageResponse)(nil), "language.FindLanguageResponse")
	proto.RegisterMapType((map[string]*App)(nil), "language.FindLanguageResponse.AppsEntry")
	proto.RegisterType((*FindLanguageValueRequest)(nil), "language.FindLanguageValueRequest")
	proto.RegisterType((*FindLanguageValueResponse)(nil), "language.FindLanguageValueResponse")
	proto.RegisterType((*AddLanguageRequest)(nil), "language.AddLanguageRequest")
	proto.RegisterType((*AddLanguageResponse)(nil), "language.AddLanguageResponse")
	proto.RegisterType((*AddLanguageDataRequest)(nil), "language.AddLanguageDataRequest")
	proto.RegisterType((*AddAppLanguageDataRequest)(nil), "language.AddAppLanguageDataRequest")
	proto.RegisterType((*AddManyLanDataRequest)(nil), "language.AddManyLanDataRequest")
	proto.RegisterType((*DeleteAppLanguageDataRequest)(nil), "language.DeleteAppLanguageDataRequest")
	proto.RegisterType((*AddCommonDataRequest)(nil), "language.AddCommonDataRequest")
	proto.RegisterType((*DeleteCommonDataRequest)(nil), "language.DeleteCommonDataRequest")
	proto.RegisterType((*DeleteLanguageDataRequest)(nil), "language.DeleteLanguageDataRequest")
	proto.RegisterType((*Response)(nil), "language.Response")
}

func init() { proto.RegisterFile("language.proto", fileDescriptor_e123c61d1ddd0892) }

var fileDescriptor_e123c61d1ddd0892 = []byte{
	// 1182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4d, 0x73, 0xdb, 0x44,
	0x18, 0xae, 0x2c, 0x59, 0xb6, 0x5f, 0x27, 0x69, 0xba, 0x4d, 0xda, 0x8d, 0x69, 0x9a, 0xa0, 0x0c,
	0x4c, 0x4e, 0x06, 0x42, 0x67, 0x4a, 0x43, 0x73, 0x70, 0x3f, 0xd2, 0x29, 0xa4, 0x14, 0xdc, 0x01,
	0x2e, 0x0c, 0x99, 0x75, 0xb4, 0x0d, 0x9a, 0xda, 0xd2, 0x56, 0x2b, 0x37, 0xe8, 0xc2, 0x8d, 0x13,
	0xbf, 0x82, 0xe1, 0xc0, 0x91, 0x23, 0x67, 0x2e, 0xfd, 0x03, 0xfc, 0x17, 0xce, 0x8c, 0xb4, 0xbb,
	0xf6, 0xae, 0x2c, 0x05, 0xec, 0x7e, 0xdc, 0xac, 0x7d, 0xde, 0xe7, 0xfd, 0xda, 0x7d, 0x3f, 0xc6,
	0xb0, 0x32, 0x24, 0xe1, 0xe9, 0x98, 0x9c, 0xd2, 0x2e, 0x8b, 0xa3, 0x24, 0x42, 0x4d, 0xf5, 0xed,
	0xfd, 0x65, 0x43, 0xf3, 0x48, 0x7e, 0xa0, 0xab, 0xd0, 0xc8, 0x80, 0xe3, 0x13, 0x1f, 0x5b, 0xdb,
	0xd6, 0x6e, 0xab, 0xef, 0x66, 0x9f, 0x77, 0x7d, 0x84, 0xc0, 0x49, 0xe8, 0x8f, 0x09, 0xae, 0xe5,
	0xa7, 0xf9, 0xef, 0xec, 0x8c, 0x0c, 0x06, 0x31, 0xb6, 0xc5, 0x59, 0xf6, 0x1b, 0x5d, 0x01, 0xd7,
	0x8f, 0x46, 0x24, 0x08, 0xb1, 0x23, 0xf8, 0xe2, 0x0b, 0x7d, 0x08, 0x0e, 0x61, 0x8c, 0x63, 0x77,
	0xdb, 0xde, 0x6d, 0xef, 0x5d, 0xeb, 0x4e, 0xdc, 0x51, 0xa6, 0xbb, 0x3d, 0xc6, 0xf8, 0xfd, 0x30,
	0x89, 0xd3, 0x7e, 0x2e, 0x89, 0x76, 0xc1, 0x3d, 0x89, 0x46, 0xa3, 0x28, 0xc4, 0x2b, 0xdb, 0xd6,
	0x6e, 0x7b, 0x6f, 0x75, 0xca, 0xb9, 0x9b, 0x9f, 0xf7, 0x25, 0x8e, 0x36, 0x01, 0x4e, 0x62, 0x4a,
	0x12, 0xea, 0x1f, 0x93, 0x04, 0x37, 0x72, 0xbb, 0x2d, 0x79, 0xd2, 0x4b, 0x74, 0x78, 0x90, 0xe2,
	0xa6, 0x01, 0xdf, 0x49, 0x33, 0x78, 0xcc, 0x7c, 0xc5, 0x6e, 0x09, 0x58, 0x9e, 0x08, 0xb6, 0x82,
	0x07, 0x29, 0x06, 0x03, 0x16, 0x6c, 0x9f, 0x0e, 0xa9, 0x64, 0xb7, 0x05, 0x2c, 0x4f, 0x04, 0x5b,
	0xc1, 0x83, 0x14, 0x2f, 0x19, 0xf0, 0x9d, 0xb4, 0x73, 0x08, 0xad, 0x49, 0xd8, 0x68, 0x15, 0xec,
	0x67, 0x34, 0x95, 0x79, 0xcf, 0x7e, 0xa2, 0x1d, 0xa8, 0xbf, 0x20, 0xc3, 0x31, 0xcd, 0xb3, 0xde,
	0xde, 0x5b, 0x9e, 0x66, 0xa0, 0xc7, 0x58, 0x5f, 0x60, 0xfb, 0xb5, 0x4f, 0x2c, 0xef, 0x1f, 0x0b,
	0x5c, 0x91, 0x14, 0x74, 0x03, 0xdc, 0xd3, 0x38, 0x1a, 0x33, 0x8e, 0xad, 0x62, 0xaa, 0x85, 0x44,
	0xf7, 0x41, 0x0e, 0x8b, 0x54, 0x4b, 0x59, 0x74, 0x00, 0xad, 0xb3, 0x28, 0x7e, 0xf6, 0x74, 0x18,
	0x9d, 0x71, 0x5c, 0xcb, 0x89, 0x5b, 0x33, 0xc4, 0x6f, 0x95, 0x84, 0xe0, 0x4e, 0x19, 0x9d, 0x5b,
	0xd0, 0xd6, 0xb4, 0x96, 0x44, 0xb2, 0xa6, 0x47, 0xd2, 0xd2, 0x5c, 0xef, 0xdc, 0x86, 0x15, 0x53,
	0xef, 0x3c, 0x6c, 0xef, 0x65, 0x13, 0xec, 0x1e, 0x63, 0x68, 0x03, 0x9a, 0x84, 0xb1, 0xe3, 0x90,
	0x8c, 0xa8, 0x24, 0x36, 0x08, 0x63, 0x5f, 0x90, 0x11, 0x45, 0x07, 0x00, 0x3e, 0x49, 0x08, 0x4f,
	0xa2, 0x98, 0xaa, 0xd8, 0x36, 0x8d, 0x4c, 0x76, 0xef, 0x4d, 0x70, 0x11, 0x99, 0x46, 0x40, 0x1f,
	0x81, 0xfb, 0x34, 0xa0, 0x43, 0x9f, 0x63, 0x3b, 0xa7, 0x6e, 0x98, 0xd4, 0xc3, 0x1c, 0x93, 0xc9,
	0x14, 0x82, 0xe8, 0x06, 0x34, 0x9e, 0x8f, 0x69, 0x1c, 0x50, 0x8e, 0x9d, 0x9c, 0xd3, 0x31, 0x39,
	0x5f, 0x09, 0x50, 0x90, 0x94, 0x68, 0xc6, 0x8a, 0x29, 0x8b, 0xe2, 0x84, 0xe3, 0x7a, 0x19, 0xab,
	0x2f, 0x40, 0xc9, 0x92, 0xa2, 0x22, 0x3a, 0xfe, 0xc3, 0x20, 0x22, 0xb1, 0xaf, 0xaa, 0x6b, 0x26,
	0x3a, 0x85, 0x4f, 0xa2, 0x53, 0x07, 0xe8, 0x26, 0x34, 0x79, 0x42, 0x92, 0x31, 0xa7, 0x1c, 0x37,
	0x72, 0xf2, 0x3b, 0x26, 0xf9, 0x89, 0x44, 0x05, 0x75, 0x22, 0x9c, 0x79, 0x1b, 0xb1, 0x24, 0x88,
	0x42, 0x8e, 0x9b, 0x65, 0xde, 0x3e, 0x16, 0xa0, 0xf4, 0x56, 0x8a, 0x66, 0xe6, 0x46, 0x84, 0xb1,
	0x20, 0x3c, 0xe5, 0xb8, 0x55, 0x66, 0xee, 0x91, 0x44, 0xa5, 0x39, 0x25, 0x8c, 0xf6, 0xf5, 0xf7,
	0x09, 0xc5, 0x87, 0x9d, 0x31, 0xab, 0x1f, 0xe7, 0x01, 0x5c, 0x2c, 0x5c, 0xf0, 0x5c, 0x0f, 0xf4,
	0x16, 0xb4, 0xb5, 0x4b, 0x9e, 0x8b, 0xba, 0x0f, 0x4b, 0xfa, 0x5d, 0xcf, 0xcb, 0xd5, 0x6f, 0x7c,
	0x2e, 0x6e, 0x1e, 0xb1, 0x71, 0xe9, 0x73, 0xd1, 0x3f, 0x85, 0x65, 0xe3, 0xda, 0xe7, 0xf5, 0x5b,
	0xbf, 0xfb, 0x79, 0x0d, 0x1b, 0x0f, 0xe0, 0x2d, 0x36, 0x92, 0xef, 0xa0, 0x71, 0x44, 0xc2, 0xec,
	0x9d, 0xa0, 0x75, 0x70, 0xb3, 0x5e, 0x12, 0xa8, 0x11, 0x58, 0x27, 0x8c, 0x3d, 0x14, 0x13, 0x30,
	0x65, 0x74, 0x32, 0x01, 0x53, 0x46, 0x95, 0x05, 0xbb, 0xc4, 0x82, 0xa3, 0x59, 0xf0, 0x3e, 0x83,
	0xb5, 0xc3, 0x20, 0xf4, 0xd5, 0xac, 0xe3, 0x7d, 0xfa, 0x7c, 0x4c, 0x79, 0xa2, 0x4d, 0x4b, 0xcb,
	0x98, 0x96, 0x1d, 0x68, 0x66, 0x2d, 0x68, 0x40, 0xb8, 0xb2, 0x37, 0xf9, 0xf6, 0xbe, 0x84, 0xf5,
	0x82, 0x2e, 0xce, 0xa2, 0x90, 0x53, 0x74, 0x13, 0x96, 0x55, 0x45, 0x1c, 0x0f, 0x03, 0x9e, 0xc8,
	0x01, 0x80, 0x66, 0x67, 0x6d, 0x7f, 0x49, 0x1d, 0x1d, 0x05, 0x3c, 0xf1, 0x06, 0x70, 0x59, 0xd7,
	0xf8, 0x5f, 0xce, 0x69, 0x3b, 0x42, 0xcd, 0xd8, 0x11, 0x74, 0xaf, 0xed, 0x82, 0xd7, 0x2f, 0x2d,
	0x33, 0x05, 0x13, 0xaf, 0x6f, 0xcb, 0xc5, 0x40, 0x38, 0xbb, 0x3b, 0x75, 0xb6, 0x4c, 0xfa, 0x9c,
	0x25, 0xa1, 0x76, 0xfe, 0x92, 0xf0, 0xda, 0x46, 0x6d, 0x0a, 0x58, 0xf7, 0xec, 0x9b, 0x0c, 0x58,
	0x38, 0x63, 0xd2, 0x0f, 0x67, 0xea, 0xc7, 0x79, 0x39, 0xfc, 0x00, 0x36, 0x4a, 0x4c, 0xcb, 0x3c,
	0x22, 0x70, 0xb4, 0xe9, 0x97, 0xff, 0xf6, 0x7e, 0xb5, 0x00, 0xf5, 0xfc, 0x57, 0xbf, 0x58, 0xb5,
	0xfc, 0xd9, 0x25, 0xcb, 0x9f, 0x63, 0x2e, 0x7f, 0x67, 0x71, 0x90, 0xd0, 0x18, 0xd7, 0x05, 0x5f,
	0x7c, 0x19, 0x41, 0xb9, 0x85, 0xa0, 0xba, 0x70, 0xd9, 0x70, 0x51, 0x86, 0x53, 0xb5, 0x88, 0x7a,
	0x7f, 0x58, 0x70, 0x45, 0x23, 0x64, 0x15, 0xbb, 0x70, 0x5c, 0xd3, 0x4a, 0xb7, 0xf5, 0x4a, 0xd7,
	0x97, 0x09, 0xc7, 0x5c, 0x26, 0x16, 0x89, 0xf0, 0x6f, 0x0b, 0x36, 0x7a, 0xbe, 0xdf, 0x63, 0xec,
	0x4d, 0x3a, 0xad, 0xda, 0x93, 0x33, 0xdb, 0x9e, 0xea, 0x25, 0xed, 0xc9, 0xd5, 0xda, 0x93, 0x16,
	0x55, 0xa3, 0x32, 0xaa, 0x66, 0x21, 0xaa, 0xdf, 0x2c, 0x58, 0xef, 0xf9, 0xfe, 0x23, 0x12, 0xa6,
	0xb2, 0x71, 0x2e, 0x1c, 0xd1, 0x7b, 0xe0, 0x0c, 0x49, 0xa8, 0x16, 0xac, 0x4b, 0x46, 0xbf, 0xca,
	0x15, 0xe7, 0xb0, 0xe6, 0xa5, 0x53, 0xe9, 0x65, 0xbd, 0xe0, 0xe5, 0xef, 0x16, 0x5c, 0xbb, 0x97,
	0xaf, 0xdb, 0x73, 0xa6, 0x7f, 0x9a, 0xe5, 0x5a, 0x59, 0x96, 0xed, 0xd9, 0x2c, 0x6b, 0x45, 0xbc,
	0xc8, 0x2b, 0xf9, 0xd3, 0x82, 0xb5, 0x9e, 0xef, 0x8b, 0xae, 0xf5, 0x4a, 0xe9, 0x7c, 0xdb, 0x2f,
	0xe1, 0x17, 0x0b, 0xae, 0x8a, 0x1c, 0xff, 0x7f, 0xe7, 0xdf, 0x5c, 0x1e, 0x7f, 0x82, 0x0d, 0xe1,
	0xcc, 0x6b, 0xb8, 0xed, 0xa9, 0x7d, 0xbb, 0xd2, 0xbe, 0x53, 0xb0, 0x0f, 0xd0, 0x54, 0x4d, 0x6c,
	0xef, 0xe7, 0x06, 0x5c, 0x54, 0x6e, 0x3c, 0xa1, 0xf1, 0x8b, 0xe0, 0x84, 0xa2, 0x3e, 0x2c, 0x1b,
	0xe3, 0x1b, 0x5d, 0x2f, 0x1f, 0x79, 0x6a, 0x47, 0xe8, 0x6c, 0x55, 0xe2, 0xc2, 0x8a, 0x77, 0x01,
	0x3d, 0x86, 0x25, 0x1d, 0x42, 0x9b, 0x55, 0x53, 0x54, 0x68, 0xbc, 0x7e, 0xfe, 0x90, 0xf5, 0x2e,
	0xa0, 0xef, 0xe1, 0xd2, 0xcc, 0xa4, 0x41, 0x5e, 0x39, 0x4d, 0x9f, 0x80, 0x9d, 0x9d, 0x73, 0x65,
	0x26, 0xfa, 0x8f, 0xa0, 0xad, 0xf5, 0x70, 0xa4, 0xaf, 0xf2, 0x33, 0xe3, 0xaa, 0xb3, 0x59, 0x81,
	0x4e, 0xb4, 0x3d, 0x84, 0x8b, 0x85, 0x89, 0x80, 0xb6, 0x4b, 0x39, 0xda, 0x53, 0xe8, 0x68, 0x6b,
	0x91, 0x91, 0x49, 0x34, 0xdb, 0xaa, 0xd1, 0x8e, 0xa1, 0xad, 0xbc, 0x93, 0x54, 0x28, 0xbc, 0x0f,
	0xcb, 0x46, 0x55, 0xeb, 0xd7, 0x5d, 0x56, 0xee, 0x15, 0x6a, 0x1e, 0xc0, 0x8a, 0xd9, 0x6c, 0xd1,
	0x96, 0xa1, 0x67, 0xb6, 0x0d, 0x57, 0x28, 0xfa, 0x1c, 0x56, 0x8b, 0xb5, 0x8a, 0xde, 0x9d, 0x4a,
	0x56, 0xd4, 0x71, 0x75, 0xb6, 0x66, 0x6b, 0x4d, 0xcf, 0x56, 0x65, 0x25, 0x56, 0x28, 0xfc, 0x1a,
	0xd6, 0x4b, 0xbb, 0x35, 0x7a, 0xbf, 0xa8, 0x73, 0x9e, 0x4b, 0x18, 0xb8, 0xf9, 0x7f, 0x5e, 0x1f,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x13, 0x0e, 0x33, 0x89, 0x05, 0x13, 0x00, 0x00,
}
